### ISSUE TITLE
Trackers being assigned to controllers.

### ISSUE THREAD

**Issue by Sox-NeosVR** [Neos-Metaverse/NeosPublic#2423] opened 2021-06-06 21:58 UTC
## Describe the bug
Trackers appearing on controllers.

## Relevant issues
When switching between different pairs of index controllers (unsure if this is the same for other devices) a vive tracker will be assigned to my hands only in Neos.

## To Reproduce
1. Turn off Pair 1
2. Turn on Pair 2

## Expected behavior
Trackers will be on your hands.

## Bug information (please complete the following information):
 - How often does it happen:   Most of the time
 - Does the bug persist after restarting Neos?   No
 - Neos Version: 2021.5.29.56
 - Neos Platform: Windows

## Reporters:
`Sox#0001`

**Comment by shiftyscales** [comment] 2021-06-07 00:18
In this case, this is not a bug, but by design. It was made so that users with extra controllers (e.g. old or broken ones) are able to use them as generic trackers/tracked devices.

**Comment by TehTurk** [comment] 2021-06-07 00:27
Still a bit of a problem tho if you think about it while minor, wouldnt it be ideal for folks to re-pair, or assign which controllers would be assigned to what? I know SteamVR somewhat alleviates this by having pucks assign to certain body nodes.

**Comment by shiftyscales** [comment] 2021-06-07 01:03
> 
> 
> Still a bit of a problem tho if you think about it while minor, wouldnt it be ideal for folks to re-pair, or assign which controllers would be assigned to what? I know SteamVR somewhat alleviates this by having pucks assign to certain body nodes.

I didn't say this wasn't an issue/could not be considered, @TehTurk.

All I was doing is adding context/explanation for why this behavior exists in its current form.

**Comment by Sox-NeosVR** [comment] 2021-06-07 05:45
SteamVR only allows 2 controllers to be paired/connected at one time (unless they are flashed into trackers) so this is kind of an un-necessary feature

**Comment by Frooxius** [comment] 2021-06-07 05:49
This behavior is actually on SteamVR side, not on ours. The Left/Right controllers are managed by the SteamVR Input (meaning it decides which device is left controller and which is right), rather than on Neos' end, so I'm not sure how much we can do about this from our end.

Do you have any body nodes assigned to those trackers in SteamVR for Neos? Sometimes they get default assignments, if you can check what those are set to that can help.

**Comment by Sox-NeosVR** [comment] 2021-06-07 06:24
i have 3 trackers assigned and the controllers i got 3 days ago will show as trackers when i switch pairs mid-game, i did check to see if the were assigned aned and the did not show in SteamVR

**Comment by Frooxius** [comment] 2021-06-07 06:47
Hmm I think I misunderstood the problem then sorry. I understood that your trackers got assigned as controllers instead, but it's that the controllers themselves show as trackers?

Can you please share a log file from session that reproduces this problem, so I can see what the controllers are being reported as by SteamVR?

**Comment by Sox-NeosVR** [comment] 2021-06-07 23:50
00:43:26.468 ( 90 FPS)	OnDeviceConnected: 5
00:43:26.468 ( 90 FPS)	DeviceClass: Controller, error: TrackedProp_Success
00:43:26.468 ( 90 FPS)	Getting Role
00:43:26.468 ( 90 FPS)	Role: LeftHand
00:43:26.468 ( 90 FPS)	Capacity: 47
00:43:26.468 ( 90 FPS)	Error: TrackedProp_Success
00:43:26.468 ( 90 FPS)	Controller Connected, Device Index: 5, Role: LeftHand, RenderModel: {indexcontroller}valve_controller_knu_1_0_left
00:43:26.468 ( 90 FPS)	LeftHand controller role is already mapped to: FrooxEngine.IndexController
00:43:26.468 ( 90 FPS)	Controller Registered
00:43:26.468 ( 90 FPS)	OnDeviceConnected: 6
00:43:26.468 ( 90 FPS)	DeviceClass: Controller, error: TrackedProp_Success
00:43:26.468 ( 90 FPS)	Getting Role
00:43:26.468 ( 90 FPS)	Role: RightHand
00:43:26.468 ( 90 FPS)	Capacity: 48
00:43:26.468 ( 90 FPS)	Error: TrackedProp_Success
00:43:26.468 ( 90 FPS)	Controller Connected, Device Index: 6, Role: RightHand, RenderModel: {indexcontroller}valve_controller_knu_1_0_right
00:43:26.468 ( 90 FPS)	RightHand controller role is already mapped to: FrooxEngine.IndexController
00:43:26.468 ( 90 FPS)	Controller Registered
00:43:29.110 ( 89 FPS)	IsLoaded: False, PlaybackEngineIndex: 1, AttemptsLeft: 2 Count: 2, PlaybackEngine: 
00:43:29.110 ( 89 FPS)	Trying Next Playback Engine
00:43:29.198 ( 89 FPS)	UMP Player Encountered Error. LastError: 
00:43:34.200 ( 90 FPS)	IsLoaded: False, PlaybackEngineIndex: 1, AttemptsLeft: 1 Count: 2, PlaybackEngine: 
00:43:34.200 ( 90 FPS)	Finished Load, IsLoaded: False
00:43:46.528 ( 89 FPS)	OnDeviceConnected: 1
00:43:46.529 ( 89 FPS)	DeviceClass: Controller, error: TrackedProp_Success
00:43:46.529 ( 89 FPS)	Getting Role
00:43:46.529 ( 89 FPS)	Role: Invalid
00:43:46.529 ( 89 FPS)	Capacity: 47
00:43:46.529 ( 89 FPS)	Error: TrackedProp_Success
00:43:46.529 ( 89 FPS)	Controller Connected, Device Index: 1, Role: Invalid, RenderModel: {indexcontroller}valve_controller_knu_1_0_left
00:43:46.674 ( 89 FPS)	OnDeviceConnected: 4
00:43:46.674 ( 89 FPS)	DeviceClass: Controller, error: TrackedProp_Success
00:43:46.674 ( 89 FPS)	Getting Role
00:43:46.674 ( 89 FPS)	Role: Invalid
00:43:46.674 ( 89 FPS)	Capacity: 48
00:43:46.674 ( 89 FPS)	Error: TrackedProp_Success
00:43:46.674 ( 89 FPS)	Controller Connected, Device Index: 4, Role: Invalid, RenderModel: {indexcontroller}valve_controller_knu_1_0_right
00:44:00.628 ( 90 FPS)	OnDeviceConnected: 5
00:44:00.628 ( 90 FPS)	DeviceClass: Controller, error: TrackedProp_Success
00:44:00.628 ( 90 FPS)	Getting Role
00:44:00.628 ( 90 FPS)	Role: Invalid
00:44:00.628 ( 90 FPS)	Capacity: 47
00:44:00.628 ( 90 FPS)	Error: TrackedProp_Success
00:44:00.628 ( 90 FPS)	Controller Connected, Device Index: 5, Role: Invalid, RenderModel: {indexcontroller}valve_controller_knu_1_0_left
00:44:00.923 ( 90 FPS)	OnDeviceConnected: 6
00:44:00.923 ( 90 FPS)	DeviceClass: Controller, error: TrackedProp_Success
00:44:00.923 ( 90 FPS)	Getting Role
00:44:00.923 ( 90 FPS)	Role: Invalid
00:44:00.923 ( 90 FPS)	Capacity: 48
00:44:00.923 ( 90 FPS)	Error: TrackedProp_Success
00:44:00.923 ( 90 FPS)	Controller Connected, Device Index: 6, Role: Invalid, RenderModel: {indexcontroller}valve_controller_knu_1_0_right
00:44:25.705 ( 90 FPS)	OnDeviceConnected: 1
00:44:25.705 ( 90 FPS)	DeviceClass: Controller, error: TrackedProp_Success
00:44:25.705 ( 90 FPS)	Getting Role
00:44:25.705 ( 90 FPS)	Role: Invalid
00:44:25.705 ( 90 FPS)	Capacity: 47
00:44:25.705 ( 90 FPS)	Error: TrackedProp_Success
00:44:25.705 ( 90 FPS)	Controller Connected, Device Index: 1, Role: Invalid, RenderModel: {indexcontroller}valve_controller_knu_1_0_left
00:44:25.816 ( 90 FPS)	OnDeviceConnected: 4
00:44:25.816 ( 90 FPS)	DeviceClass: Controller, error: TrackedProp_Success
00:44:25.816 ( 90 FPS)	Getting Role
00:44:25.816 ( 90 FPS)	Role: Invalid
00:44:25.816 ( 90 FPS)	Capacity: 48
00:44:25.816 ( 90 FPS)	Error: TrackedProp_Success
00:44:25.816 ( 90 FPS)	Controller Connected, Device Index: 4, Role: Invalid, RenderModel: {indexcontroller}valve_controller_knu_1_0_right
00:44:39.468 ( 90 FPS)	Exiting Neos. Save Homes: False


This is a log of me switching controllers and having the bug happen

**Comment by ProbablePrime** [comment] 2021-06-07 23:57
hey @Sox-NeosVR we need a full log file. Thats the entire file.

If you have one of those please upload it to github. You can do this by dragging the file into the box where you type your message. Github will handle the rest.

Thank you!

**Comment by Sox-NeosVR** [comment] 2021-06-08 00:02
[KYLE-PC - 2021.6.7.922 - 2021-06-08 00_42_26.log](https://github.com/Neos-Metaverse/NeosPublic/files/6612560/KYLE-PC.-.2021.6.7.922.-.2021-06-08.00_42_26.log)

**Comment by ProbablePrime** [comment] 2021-06-08 00:03
@Sox-NeosVR Perfect, you've done it correctly. Now we need to wait for the Team to review it.

Thank you!

**Comment by Frooxius** [comment] 2021-06-09 06:35
Thanks for the log, I'm looking at it right now. What exactly were the steps during this log?

If I'm reading it correctly, it looks like you did the following:
- Start with first set of controllers
- Turn off first set of controllers
- Turn on second set of controllers
- Turn on first set of controllers again
- Turn off second set of controllers and turn on again?

Does this sound correct? It seems like we might be able to remap the second set of controllers as they get assigned the correct role, but I'm a bit uncertain why are the first controllers and second popping up again as Invalid afterwards.

**Comment by Sox-NeosVR** [comment] 2021-06-09 08:09
Start with first set of controllers
Turn off first set of controllers
Turn on second set of controllers**

**this is when it triggered, then i turned off second set and turned on first set which removes/hides the trackers that appear on my hands

**Comment by Frooxius** [comment] 2021-06-10 08:07
The controller re-connection should now work in 2021.6.10.457, please give it a try and let me know if there are any issues!

**Closed by Frooxius** 2021-06-10 08:07 UTC
Labels: By Design, Not a Bug
