### ISSUE TITLE
Random but frequent crashes.

### ISSUE THREAD

**Issue by RaliiTheAvali** [Neos-Metaverse/NeosPublic#1967] opened 2021-04-06 23:32 UTC
IMPORTANT: PLEASE REPLACE OR DELETE (if not relevant) ANY TEXT IN BRACKETS [Like this] AND THIS ONE AS WELL

## Describe the bug
General Crashes, unknown issue or cause Logs included.

## Relevant issues
N/A

## To Reproduce
[Steps to reproduce the behavior:
1. Unknown, happens inconstantly.

## Expected behavior
[A clear and concise description of what you expected to happen.]

## Screenshots / Video
[If applicable, add screenshots or a video to help explain your problem.]

## Bug information (please complete the following information):
 - How often does it happen: once per day/ login
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.6.931
 - Neos Platform: Windows
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: Crashes started some time after patch 2021.3.23.391

## Reporters:
< log for todays crash >[RALII-PC - 2021.4.6.931 - 2021-04-06 17_49_38.log](https://github.com/Neos-Metaverse/NeosPublic/files/6268010/RALII-PC.-.2021.4.6.931.-.2021-04-06.17_49_38.log)
Crash date: 04/03/21 [RALII-PC - 2021.4.2.690 - 2021-04-03 01_16_07.log](https://github.com/Neos-Metaverse/NeosPublic/files/6268013/RALII-PC.-.2021.4.2.690.-.2021-04-03.01_16_07.log)
Crash date: 03/31/21 [RALII-PC - 2021.3.31.528 - 2021-03-31 15_53_13.log](https://github.com/Neos-Metaverse/NeosPublic/files/6268015/RALII-PC.-.2021.3.31.528.-.2021-03-31.15_53_13.log)

[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/6268115/Player.log)
[error.log](https://github.com/Neos-Metaverse/NeosPublic/files/6268117/error.log)

**Comment by kazu0617** [comment] 2021-04-06 23:50
When encounter a crash, you're also created some dumps and more information in `Appdata/Local/Temp/Solirax/NeosVR/Crashes`.
It's much more comfortable.

**Comment by RaliiTheAvali** [comment] 2021-04-07 00:19
> 
> 
> When encounter a crash, you're also created some dumps and more information in `Appdata/Local/Temp/Solirax/NeosVR/Crashes`.
> It's much more comfortable I think.

edited to include the two new files

**Comment by shiftyscales** [comment] 2021-04-07 04:46
Based on your log files, itt appears your crashes are being caused by the libVLC wrapper library. Video players are currently one of the most common causes of crashing in Neos.

We will be integrating a new/official libVLC integration soon when we're able, for now it's a fairly high priority. I'll be closing this issue as a duplicate of #660. Sorry for the inconveniences.

**Closed by shiftyscales** 2021-04-07 04:46 UTC
Labels: Bug
