### ISSUE TITLE
Screen mode users being able equip objects off an avatar which have an ActiveUserFilter set

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#583] opened 2020-05-24 04:52 UTC
I noticed when talking with LucasRo7 that users in screen mode are able to equip objects off my equipped avatar despite having an ActiveUserFilter set to ActiveUserWhenPresent, I tested this with a VR user and they said they were not able to do so.

**Comment by Frooxius** [comment] 2020-05-24 14:41
What exactly do you mean by equip? As in equip tools? Or just grab objects? Tools don't have ActiveUserFilter property, the grabbables and touchables do, but those don't have any concept of "Equipping", so I'm not fully sure I understand what do you mean.

**Comment by H3BO3** [comment] 2020-07-20 19:23
@Hayden-da-Serg Would you be able to provide an update on this? it's been sitting around for a while now.

**Comment by shiftyscales** [comment] 2020-07-20 19:34
It's possibly related to #766. As was noted by Frooxius- tools don't have any form of user filtering.

I also just checked- and in screen mode, you don't need to grip a tool in order to equip it. Merely double clicking the right mouse button will equip the tool regardless of if the tool has a grabbable on it or not (since tool equips aren't dependent on grabbables.)

I believe that is what he is refering to, @Frooxius and @H3BO3. Just the fact that because user filters don't apply to the tooltips themselves, there are mechanisms to equip a tool that is under a grabbable that has a user filter on it.

Another that was recently observed by Conduit was that while grabbing his avatar, and pulling the avatar in to your hand, it would trigger the tool equip mechanism even though the tool is deep in the avatar's hierarchy under a user-filtered grabbable on his snapper.

**Comment by Hayden-da-Serg** [comment] 2020-07-21 11:56
Yes @shiftyscales this is exactly the case

**Comment by ProbablePrime** [comment] 2021-06-17 22:38
@Hayden-da-Serg does this occur with the new Screen mode?

**Comment by Hayden-da-Serg** [comment] 2021-06-18 00:48
Haven't had the chance to check, will do so when I do get the chance.

**Comment by Beaned2000** [comment] 2021-07-29 13:35
This does not seem to be the case for the new desktop anymore, i tested this with both the ActiveUserFilter and with the only user list. both are behaving as intended therefore i will be closing this issue. if you believe it was a mistake to close this feel free to reopen it.

**Closed by Beaned2000** 2021-07-29 13:35 UTC
Labels: Needs More Information, Not a Bug
