### ISSUE TITLE
RayCast-/One "IgnoreUsers"

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2058] opened 2021-04-20 19:23 UTC
## Is your feature request related to a problem? Please describe.
I'm wanting to use a raycast but not on users and I can't filter Users out given the current lack of Collections.

## Relevant issues
None.

## Describe the solution you'd like
Another boolean input to "RayCastOne", "RayCaster" and "RayCastDriver" to make "IgnoreUsers" thus ignoring hits on users.

## Describe alternatives you've considered
Wait for collections.

## Additional context
I'm wanting to place a dynamic bone collider for my dynamic bones to interact with the ground and currently that's not quite possible due to the raycast also including users.

**Comment by shiftyscales** [comment] 2021-04-21 01:15
This issue is a duplicate of #403 and yes, collections are the answer.

**Closed by shiftyscales** 2021-04-21 01:15 UTC
Labels: Enhancement
