### ISSUE TITLE
Neos optimizes materials which color values are being driven by logix 

### ISSUE THREAD

**Issue by du27y** [Neos-Metaverse/NeosPublic#2099] opened 2021-04-26 19:11 UTC
## Describe the bug
When having multiple materials in a worlds assets which are all being driven by separate logix (setting up a floor with neoDMX) neos optimizes all of them to be the same material effectively breaking the driven materials. 

## Relevant issues
Couldn't find any

## To Reproduce
1. Create a bunch of materials with the material tip
2. Drive the material colors with logix
3. Set the drivers to be all black
4. Save the world

## Expected behavior
Neos will ignore materials in the assets that are being driven in any way

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Current
 - Neos Platform: Windows
 - Regression: No idea but probably yes

## Additional context
I spent half an hour setting up materials on a floor in a club world to be driven by neoDMX just to find out that neos destroys all my work in the attempt to optimize

**Comment by 3x1t-5tyl3** [comment] 2021-04-26 19:24
Potential duplicate of #1497 see shifty's comment. 
> 
> 
> On retrospect looking back at this issue, it feels more like an implementation issue on the part of the world designer/something that should be considered. Assets stored in the assets folder are intended more to be temporary/cleaned up from time to time, so if driving the material with Logix, it makes sense for it to be packed away in some dedicated slot somewhere in the world's hierarchy instead.

**Comment by shiftyscales** [comment] 2021-04-26 19:28
Definite duplicate of #1497 - but from what I recall having messed around with it, the issue only occurred for materials that were stored on the 'assets' folder. The original issue could be re-opened if it's still causing problems but when the materials/Logix were stored on the objects using the material the issue was not occurring in my experience, @du27y.

**Closed by shiftyscales** 2021-04-26 19:28 UTC
Labels: Bug, Duplicate
