### ISSUE TITLE
Slot references in logiX won't attach to Multiplexer node unless a ref node is already out.

### ISSUE THREAD

**Issue by ScarsTRF** [Neos-Metaverse/NeosPublic#2983] opened 2021-09-10 06:27 UTC
### Describe the bug?

When you are multiplexing a few slots, placing the ref directly from the ref card of the slot to the multiplexer node won't connect unless I were to connect the ref to another node like "Get Active User" then the ref node from the "Get Active User" to the multiplexer node.

### Relevant issues

I do not see any other issues related to this

### To Reproduce

Get a logiX multiplexer node out from the panel and pull a ref card out from a slot you want to reference. Try to reference the slot into the multiplexer as it won't connect. To bypass this issue, connect the ref card to something like a "Get Active User" Node, then connect the ref node to the multiplexer.

### Expected behavior

The expected behavior is to connect the Slot reference directly to the multiplexer from the ref card and referencing the slot instantly.

### Log Files

[SCARS-DESKTOP - 2021.9.9.1144 - 2021-09-10 00_58_01.log](https://github.com/Neos-Metaverse/NeosPublic/files/7141671/SCARS-DESKTOP.-.2021.9.9.1144.-.2021-09-10.00_58_01.log)

### Screenshots

https://user-images.githubusercontent.com/23484495/132809056-b5d6ce4d-81b8-4872-9a58-7d8db0d2bd6f.mp4

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.9.1144

### What Platforms does this occur on?

Windows, Linux

### Did this work before?

I Don't Know

### Reporters

@ScarsTRF#2778

**Comment by H3BO3** [comment] 2021-09-10 06:28
Duplicate of #2051

**Closed by H3BO3** 2021-09-10 06:28 UTC
Labels: Bug
