### ISSUE TITLE
Make voice message recording an optional toggle instead of held

### ISSUE THREAD

**Issue by RileyGuy** [Neos-Metaverse/NeosPublic#2088] opened 2021-04-26 06:49 UTC
## Is your tweak request related to a problem? Please describe.
Yes, the record button for the voice message recording tends to be quite small, leading to lots of accidental releases.

## Describe what would you like tweaked
An option to allow the recording button to be toggled instead of held.

## Describe alternatives you've considered
None that I can think of that would intrinsically solve this issue.

## Additional context
I have observed information that would otherwise be sensitive leaking due to people not realizing the button is released.

**Comment by shiftyscales** [comment] 2021-04-26 08:18
Hey @RileyGuy - apologies for the inconvenience, and the frustration, this issue is a duplicate of #1978.

**Closed by shiftyscales** 2021-04-26 08:18 UTC
Labels: Duplicate, Tweak
