### ISSUE TITLE
UI Aligning to a grabbed object results in view targeting the user's holder when object is released

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#2241] opened 2021-05-14 02:34 UTC
## Describe the bug
When UI Aligning to an image that is being grabbed by another user, the freeform camera will follow the image as expected.
Upon the image being released, the freeform camera will change targets to the holder of the user that was grabbing the image.

## Relevant issues
[Did you find any existing issues relevant to this one? If you found the same issue, please contribute to that one instead of making a duplicate.]

## To Reproduce
1. Spawn an item that can be UI Aligned (In this case, an image)
2. Have another user grab the item
3. CTRL+Click the item to enter UI Aligned mode on the grabbed item.
4. Have the other user release the item.
5. Observe that the freeform camera now appears to target the other user's holder slot, until you exit UI Aligned mode.

## Expected behavior
Freeform camera should remain UI Aligned to the originally targeted object

## Screenshots / Video
Example of view after targeted item was released:
![Example](http://files.aerizeon.net/sharex/2021/2021-05-13_22-30-Neos_J6YOgeiw1l.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.13.433
 - Neos Platform: Windows

## Reporters:
Epsilion
Reddragon
Psychpsyo
jeana
Goodvibes

**Comment by shiftyscales** [comment] 2021-05-14 05:21
Duplicate of #2180.

**Closed by shiftyscales** 2021-05-14 05:21 UTC
Labels: Bug
