### ISSUE TITLE
Voice To Text Component

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2809] opened 2021-08-15 23:15 UTC
### Is your feature request related to a problem? Please describe.

Translation tools require a text based form of a string to translate, and currently these use an external web browser. However, given the current status of speach-to-text engines like cortana or the chrome browser itself, these apis are available for software already.

For this, I would like to request the addition of a speach-to-text component that emits the last section of spoken text as an event or just a changing field.

I feel this can help a few accessibility cases:
For deaf users there currently seems to be two conversations that happen, one in voice and one that users type with mute helpers. With a text to speech component those two could merge together more easily, where the conversation between everyone can occur with lower effort. 
For localization an external web browser is currently needed to go from voice to text, then to translation, then back into neos.
When trying to set up a new user this isn't impossibly hard, but can be complex to guide them through a multi-step process. If instead the voice to text section could be done inside of neos, then no external website is required and only the api calls are needed, which can be done from inside neos as it stands.

### Relevant issues

#1914 would be more easily used with this component.
#196 would be more easily implemented with this component.
There are still questions of price, but this at least removes one of the hurdles of this feature.

### Describe the solution you'd like

A component that for a given audio stream, it attempts to parse the speech into a data accessible format.

### Describe alternatives you've considered

External websites as is currently done. This is the no change behavior.

### Additional context

This does open up a very odd security case, where users can make transcripts of local users very easily. Currently external recording software would be used and opus streams captured. However, some issues around this already exist with the current translation tools that don't necessarily know when you leave a session.

**Comment by Earthmark** [comment] 2021-08-15 23:18
One future goal of mine is splicing both #1914 and #196 together into an auto translating chat log, which I feel would help bridge a lot of communities that may have communication barriers otherwise.

**Comment by shadowpanther** [comment] 2021-08-15 23:22
If you have a C# implementation that doesn't rely on some rate-limited external API and is efficient and reliable, that'd be a start.
Both Chrome and Cortana rely on external APIs.

**Comment by Earthmark** [comment] 2021-08-15 23:26
My bad, I assumed these were self contained apis, looking into https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition and https://docs.microsoft.com/en-us/previous-versions/office/developer/speech-technologies/dd147134(v=office.14) more though they are as you say, server based... well that's saddening.

**Comment by ProbablePrime** [comment] 2021-08-15 23:31
I think this is a duplicate of #85 we may have to close. This one is of course more up to date though.

**Comment by Frooxius** [comment] 2021-08-15 23:39
I'd recommend deciding on whether to close this one or the original before we continue any discussion. Since we're already starting to rehash the discussion of the original in this one, it might be better to continue the old one, so we're continuing from  what was already discussed.

**Comment by ProbablePrime** [comment] 2021-08-15 23:43
I agree with Frooxius. I'll leave a note on the old one to read Earthmark's one here.

Thank you!

**Closed by ProbablePrime** 2021-08-15 23:43 UTC
Labels: Duplicate, Enhancement
