### ISSUE TITLE
NCR Transfers of small amounts show up as failed, but succeeded?

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2658] opened 2021-07-17 02:28 UTC
### Describe the bug?

I was tipped two small values of NCR as a joke by a user, but for the user the transfers showed up as failed, but I still received the transfer.

It does appear to have succeeded for a moment and is green/blue, but then it turns red after a few seconds.

The message does turn green again after restarting Neos.

This may result in scams of users not knowing their transfer succeeded, but it was remarked as failed.

### Relevant issues

None found

### To Reproduce

Send a small amount of NCR to another user, and see the transfer fail.

### Expected behavior

The transfer is marked as succeeded.

### Screenshots

![image](https://user-images.githubusercontent.com/1251609/126022492-e7089f62-cfe9-4f51-ad58-8ec5a164fcca.png)

![image](https://user-images.githubusercontent.com/1251609/126022513-381e83e2-2f19-49fe-a5ba-63b42dd57d67.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

No

### Neos Version Number

2021.7.11.1002

### What Platforms does this occur on?

- [ ] Any
- [X] Windows
- [ ] Linux
- [ ] Android / Quest

### Link to Reproduction Item/World

N/A?

### Did this work before?

No

### If it worked before, on which build?

NA before, as we did not have notification status in the chat message.

### Reporters

Earthmark Earthmark#0314
Marco Sizemore

**Comment by shadowpanther** [comment] 2021-07-17 03:20
After some testing (different amounts from 0.0001NCR to 1NCR and also KFC), I can say that the transaction itself completes, the wallet amounts change for both sides, but the send receipt is not being returned from the cloud. After waiting for some time (5-30 seconds), the message turns from yellow ("sending") to red ("failed"). It might be caused by the SignalR transition, I think.

**Comment by Frooxius** [comment] 2021-07-21 02:42
Should be fixed in 2021.7.21.127, thanks for report!

Reason for this is that the message is only added locally and not actually sent like that, since the credit transfers generate their own messages implicitly on the cloud.

**Closed by Frooxius** 2021-07-21 02:42 UTC
Labels: Bug, Cloud, Regression
