### ISSUE TITLE
LogiX's DriveNode <RefID> is now a Missing Component

### ISSUE THREAD

**Issue by orange3134** [Neos-Metaverse/NeosPublic#2114] opened 2021-04-28 18:00 UTC
## Describe the bug
LogiX's `DriveNode <RefID>` is now a Missing Component.
The type field says:
```FrooxEngine.LogiX.DriverNode`1[[FrooxEngine.RefID, FrooxEngine, Version=2021.1.13.764, Culture=neutral, PublicKeyToken=null]]```

## Relevant issues
none

## To Reproduce
1. Spawn an item that previously used `DriveNode <RefID>`. (For example, NeoRoid avatar)
2. You can find the Missing Component by checking LogiX in the Inspector.

## Expected behavior
It should work as usual.

## Screenshots / Video
at 2021.4.27.1385
![20210429023640_1](https://user-images.githubusercontent.com/56525091/116449830-89c64d00-a895-11eb-882e-4c06b28a5502.jpg)

at 2021.4.24.849
![20210429023843_1](https://user-images.githubusercontent.com/56525091/116449959-b4180a80-a895-11eb-91b4-b92647e49ec9.jpg)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.27.1385
 - Neos Platform: Windows
 - Link to reproduction World/Item: none
 - Regression: [Did this work before? Yes (2021.4.24.849)

## Additional context
Driving the RefID may not be a good idea. But I'm happy that past items continue to work.

## Reporters:
orange#1901

**Comment by Aerizeon** [comment] 2021-04-28 18:08
This is caused by `FrooxEngine.RefID` being moved to `BaseX.RefID`

**Comment by H3BO3** [comment] 2021-04-28 18:15
According to Shifty there will be a fix to enable compatibility with those types soon

**Comment by H3BO3** [comment] 2021-04-28 18:17
https://discord.com/channels/402159838827905024/439422161657135106/836841651917815818

**Comment by Frooxius** [comment] 2021-04-28 23:52
Fixed in 2021.4.28.1415, thank you for the report!

**Closed by Frooxius** 2021-04-28 23:52 UTC
Labels: Bug
