### ISSUE TITLE
Unity animation creator for  in neosvr with keyframes for creating animation file you can create and use in-game and put into some kind of animation component that you can assign a rig to

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#2421] opened 2021-06-06 18:53 UTC
## Is your feature request related to a problem? 
No i need this exactly as like in unity where you can create animation files in Neos and keyframes to move between Multiple points and then becoming a neos.anim file or something and then you put it into a animation player component that you can refer to the rig of the avatar just like how you put music in a sound component
 

## Relevant issues
Not one that has the exact same things I wrote here this is specific for a in-game animation file creator exactly like how it works in unity 

## Describe the solution you'd like
A clone of the unity animation creator working fully in Neos 

## Describe alternatives you've considered
I'm not good at programming 

## Additional context
Animator creater in neos

**Comment by H3BO3** [comment] 2021-06-06 18:56
Duplicate of #1763

**Closed by H3BO3** 2021-06-06 18:56 UTC
Labels: Enhancement
