### ISSUE TITLE
Japanese character う isn't rendered correctly

### ISSUE THREAD

**Issue by stabbyderg** [Neos-Metaverse/NeosPublic#2404] opened 2021-06-02 18:55 UTC
## Describe the bug
The default font renders う (the vowel "u") incorrectly in Neos. Only the top half of the character is correct.

## Relevant issues
[Did you find any existing issues relevant to this one? If you found the same issue, please contribute to that one instead of making a duplicate.]

## To Reproduce
1. Create text
2. Paste this character う
3. Look at the result

## Expected behavior
You should see this: う

## Log Files
N/A

## Screenshots / Video
<img width="35" alt="Screen Shot 2021-06-02 at 1 52 34 PM" src="https://user-images.githubusercontent.com/68791319/120536514-d5df4280-c3a9-11eb-9794-fb9a26e8946a.png">

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: [Any]
 - Link to reproduction World/Item: N/A
 - Regression: [Did this work before? No

## Additional context
This is one of the 5 vowels of Japanese so it shows up a LOT

## Reporters:
stabbyderg

**Comment by shiftyscales** [comment] 2021-06-02 20:51
This is a duplicate of #621. Thank you for the report.

**Closed by shiftyscales** 2021-06-02 20:51 UTC
Labels: Bug, Duplicate
