### ISSUE TITLE
Material (Logix like) Node Editor

### ISSUE THREAD

**Issue by minenick123** [Neos-Metaverse/NeosPublic#3453] opened 2021-12-13 19:30 UTC
### Is your feature request related to a problem? Please describe.

There is a bunch of things you can currently do using the included materials and shaders in neos. Tho to get some very interesting effects it can be quite complicated making a material that uses a bunch of additional components to look in a ceartain way.

### Relevant issues

Nope

### Describe the solution you'd like

A node like editor simmilar to logix, i specifically looked at blender for that one and in essence it doesent seem like that bad of an idea since it would make editing and creating materials a whole bunch easier and more user friendly, expecially to new users and if done right could even eliminate the need for custom shaders in a sence

### Describe alternatives you've considered

Nothing since the Idea is not really necessary since everything it would do can already done just more painfull and annoyingly

**Comment by H3BO3** [comment] 2021-12-13 19:35
This is planned for custom shaders

**Comment by ProbablePrime** [comment] 2021-12-13 19:36
This is unfortunately a duplicate of #63 as our custom shader system will be graph based like logix once we have it. I'll be closing this one and you're welcome to take the discussion over to #63

**Closed by ProbablePrime** 2021-12-13 19:36 UTC
Labels: Enhancement
