### ISSUE TITLE
sessions persisting after being closed

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3632] opened 2022-03-12 17:43 UTC
### Describe the bug?

sometimes sessions i visited constantly appear in my world browser even though they have been closed over 40 days ago clearing my local database did nothing resetting my computer clock did nothing I have to wait until it fixes itself by the way it doesn't

### Relevant issues

couldn't find anything

### To Reproduce

you can't really replicate it

### Expected behavior

a session should be immediately removed from my world browser when it is not available

### Log Files

[DESKTOP-DAN95E7 - 2022.1.28.1335 - 2022-03-12 10_35_21.log](https://github.com/Neos-Metaverse/NeosPublic/files/8238058/DESKTOP-DAN95E7.-.2022.1.28.1335.-.2022-03-12.10_35_21.log)

### Screenshots

this session was closed 3 days ago
![image](https://user-images.githubusercontent.com/76523692/158028681-9e243e0f-a1e5-4b61-a56d-a51f906e8a98.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

I don't remember

**Comment by ProbablePrime** [comment] 2022-03-12 21:47
This is a duplicate of #3563 so I'll be closing it.

**Closed by ProbablePrime** 2022-03-12 21:47 UTC
Labels: Bug
