### ISSUE TITLE
dragging in images produce two import windows

### ISSUE THREAD

**Issue by inzanesonikku** [Neos-Metaverse/NeosPublic#913] opened 2020-08-20 06:59 UTC
when dragging in any image, it will spawn in two import windows clipping into each other

**Comment by Enverex** [comment] 2020-08-25 20:13
In a new world:
Drag and drop = One import dialogue.
Ctrl+V = One import dialogue.

In my space map:
Drag and drop = Two identical import dialogues (on top of each other)
Ctrl + V = Same (2 import dialogues).

**Comment by TehTurk** [comment] 2021-04-15 14:10
I'm going to close this for now as it is seems the cause is an extra Clipboard Importer, if you can't find the component, perhaps we need better searching tools #27 or #256 to parse it manually in some form. Something more built in feature wise would be more ideal.

**Closed by TehTurk** 2021-04-15 14:10 UTC
Labels: Needs More Information
