### ISSUE TITLE
The function to level the grabbed object is not working properly.

### ISSUE THREAD

**Issue by orange3134** [Neos-Metaverse/NeosPublic#1863] opened 2021-03-23 16:47 UTC
## Describe the bug
When I'm grabbing an object with a laser, I should be able to lock the horizontal axis rotation every 90 degrees by pulling the trigger.
However, when I do this while moving my hand, the rotation is slightly off.

This rotation deviation seems to increase as the hand moves faster.

## Relevant issues
none

## To Reproduce
1. Create a Box.
2. Grab the Box with a laser and press the trigger while moving your hand.
3. The Box will tilt a little.

## Expected behavior
The tilt of the Box should be horizontal.

## Screenshots / Video
https://youtu.be/onhJFZLRG2M

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.23.391
 - Neos Platform: Windows
 - Link to reproduction World/Item: none
 - Regression: Maybe yes. In 2021.3.16.1287 this issue should not have occurred.

## Additional context
In the first half of the video, Box appears to be perfectly horizontal.
As a matter of fact, even if I don't move my hand, my hand is shaking slightly, so when I check the rotation with the inspector, it is not perfectly horizontal.

## Reporters:
orange#1901

**Comment by TehTurk** [comment] 2021-03-24 08:04
This might be related to the new input update changes. From Patch 2021.3.23.391

**Comment by Frooxius** [comment] 2021-03-25 06:49
This should be fixed in 2021.3.25.399 now, it was indeed caused by the input system changes. Thanks!

**Closed by Frooxius** 2021-03-25 06:49 UTC
Labels: Bug
