### ISSUE TITLE
Importing a specific .stp file crashes neos

### ISSUE THREAD

**Issue by RileyGuy** [Neos-Metaverse/NeosPublic#1481] opened 2020-12-15 22:07 UTC
Trying to import [this model](https://developers.hp.com/system/files/attachments/hp_reverb_g2_assembly.zip) at all causes a unity crash.

[DESKTOP-3DSJ4BT - 2020.4.9.1318 - 2020-04-09 17_19_27.log](https://github.com/Frooxius/NeosPublic/files/5698963/DESKTOP-3DSJ4BT.-.2020.4.9.1318.-.2020-04-09.17_19_27.log)

**Comment by Frooxius** [comment] 2020-12-15 22:17
Looks like a bug in Assimp. We're currently a fair bit behind the main branch due to some regressions, but I haven't updated in a while. I'll have to check if the new version fixes this once we update and then create a bug report for them if necessary.

**Comment by Frooxius** [comment] 2021-01-26 22:01
Tested this on 2021.1.26.1308 with latest Assimp. Doesn't seem to crash anymore, but it still fails to import.

Does this model work with other software, like Blender?

**Comment by RileyGuy** [comment] 2021-01-27 10:19
Yep, I had to use blender before in order to import it.

**Comment by Frooxius** [comment] 2021-07-22 07:49
I've checked and both of the files now import properly with latest Assimpin 2021.7.22.458. For the .stp you might need FreeCad installed though, most CAD files will require that. Closing this now.

**Closed by Frooxius** 2021-07-22 07:49 UTC
Labels: File Interactions, Waiting on 3rd Party
