### ISSUE TITLE
Glue Tooltip makes LogiX nodes un-editable

### ISSUE THREAD

**Issue by ryanroye** [Neos-Metaverse/NeosPublic#135] opened 2018-08-24 22:47 UTC
I'm not exactly sure why this is, however... on the surface it just seems to be parenting everything to a "glued" object. It would come in handy for packaging a large node setup that encompasses multiple objects.

**Comment by Coffee-Maker** [comment] 2020-06-26 04:16
After looking into this a bit, I didn't notice any unintended behavior, is this issue still relevant?

**Comment by ryanroye** [comment] 2020-07-08 09:30
I'll need to take a look at it again, a lot of changes have been made since I submitted this issue.

**Comment by kazu0617** [comment] 2021-02-13 08:11
I tried to reproduce it with the latest version (2021.2.7.1345). It seems that this phenomenon is still present.
The procedure to reproduce this is as follows: 1.
1. equip LogixTip and build Logix appropriately. 2.
2. equip a GlueTip and surround the Logix with a primary.
However, I feel that this is not a bug, but rather a specification that GlueTip has and is not a bug.
Also, if you want to edit it, just pack it and unpack it and it will continue to be editable, so it doesn't seem to be a serious bug.

If you use GlueTip to Bake Mesh, Logix will be destroyed haha

最新版(2021.2.7.1345)で再現してみました。どうやら現在もこの現象は残っているようです。
再現手順としては次の通りです。
1. LogixTip を装備し、適当にLogixを組む。
2. GlueTip を装備し、プライマリでLogixを囲う。
ただ、これはバグというよりもGlueTipが持つ仕様であり、バグではないのではと感じています。
それと、もし編集したい場合は一度PackingしてからUnpackしてあげれば引き続き編集可能となり、特に深刻なバグを抱えているわけでもなさそうです。

GlueTipを利用してBake MeshしたらLogixは破壊されます（そりゃそうだ

**Comment by ProbablePrime** [comment] 2021-03-31 04:12
I agree this isn't a problem. The nodes still work they just usually aren't individually grabbable. With community created tools such as 3DPack and Blueprints I'm not sure Glueing Logix is happening much these days.

I'll close this issue. If anyone is still struggling with this please feel free to open it with more information on the behaviour and how its causing issues.

**Closed by ProbablePrime** 2021-03-31 04:12 UTC
Labels: Bug, Good First Issue, Needs More Information, UI/UX
