### ISSUE TITLE
Unable to Receive Messages

### ISSUE THREAD

**Issue by ThatOneTeshari** [Neos-Metaverse/NeosPublic#2444] opened 2021-06-09 05:05 UTC
## Describe the bug
Failure to receive messages from other users this has been a consistent issue for the past month. However, it does not seem to be the inverse as people are able to get my messages. The only way for myself to receive messages from other users is through logging out and then logging back in to update my chat logs, this however does not fix the bug as it persists afterwards.

## To Reproduce
[Steps to reproduce the behavior:
Due to the nature of this bug, the most I can explain on it is the following for steps,
1: I'm truthfully unsure how to replicate this bug. However it may be due to improper installing and uninstalling of Neos VR, this includes deleting what is in the Solirax cache.

## Expected behavior
Receiving messages when they're sent to me from other users.

## Log Files
[BANBANS-PC - 2021.5.29.1365 - 2021-06-06 17_16_32.log](https://github.com/Neos-Metaverse/NeosPublic/files/6621174/BANBANS-PC.-.2021.5.29.1365.-.2021-06-06.17_16_32.log)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.7.794
 - Neos Platform: Windows
 - Regression: Yes: 2021.4.29.1307

## Additional context
Prior to this issue, I was trying to resolve an issue that had resulted in me unable to load my world, or anything and was stuck in an endless loop of trying to load into the game. This taking upwards to over an hour of waiting which yielded no results.

If additional logs are needed, I shall provide as many as needed until it's resolved.

**Comment by H3BO3** [comment] 2021-06-09 05:09
This could be considered a duplicate of #1922 - Could you reply with your findings there? I'll re-open that issue.

**Closed by H3BO3** 2021-06-09 05:09 UTC
Labels: Bug

**Comment by ThatOneTeshari** [comment] 2021-06-09 05:23
Thanks H3! Wasn't aware there was an existing issue up about this stuff.
