### ISSUE TITLE
View slightly lags behind in desktop mode after update 2021.9.11.1001

### ISSUE THREAD

**Issue by RileyGuy** [Neos-Metaverse/NeosPublic#2992] opened 2021-09-12 01:34 UTC
### Describe the bug?

When moving your mouse, you can observe your hand/face lagging behind very slightly. It's a bit hard to describe, but for instance I can see my face move to catch up due to how close my near clip is. You can also observe this when holding a tooltip, it will appear to lag behind slightly when you move your mouse around quickly.

### Relevant issues

N/A

### To Reproduce

1) Launch neos in desktop mode.
2) Equip a tool and move your mouse around quickly.
3) You will observe that the tool appears to lag behind the direction in which you're moving your mouse.
If your near clip is close enough, you will observe your face lagging behind as you crouch and move your mouse.

### Expected behavior

The body movements shouldn't lag behind the view movement.

### Screenshots

![image](https://user-images.githubusercontent.com/9770110/132967707-bded8d89-c15b-4eff-9538-79e9ccaef646.png)
It's difficult to capture in a picture, but this is me mid-crouch. You can see the inside of my nose as I crouch. This didn't happen previously.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.11.1001

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.9.9.1144

### Additional context

While it's not necessarily game-breaking. It's rather jarring and it makes the game feel a bit more latent when moving around.

### Reporters

Myself.

**Comment by ProbablePrime** [comment] 2021-09-12 01:41
Potential duplicate of: #2990

**Comment by epicEaston197** [comment] 2021-09-12 01:52
I have this happened to me too and it's quite disorienting

**Comment by shiftyscales** [comment] 2021-09-12 02:23
Marking this as a duplicate of #2990.

**Closed by shiftyscales** 2021-09-12 02:23 UTC
Labels: Bug, Duplicate
