### ISSUE TITLE
LookAtUser always looks at the local user when PositionSource is set to View

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2411] opened 2021-06-03 14:57 UTC
## Describe the bug
When putting a user in TargetUser - It targets the local user as if TargetAtLocalUser is enabled if the PositionSource is set to View (the current default PositionSource).

## Relevant issues
None

## To Reproduce
1. Put LookAtUser on an object
2. Put a user in TargetUser
3. Ask everyone if it's looking at them

## Expected behavior
The object should only look at the user thats referenced

## Screenshots / Video
![image](https://user-images.githubusercontent.com/53165730/120665953-34fc9000-c45a-11eb-8bdc-7f52226cc695.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Windows
 - Link to reproduction World/Item: Null
 - Regression: It used to work fine

## Additional context
This bug first surfaced yesterday when Sox had this issue with a different object in a different world

## Reporters:
AshtonSparx#5050 Sox#0001

**Comment by shiftyscales** [comment] 2021-06-03 15:44
I've confirmed this issue by creating a cone, and setting it to look at me. Cyro reported it was aimed at him as well.

This appears to only occur when the `PositionSource` is set to `View`. `Head` and `Root` both work as intended.

**Comment by Frooxius** [comment] 2021-06-07 13:35
Fixed in 2021.6.7.794! Note that the view position won't always be available though for other users, so it might not position properly at all times if you do this.

**Closed by Frooxius** 2021-06-07 13:35 UTC
Labels: Bug
