### ISSUE TITLE
Whisper Bubbles do not lower the volume of people outside the bubble enough

### ISSUE THREAD

**Issue by StarfishHidari** [Neos-Metaverse/NeosPublic#1879] opened 2021-03-25 21:30 UTC
## Is your tweak request related to a problem? Please describe.
When I go into whisper mode, I can still hear people that are not inside of my whisper bubble clearly. As I explained in #642 , I have difficulty processing audio when there are a lot of voices going at once, so I frequently use whisper mode to try to muffle voices of people that aren't near me.

My issue is that when I am in whisper mode it does not muffle outside voices much at all, making it still very difficult for me to process audio and have a conversation with someone. I tried to look into modifying how much my whisper mode lowers the volume of players outside the bubble, but I found that option doesn't exist in the whisper mode settings on your head proxy.

## Describe what would you like tweaked
Voices outside of my bubble should be at the very least muffled or muted.
A nice alternative would be the option to configure the volume of people outside my bubble when I'm in whisper mode

**Comment by Frooxius** [comment] 2021-03-25 21:44
Hmm this is a bit odd, it should already do this already. Is this a regression? Did it work at any point for you and suddenly break or has this always behaved this way?

Does anyone else experience this not working for them either?

Can you try switching to a different avatar (e.g. one of the Neos default ones) and see if the voices of people outside the bubble become quieter?

**Comment by Frooxius** [comment] 2021-03-25 21:49
I can expose the multiplier for external voices so you can tweak it, but from the description it does sound like something isn't working quite correctly, since the volume should be significantly lower. Perhaps there's some scaling that has expanded the transition range, or something is messed up with the proxies used to measure the distance to the avatar.

**Comment by shiftyscales** [comment] 2021-03-25 21:56
Based on her recent comment on #642 as well, it seems @StarfishHidari may be particularly sensitive to any amount of noise/volume.

Or her hardware is more sensitive/boosts the actual volume range because they also noted "typically someone can be hundreds of meters off in the distance and I still hear them as if they're next to me using logarithmic falloff" so I'm wondering if she might have loudness equalization enabled on her sound device in Windows or something similar?

![image](https://user-images.githubusercontent.com/54213390/112548541-a2fd4a80-8d79-11eb-9226-f1a2e5029127.png)

As noted though, it's already supposed to be fairly quiet/muffled when you are in a whisper bubble.

**Comment by Frooxius** [comment] 2021-03-25 22:06
Ah I see! The whisper sphere doesn't use the logarithmic falloff though, it's a hardcoded transition to 10 % of the original volume for anyone outside of the bubbles radius, in addition to their regular voice fall-off, so that shouldn't matter at all. It's like you went to the audio settings for them and lowered their user volume to 10 %.

I have the customization coming in the next build now, so you'll see if that helps. I'd definitely recommend checking with another avatar though, because it sounds to me like there might be something else wrong that's not applying that 10 % multiplier, since she mentioned that that it doesn't do much at all.

**Comment by StarfishHidari** [comment] 2021-03-26 01:35
I checked my sound drivers and I don't have any sound enhancements turned on, loudness equalization is disabled.

I just tried multiple of my avatars and also the Neos Bot from neos essentials and it had no effect on the bubble, I also tried making a brand new avatar by making a head and hands avatar with a box and that didn't change anything either.

I think this did used to work but it had been so long I just assumed this was how it always was and forgot.

I asked multiple people to switch into whisper mode and asked how loud I was when I was outside of their bubble, and they all said I was being fairly muffled when outside of their bubble.

**Comment by Frooxius** [comment] 2021-03-26 01:37
Ah thanks for the info! That's definitely strange that it doesn't muffle other people much for you, but works on others. I have the setting coming in the next build, you'll see if it helps at all or not. If not we can investigate some more into what's broken.

**Comment by Hayden-da-Serg** [comment] 2021-03-26 01:40
This may also be a result of #1701 whenever the value is set too big from what it should be it makes users sound like they're penetrating the whisper bubble.

**Comment by Frooxius** [comment] 2021-03-27 08:48
@Hayden-da-Serg Hmm yeah it might, but then we'd expect to see an effect when trying different avatars, so it seems unlikely to be the culprit.

@StarfishHidari I've added a new setting in 2021.3.27.510, can you give it a try and see if it helps?

**Comment by StarfishHidari** [comment] 2021-03-28 08:36
interestingly it seems you adding that setting seems to have fixed the issue 😊 thanks a lot

**Comment by Frooxius** [comment] 2021-03-30 08:37
Ah thanks for the info! Glad it helped, closing this.

**Closed by Frooxius** 2021-03-30 08:37 UTC
Labels: Bug
