### ISSUE TITLE
Unable to join Contacts+ session if user is not a contact of the host

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#2116] opened 2021-04-29 02:01 UTC
## Describe the bug
It appears the issue that was to be fixed in `2021.4.27.1385` (- Fixed not being able to join Contacts+ sessions when not friends with the host) still has some unresolved cases. I am unable to join a Hidden, Contacts+ session after receiving an invite from a friend in that session. I am not friends with the host.

## To Reproduce
- Receive an invite to a Hidden, Contacts+ session of which the host is not your contact
- Attempt to join the session

## Expected behavior
Connecting to the session should proceed without error.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.28.1415
 - Neos Platform: Windows
 - Regression: Yes, 

## Additional context
[SHIFTYWINDOWS - 2021.4.28.1415 - 2021-04-28 18_51_03.log](https://github.com/Neos-Metaverse/NeosPublic/files/6395848/SHIFTYWINDOWS.-.2021.4.28.1415.-.2021-04-28.18_51_03.log)
A log file from attempting to join such a session in which I launched Neos, attempted to join the session three times, then exited Neos.

## Reporters:
Shifty# 7944, jellyosaurus# 7259

**Comment by Frooxius** [comment] 2021-04-29 22:00
Fixed in 2021.4.29.1307!

**Comment by shiftyscales** [comment] 2021-05-01 05:08
This seems to still be an issue, unfortunately.

**Comment by Frooxius** [comment] 2021-05-01 13:11
Can you send me logs from the host?

**Comment by RaithSphere** [comment] 2021-05-01 21:25
[DIGIPAWS - 2021.4.29.1307 - 2021-05-01 22_17_27.log](https://github.com/Neos-Metaverse/NeosPublic/files/6410321/DIGIPAWS.-.2021.4.29.1307.-.2021-05-01.22_17_27.log)

**Comment by shiftyscales** [comment] 2021-05-01 21:30
And my log attempting to connect to Raith's session, relevant lines starting at 747 onward:
[SHIFTYWINDOWS - 2021.4.29.1307 - 2021-05-01 11_49_18.log](https://github.com/Neos-Metaverse/NeosPublic/files/6410327/SHIFTYWINDOWS.-.2021.4.29.1307.-.2021-05-01.11_49_18.log)

**Comment by shadowpanther** [comment] 2021-05-03 22:59
[VIXEN - 2021.4.29.1307 - 2021-05-04 01_35_27.log](https://github.com/Neos-Metaverse/NeosPublic/files/6418231/VIXEN.-.2021.4.29.1307.-.2021-05-04.01_35_27.log)
Encountered this today. Relevant attempts at the end of the log (session name GopStop)

**Comment by Frooxius** [comment] 2021-05-04 08:00
Should be fixed for good in 2021.5.4.471, sorry for the trouble!

**Comment by Readun** [comment] 2021-05-04 16:02
Saadly... still seeming to be a Problem. Tried it out with xlinka, our Headlesses on Contacts+.
We could not join each others headlesses. 
As soon as I was Contact with the Headless, it worked.
Which logs would be relevant?
Mine:
[READUN-PC - 2021.5.4.471 - 2021-05-04 17_43_28.log](https://github.com/Neos-Metaverse/NeosPublic/files/6422398/READUN-PC.-.2021.5.4.471.-.2021-05-04.17_43_28.log)

Starting at around 17:50:46.870

**Comment by TehTurk** [comment] 2021-05-04 17:15
Oh boy. Now question since this has been one of our more prolific bugs, what's been the cause? (Dumb question I know) but how does the discovery of other worlds mixed with join permissions work? It seems like something might have been introduced that's been causing this inherently.

**Comment by Frooxius** [comment] 2021-05-04 17:28
The root cause is because we increased the security of the security tokens. This has had a ripple effect on parts of the verification system, including cloud infrastructure. 

Security systems like this have a lot of checks along the way, so it's easy to trip them up and fail the process due to mismatch or something unexpected.

It looks like there's some problem with the API part of this now, I'm investigating this.

**Comment by TehTurk** [comment] 2021-05-04 18:35
No problem thanks for explaining! I figured an ask on the why/how would be a good idea for most folks to understand what's been going on :)

**Comment by Frooxius** [comment] 2021-05-04 18:37
Yeah. This is actually a good example of why we're sometimes resistant to do "small tweaks" that seem really simple on the surface and quick to. Sometimes they have a ripple effect like this, that takes a while to deal with. Sometimes we see those coming, sometimes we don't.

I think I have a solution now that should fixup the problems, working on it now.

**Comment by Frooxius** [comment] 2021-05-05 22:12
This has been fixed in 2021.5.5.159!

**Comment by FroppyVR** [comment] 2021-05-08 22:41
Just got this, the error said something about being unable to join unless you're contacts with someone in the session, it was contacts+ and I had a few contacts in there. Was a headless run by CytraX.

Logs:
[DESKTOP-ROAF3GP - 2021.5.8.445 - 2021-05-08 17_44_28.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446670/DESKTOP-ROAF3GP.-.2021.5.8.445.-.2021-05-08.17_44_28.log)
[DESKTOP-ROAF3GP - 2021.5.8.445 - 2021-05-08 17_45_10.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446671/DESKTOP-ROAF3GP.-.2021.5.8.445.-.2021-05-08.17_45_10.log)

**Comment by Frooxius** [comment] 2021-05-08 22:49
Is it possible to get logs from the host for this session?

**Comment by shiftyscales** [comment] 2021-05-08 22:53
I've asked that people provide them. From the cases I've heard people mention of this issue occurring, it sounds like if they try rejoining enough times, they are eventually let in. Not certain if knowing that helps at all, Froox.

I believe we're currently awaiting logs from Raith.

**Comment by AshtonSparx** [comment] 2021-05-08 23:02
[DESKTOP-SPEUN1P - 2021.5.6.453 - 2021-05-07 16_58_20.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446683/DESKTOP-SPEUN1P.-.2021.5.6.453.-.2021-05-07.16_58_20.log)
Line 943 is first attempt (in my logs) --

**Comment by RaithSphere** [comment] 2021-05-08 23:05
This log is huge[
[CYTRAX - 2021.5.5.159 - 2021-05-05 04_02_28.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446688/CYTRAX.-.2021.5.5.159.-.2021-05-05.04_02_28.log)
](url)

**Comment by Frooxius** [comment] 2021-05-09 03:06
Thanks for the logs, found the issue! Was due to some token symbols not being encoded properly, should be working properly in 2021.5.9.179 now! (the joining user needs to update, not just the host!)

**Closed by Frooxius** 2021-05-09 03:06 UTC
Labels: Bug, Needs More Information, Regression
