### ISSUE TITLE
Gripping onto a world and changing locomotion modes rapidly moves user

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1735] opened 2021-02-10 00:24 UTC
## Describe the bug
While gripping is enabled in the locomotion mode, if a user changes their locomotion mode (e.g. to noclip) they will be rapidly sent out towards the floating point respawn range.

## Relevant issues
Related in nature to similar user root streaming issues that have cropped up like #1719.

## To Reproduce
- Grip onto a collider while gripping is enabled
- Change locomotion modes

## Expected behavior
The user maintains their relative position while gripping, even if changing locomotion modes.

## Bug information (please complete the following information):
 - How often does it happen: Always (in a multi-user session)
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.7.1345
 - Neos Platform: Windows
 - Regression: Yes

## Additional context
- It appears this issue can only be replicated as a client/it doesn't affect the host
- If changing from a walk/run locomotion type with gripping to another walk/run locomotion without gripping enabled, the user will be bumped in position a few times in smaller intervals

## Reporters:
- Initially reported to me by Aegis_Wolf#5227

**Comment by Hayden-da-Serg** [comment] 2021-02-10 01:17
I appear to be unable to replicate this under similar conditions, I grab onto a world collider then switch to Noclip, I remain in the place I was last whenever I switched.
I am in a multi-user session that I'm not the host of.

**Comment by chemicalcrux** [comment] 2021-02-10 20:50
I can reproduce this in the Giant Cabin 1.2 world. Just grab a chair and switch to Noclip.

I cannot reproduce this in a SpaceWorld. Grabbing the floor and swithcing to Noclip has no effect.

**Comment by StarfishHidari** [comment] 2021-02-19 21:33
I found that in some worlds instead of sending you flying, it will act as if you're parented under the object and follow that object's position and rotation. Originally I thought it was a seperate issue because I noticed this when climbing players, but then realized it wasn't exclusive to climbing players.

It seemed like switching from walk/run to fly did not trigger this response, but every other switch did cause either flying off or following that object's transforms. I recorded a video of the bug happening here;
https://www.youtube.com/watch?v=7kObPvJG2Ek

I'm assuming the reason some worlds send you flying and some merely act as if you're parented under the object despite not being is that some worlds parent you under a user slot for organization?

**Comment by Frooxius** [comment] 2021-03-05 03:04
Fixed in 2021.3.5.176, thanks!

**Closed by Frooxius** 2021-03-05 03:04 UTC
Labels: Bug, Locomotion
