### ISSUE TITLE
Ability to adjust VR shortcuts

### ISSUE THREAD

**Issue by ko-tengu** [Neos-Metaverse/NeosPublic#3805] opened 2022-12-12 09:55 UTC
### Is your tweak request related to a problem? Please describe.

The VR shortcuts are really awkward to work around as a left handed person. The legacy inventory browser shortcut especially is extremely frustrating to work around, since trying to use a context menu on a held tooltip opens the inventory half the time instead. 

I understand these are supposed to only work "near your head" but the threshold for near my head seems to be nearly a foot away, I have to hold my hand way out to make sure I don't accidentally open the wrong menu.

### Describe what would you like tweaked

Let us specifically enable or configure certain shortcuts, or at least have them switch with your primary handedness. If this isn't possible for some reason, at least let us configure the distance that's "near your head."

### Describe alternatives you've considered

There are mods to disable some of the shortcuts, such as the "open dash" shortcut, and I've considered looking into modifying them to disable everything except emergency respawn and emergency disconnect.

**Comment by ProbablePrime** [comment] 2022-12-12 11:02
hey, this is unfortunately a duplicate of this issue: https://github.com/Neos-Metaverse/NeosPublic/issues/1130

So I will be closing this as a duplicate.

**Closed as not planned by ProbablePrime** 2022-12-12 11:02 UTC
Labels: Duplicate, Tweak
