### ISSUE TITLE
Texture Compression Fault

### ISSUE THREAD

**Issue by scuffedplus** [Neos-Metaverse/NeosPublic#3715] opened 2022-07-31 20:56 UTC
### Describe the bug?

while opening texture compression and trying to change the desired compression method, the game, just sort of hung, jittering between normal - ish performance, and 1 -2 fps, and or the game hanging to steamVR dash.
The Neos process also took the liberty of pinning every one of my 8 CPU cores to 100% untill i was forced to  terminate the process
The texture also, just wouldn't use the expected compression method, sticking to either BC3 or RGBA32, when set to BC7LZMA.
Both I, and a friend attempting to do the same basic thing have failed to set a texture to the desired compression method, but they experienced less prolonged performance interrupts.

### Relevant issues

---

### To Reproduce

Open a texture in the inspector, and change the desired compression format, while the texture is in use on your avatar.

### Expected behavior

The texture would be set to the desired compression method without my game hanging to dash or crashing.

### Log Files

[SEANS-PC_-_2022.1.28.1335_-_2022-07-29_22_33_57.log](https://github.com/Neos-Metaverse/NeosPublic/files/9229699/SEANS-PC_-_2022.1.28.1335_-_2022-07-29_22_33_57.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

No

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

scuffed+
 &&&
epicEaston197

**Comment by LexiBasilisk** [comment] 2022-08-06 00:45
This sounds like a duplicate of #3100.

**Closed as completed by LexiBasilisk** 2022-08-06 00:45 UTC
Labels: Bug, Duplicate
