### ISSUE TITLE
Prevent locomotion grip type 'AnyObjects' from overriding LocomotionGrip

### ISSUE THREAD

**Issue by LeDrascol** [Neos-Metaverse/NeosPublic#1437] opened 2020-12-05 15:48 UTC
## Is your tweak request related to a problem? Please describe.
Setting LocomotionGrip to false is designed to prevent an object from being gripped, but does not work if the locomotion Gripping setting is set to AnyObjects. This renders the component semi-useless, as users can self-inject an AnyObjects grip locomotion to bypass the collider's intended settings.

Colliders with LocomotionGrip set to false are prevented from being gripped, except when the locomotion Gripping setting is set to AnyObjects. This renders the component semi-useless, as users can self-inject an AnyObjects grip locomotion to bypass the collider's intended settings.

Additionally, users are unable to prevent being grabbed or climbed by another user using a locomotion with the locomotion Gripping setting is set to AnyObjects. All methods of removing the offending grabbing user will fail, except deleting the user's root slot.

Many users are uncomfortable with or otherwise do not want to be climbed or grabbed, but have no intended method of preventing this behavior from misbehaving users.

## Describe what would you like tweaked
Prevent gripping a collider with LocomotionGrip set to false in the hiarchy.

## Describe alternatives you've considered
- Delete users that violate the component
- Issue #600

## Additional context
Updated to use new formatting.

**Comment by shiftyscales** [comment] 2021-05-24 15:47
Closing this issue as a duplicate of #647. The underlying issue isn't that the locomotion grip is overridden by setting the gripping type to AnyObjects, but rather that there exist colliders on and around the user root that you can't apply the locomotion grip component to in advance. (E.g. the user root itself.)

**Closed by shiftyscales** 2021-05-24 15:47 UTC
Labels: Duplicate, Locomotion & Physical Interactions, Tweak
