### ISSUE TITLE
Show default input values for logix nodes on logix tip

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2710] opened 2021-07-26 12:39 UTC
### Is your tweak request related to a problem? Please describe.

Knowing the default values for logix node inputs is currently impossible without testing the node without giving anything to it.
This is annoying for small nodes and potentially infeasible for ones with many inputs.

### Describe what would you like tweaked

On the logix tip, where it shows the type of an input, also show it's default value for when nothing is plugged in.

### Describe alternatives you've considered

Not doing this, which I don't see much of a reason for as this info wouldn't take up a lot of space and is pretty vital to how the node works.
Checking the Wiki on every node, which is time consuming, especially in VR. (And I don't even know if that includes these values)

**Comment by Frooxius** [comment] 2021-08-02 13:59
This has been requested in the past and it's something we'd like to add, but it's a bit more involved to actually implement this. Currently there is no mechanism to actually determine the default value programmatically, as that happens in the code and will require us to manually document this.

In some cases the default value can change based on context too, so it's not always necessarily a fixed one too. This will probably be best handled as part of a documentation system.

**Comment by H3BO3** [comment] 2021-10-01 20:15
Realized this is a duplicate of #1047

**Closed by H3BO3** 2021-10-01 20:15 UTC
Labels: Enhancement, LogiX, Tools
