### ISSUE TITLE
neosvr crashes frequently, what should I do?

### ISSUE THREAD

**Issue by yaira7** [Neos-Metaverse/NeosPublic#2198] opened 2021-05-08 06:05 UTC
## Describe the bug
Symptoms are:
Neosvr crashes frequently(At least once an hour).
Often happens when I'm with a particular friend.
Occurs on both the host and the client.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: latest
 - Neos Platform:Windows
 - Regression:  No

## Additional context
I also cleared the cache.

I'm Japanese so I used an interpreter.
Therefore, it can be difficult to understand.

## Reporters:
My discord account:yaira・Y・F#0566

**Comment by yaira7** [comment] 2021-05-08 07:53
Sorry. I forgot attach Log File.
[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/6445466/Player.log)
[YU-WIN10 - 2021.5.6.453 - 2021-05-08 16_38_16.log](https://github.com/Neos-Metaverse/NeosPublic/files/6445469/YU-WIN10.-.2021.5.6.453.-.2021-05-08.16_38_16.log)

**Comment by shiftyscales** [comment] 2021-05-09 02:00
Based on the attached log, I believe this to be issue #660. Effectively- the current media playback library, UMP, and the libVLC wrapper library that are in use for video playback are prone to causing crashes. There isn't much that can be done immediately unfortunately because those libraries are really outdated, and closed source.

We are planning on upgrading to the official libVLC library soon, but it is currently awaiting some underlying engine work first. But it is a very high priority.

Video player related crashes without exaggeration represent about 95+% of all crash reports I ever receive.

You may wish to try removing any video players that you have in your worlds e.g. cloud home, etc. and see if that helps alleviate the issue.

For future reference in addition to the Neos log, you can also find an error.log/Player.log in the crashes folder at `%TEMP%\Solirax\NeosVR\Crashes`.

To navigate there quickly:
- Press Windows Key + R
- Enter `%TEMP%\Solirax\NeosVR\Crashes` then OK.

Apologies for the inconveniences @yaira7 @OrbitCZ, this is an issue I would also like us to tackle as soon as is feasible, but for now, it is best to try to work around it/minimize how many video players are loaded in a world at one time.

**Comment by shiftyscales** [comment] 2021-05-13 16:33
Closing as a duplicate of #660.

**Closed by shiftyscales** 2021-05-13 16:33 UTC
Labels: Bug, Crash Report, Duplicate
