### ISSUE TITLE
Session URLs don't work when a session is Hidden

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#2631] opened 2021-07-12 17:05 UTC
## Describe the bug
Whenever a session is hidden, no one can join using any provided CloudX Session URLs, this can make it difficult to get people in a hidden session when there's no other way to distribute the link to a session (for example then the contact message history refuses to load)

## To Reproduce
- Open a Hidden session
- Copy the Session URL from the Session menu
- Attempt to join said session URL from a different account
- Loading indicator just vanishes

## Expected behavior
From what I heard, hidden should mean that the session should still be accessible if the URL is accessible.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.7.11.1002
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Unknown

## Additional context
This can also make work difficult, say I'm working on something and I share the session URL to a small group who I may not all have in my Neos contacts list, they will not be able to join the session while it's hidden.

## Reporters:
Hayden#3180

**Comment by Aerizeon** [comment] 2021-07-12 17:15
Duplicate of #2494

**Comment by TehTurk** [comment] 2021-07-12 17:17
Moving over to #2494

**Closed by TehTurk** 2021-07-12 17:17 UTC
Labels: Bug
