### ISSUE TITLE
Extra LogiX Interpolation/Easing Nodes

### ISSUE THREAD

**Issue by RyuviTheViali** [Neos-Metaverse/NeosPublic#2707] opened 2021-07-25 22:07 UTC
### Is your feature request related to a problem? Please describe.

Currently LogiX provides a couple of interpolation nodes - Lerp and Smooth Lerp - as well as a couple of smoothing nodes. 

If one wishes to have a more intricate or different form of interpolation in LogiX, it has to be constructed out of multiple nodes. Depending on the interpolation type, this node tree can become larger in size. For commonly-used interpolation types, this method of constructing them is not portable between LogiX projects, and can clutter LogiX node trees.

### Relevant issues

No relevant issues.

### Describe the solution you'd like

An expansion of the repertoire of interpolation nodes available in LogiX would solve this issue and provide a wider gamut of control over how data is interpolated in LogiX node trees.

Listed are interpolation types that could prove useful in LogiX
(Code examples of all of the following interpolation types can be found [here](https://easings.net/))
For these interpolation types, all input parameters are: From, To, Lerp (0-1)
- Sine In Lerp, Sine Out Lerp, Sine In Out Lerp
- Quadratic In Lerp, Quadratic Out Lerp, Quadratic In Out Lerp
- Cubic In Lerp, Cubic Out Lerp, Cubic In Out Lerp
- Quartic In Lerp, Quartic Out Lerp, Quartic In Out Lerp
- Quintic In Lerp, Quintic Out Lerp, Quintic In Out Lerp
- Exponential In Lerp, Exponential Out Lerp, Exponential In Out Lerp
- Circular In Lerp, Circular Out Lerp, Circular In Out Lerp
- Back In Lerp, Back Out Lerp, Back In Out Lerp

Elastic interpolation requires an extra input parameter to allow for finer control over its interpolation:
- Elastic In Lerp, Elastic Out Lerp, Elastic In Out Lerp
- Input Parameters: From, To, Magnitude (default: 10), Lerp (0-1)

### Describe alternatives you've considered

All of the provided nodes given above could be combined into a singular node with the input parameters of:
- From, To, Magnitude (If applicable), Lerp (0-1), InterpolationType (A potential new enum type which allows the user to choose the interpolation type).

### Additional context

These nodes would currently serve mainly as quality-of-life improvements for LogiX workflows, and give LogiX editors more options when needing to interpolate their data for use in things including LogiX-based animation.

**Comment by ProbablePrime** [comment] 2021-07-25 22:08
Possible duplicate of: https://github.com/Neos-Metaverse/NeosPublic/issues/2521 ?

**Comment by RyuviTheViali** [comment] 2021-07-25 22:09
Ah yes, duplicate issue, that's referring to the same website too.

**Comment by ProbablePrime** [comment] 2021-07-25 22:11
Ok great. I will review your proposed node structure and compare it to my thoughts. 

This one in C# is actually just funky maths but in Logix it becomes very unwieldy. I'm Erin and I implemented Elastic and Bounce. But it takes a long time per function.

**Comment by ProbablePrime** [comment] 2021-07-26 09:45
Ok, I've reviewed yours and will be closing this as a duplicate unfortunately. I will refer to this one in my one so that we have cross-pollination.

They essentially have the same idea but where they differ is that this one has a larger proposal on how it should be implemented. Which is useful in some cases but I'm not sure this will line up with our usual design here.

Take a look inside Math/Shaping. The nodes here actually map to some of the easings and we might want to implement the rest as additional nodes in this directory. 

I'm not too sure as there are many ways this could be done.

**Closed by ProbablePrime** 2021-07-26 09:45 UTC
Labels: Enhancement, LogiX, Quality of Life
