### ISSUE TITLE
ValueInequalityDriver

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3558] opened 2022-01-25 14:10 UTC
### Is your feature request related to a problem? Please describe.

I'm always frustrated when needing to check if a value is not equal to something. We already have ValueEqualityDriver which can be used here in combination with something like a BooleanValueDriver to invert its bool but a single component solution here would be nice, considering how often I run into this.

### Relevant issues

Found none.

### Describe the solution you'd like

A ValueInequalityDriver component that does the opposite of ValueEqualityDriver.

### Describe alternatives you've considered

1. Not adding this. (Don't see why, especially considering that ValueEqualityDriver already exists.)
2. Using Logix. (That's at least 3 nodes in an otherwise logixless system...)
3. Using a ValueEqualityDriver in Combination with a BooleanValueDriver of type bool to invert the output.
4. Upgrading ValueEqualityDriver to something like ValueComparisonDriver that would take a comparison type (equal, not equal, maybe greater than and less than...)

**Comment by Banane9** [comment] 2022-01-25 16:27
Seconding the 4th option - currently you can only abuse value gradient drivers for that, aassuming your input is a float

**Comment by shiftyscales** [comment] 2022-01-25 17:01
Related/duplicate of #3024.

**Closed** 2024-04-14 08:24 UTC
Labels: Enhancement
