### ISSUE TITLE
Custom logix node creator 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#2965] opened 2021-09-08 19:37 UTC
### Is your feature request related to a problem? Please describe.

So basically a tool or wizard for creating custom logix nodes that you can connect things to out of components this would save on a lot of slots and could be handy for when you want to make a logix node that does a specific thing 

### Relevant issues

I guess the GitHub request about logix packing into one slot is relevant to this 

### Describe the solution you'd like

It would be handy 

### Describe alternatives you've considered

Not yet

**Comment by ProbablePrime** [comment] 2021-09-08 19:39
This is a somewhat duplicate of #1159 or #2818, so i'll be closing this one as a duplicate.

Thank you for your idea!

**Closed by ProbablePrime** 2021-09-08 19:39 UTC
Labels: Enhancement
