### ISSUE TITLE
Extend localization system for community use

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1715] opened 2021-02-05 10:02 UTC
## Is your feature request related to a problem? Please describe.
Localizing materials / images or other values based on the Neos language currently requires Logix when it should really be a single component that switches between multiple options, depending on the language, similar to what a ValueUserOverride does.

## Relevant issues
I couldn't find any

## Describe the solution you'd like
Two components, ValueLocaleOverride and ReferenceLocaleOverride, that drive a value or reference based on the users current locale.

## Describe alternatives you've considered
Various different logix based solutions, which seem like a lot just to localize something like an image, mesh or material.

**Comment by Frooxius** [comment] 2021-02-05 10:36
I don't plan on providing these two specifically, localization of images and other assets is going to be handled by the Neos' native localization system (the one currently used for the UI) once it's expanded for community use and provide a more scalable solution that doesn't need to be hard-coded into the world.

**Comment by TehTurk** [comment] 2021-02-23 11:19
Would this be sufficient to close then @Frooxius @Psychpsyo ?

**Comment by Psychpsyo** [comment] 2021-02-24 01:48
I feel like it would make more sense to keep this issue open until what Froox mentioned is actually implemented since the main request is still there and not 'fixed' yet.
And to possibly rename it to what Froox mentioned, making it a bit of a more general issue.

**Comment by Psychpsyo** [comment] 2021-05-13 20:36
Since this was brought up in #2222 again I just noticed a thing I wasn't aware of last time:
The need for a system like this to localize an asset, not just to your Neos language but instead to a different, project/item/world-specific language setting since there's reasons for wanting to have a specific wolrld, game or item in one language while Neos is set to some other language.
If, for example, an entire world was made in German and then got translated to English, I'd like to have the German version of the world without having to set Neos to German.

**Comment by shadowpanther** [comment] 2021-07-05 16:48
I would also like to change a text/picture/etc. in the world depending on a user's locale.
Currently, with the intention to make the system most extendable, I can do the following:
- create a Cloud Variable <int> writable per-user (unsafe)
- make every localisable item in the world use the corresponding multiplexer that is driven by this Cloud Variable
- make a panel that allows the user to change their instance of the Cloud Variable
- maintain the correspondence of this int to the list of the world's supported languages

This seems like overengineering, but unless we have other proper means to do that, I don't see any better way.

**Comment by shadowpanther** [comment] 2021-07-12 21:08
Probably a duplicate of #1044 which was added to the roadmap: https://github.com/Neos-Metaverse/NeosPublic/projects/7#card-64851638

**Comment by Psychpsyo** [comment] 2021-07-16 07:54
#1044 seems to refer to custom localization in general (and implies it's use for strings) while this issue is specifically about localizing other assets. (at least that's why I created it) Both are on the roadmap now, though I'm not sure if something being on the roadmap serves as a reason to close the Github issues around it.

**Comment by Psychpsyo** [comment] 2021-07-16 07:56
> 
> 
> I would also like to change a text/picture/etc. in the world depending on a user's locale.
> Currently, with the intention to make the system most extendable, I can do the following:
> 
>     * create a Cloud Variable  writable per-user (unsafe)
> 
>     * make every localisable item in the world use the corresponding multiplexer that is driven by this Cloud Variable
> 
>     * make a panel that allows the user to change their instance of the Cloud Variable
> 
>     * maintain the correspondence of this int to the list of the world's supported languages
> 
> 
> This seems like overengineering, but unless we have other proper means to do that, I don't see any better way.

There's also a component that gets a users language from their Neos settings, which is fine as long as people don't have a reason to set your things to a different language to the game in general.

**Comment by shadowpanther** [comment] 2021-07-16 08:01
A component and a LogiX node, yes. The problem with that is I still need to use AssetMultiplexer component which takes an int, so I need to have a map of language string to int. The solution I see here is a multiplexer that takes a language as an input, but as my idea was already shut down by Froox in #ideas, we have to wait till the proper official implementation is available.

**Closed** 2024-04-14 08:28 UTC
Labels: Enhancement, Translation
