### ISSUE TITLE
UI Tooltipping & Guidance

### ISSUE THREAD

**Issue by jaschahuisman** [Neos-Metaverse/NeosPublic#3310] opened 2021-11-04 08:52 UTC
### Is your feature request related to a problem? Please describe.

When creating new instances or modifying items in menus I always get frustrated about that I don't know the meaning of icons and symbols in menus. For example, in figure 1, it is not clear for a user what the trashcan icon means, and why there are two of them. To make the user experience more accessible, there must be a way of tooltipping and guidance.

![Capture](https://user-images.githubusercontent.com/39152972/140283792-f3780300-8a81-4c5c-b0ff-4b61c24ec0d7.PNG)

_Figure 1_

### Describe the solution you'd like

As I proposed there must be some kind of guidance, like tooltipping icon-only buttons in menus. Using an icon twice with different colors is a no-go in the world of user experience.

### Describe alternatives you've considered

There is an article about alternatives on tooltips, but on some points I don't agree with the author (in particular cases like Neos). Icons are cool, don't require much space and are directive, if you use them the right way.

Read the article here:
https://adamsilver.io/blog/the-problem-with-tooltips-and-what-to-do-instead/

**Comment by ProbablePrime** [comment] 2021-11-04 09:02
This is unfortunately a duplicate of several other issues but the good news is that we plan to work on this with our UI re-work.

You can find the duplicate issues here:
- #982
- https://github.com/Neos-Metaverse/NeosPublic/projects/2

**Closed by ProbablePrime** 2021-11-04 09:02 UTC
Labels: Enhancement
