### ISSUE TITLE
Make avatar movement speed consistent regardless of framerate.

### ISSUE THREAD

**Issue by Veeridian** [Neos-Metaverse/NeosPublic#3780] opened 2022-10-28 19:21 UTC
### Is your tweak request related to a problem? Please describe.

In lower framerate sessions or scenarios, one's movement speed decreases compared to a high framerate scenario, where the avatar movement speed is considered normal.

### Describe what would you like tweaked

Making movement speed consistent in all scenarios. 

### Describe alternatives you've considered

N/A

**Comment by LexiBasilisk** [comment] 2022-10-28 20:00
Thanks for the report @Veeridian - this is a duplicate of #3068. In that issue Froox noted:
> This is due to the timestepping for the physics system being smoothed out. It doesn't change as rapidly as the framerate does to avoid issues with stability in the simulation. If the FPS jumps a lot, it might fluctuate a bit. However it should always eventually stabilize.
> 
> If you push the framerate really low (e.g. like in your example), then it will simply hit a limit, where Neos will avoid timesteps that are too large to avoid things from exploding too.
> 
> Not sure if there's too much to do here in this case, unless the behavior doesn't stabilize over time.
> 
> We can make it adapt faster, but that can lead to other bad behaviors, such us phasing through walls, ground and other stability issues. Alternatively we can add multiple timesteps, but that can make things worse - if framerate gets bad, it'll generate more load on the CPU and in some cases skipping timesteps will feel jittery in VR, so it's a tricky thing to deal with.

**Closed as completed by LexiBasilisk** 2022-10-28 20:00 UTC
Labels: Duplicate, Tweak
