### ISSUE TITLE
Add args for Disable Desktop tab and any components for desktop futures.

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#1926] opened 2021-04-01 00:14 UTC
## Is your feature request related to a problem? Please describe.
Idk. Maybe nothing

## Relevant issues
Nothing I think. In addition, since the issue seemed to be covered, I checked it easily and it did not seem to be covered.

## Describe the solution you'd like
Neos has the ability to display a desktop, but some platforms don't have desktops to begin with (like Android), or you may prefer to use other desktop overlay applications (XSOverlay, OVR Toolkit, etc.). If you can handle such cases by adding an argument (or batch build the Android version with the argument added), you can use a larger dashboard for users who don't or can't use it, and reduce memory, logs, and crashes.

This was briefly elaborated on in the Discord.
You can check it out from the link below.
https://discord.com/channels/402159838827905024/439422161657135106/826964886436577330

One of the things that came up was that H3BO3 would like to see a checkbox in the NeosLauncher to toggle the same content as well as adding arguments. I don't use it much, but Lanucher is easier to set up, and more importantly, it is GUI-based, so I would like to see that checkbox added when it is added.

Original:
デスクトップを表示する機能がNeosにはありますが、プラットフォームによってはそもそもデスクトップが存在しなかったり(Androidとか)、また他のデスクトップオーバーレイアプリを好んで使いたい場合もあります（XSOverlay, OVR Toolkitなど）。そういった場合に引数を追加する（あるいは引数を追加した状態でAndroid版のバッチビルドする）ことで対応できれば使わない、使えないユーザにとってはその分ダッシュボードを広く使えますし、メモリやログ、クラッシュする原因を減らすことができます。

この内容をDiscordでかんたんに精査しました。
以下のリンクから確認できます。
https://discord.com/channels/402159838827905024/439422161657135106/826964886436577330

その中で出た内容として、引数を追加するだけでなくNeosLauncherに同様の内容をトグルできるチェックボックスがほしいとの話がH3BO3さんから出ました。自分はあまり使いませんが、Lanucherのほうがより楽に設定できますし、何よりGUIベースで使用できるので追加する際にはそのチェックも追加してほしいです。

**Comment by TehTurk** [comment] 2021-04-01 22:31
I would think the Headless Client would work in the same fashion atm, no? I know your asking for more of a CLI for Neos, but I don't know the feasibility of it atm, or whether there'd be a proper CLI  for every interaction in game.

**Comment by kazu0617** [comment] 2021-04-01 22:46
> I would think the Headless Client would work in the same fashion atm, no? I know your asking for more of a CLI for Neos, but I don't know the feasibility of it atm, or whether there'd be a proper CLI for every interaction in game.

...what? I just want to disable desktop "tab" not an "GUI".
I know to disable GUI can use at now already (and I run Headless so many times).
I planned for disabling desktop overlay function.

**Comment by TehTurk** [comment] 2021-04-02 01:20
Ah sorry this is a confusion on my part then! I misread

**Comment by shiftyscales** [comment] 2021-04-25 21:18
This is a duplicate of #1861.

> This will make more sense once we have screen sharing, which will let you stream your desktop to other users in the world, which is why we kept it there for now. I don't think it's worth it spending time engineering solution to hide/disable it in the meanwhile, it's just an oddity right now, but shouldn't actively harm anything.

https://github.com/Neos-Metaverse/NeosPublic/issues/1861#issuecomment-804982929

**Closed by shiftyscales** 2021-04-25 21:18 UTC
Labels: Enhancement, Won't Fix/Implement

**Comment by kazu0617** [comment] 2021-04-27 07:46
You're absolutely right. Thank you.
