### ISSUE TITLE
Certain item doesn't spawn from the inventory

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2340] opened 2021-05-25 16:10 UTC
## Describe the bug
At least one certain item in my inventory doesn't spawn. It is creating an ampty InventorySpawn slot, and that's all that happens.

## Relevant issues
#2335 by the exception

## To Reproduce
1. Be me
2. Go into my inventory
3. Try to spawn the 'fast furry transform' item

## Expected behavior
Item spawns

## Log Files
[VIXEN - 2021.5.24.1203 - 2021-05-25 18_55_03.log](https://github.com/Neos-Metaverse/NeosPublic/files/6540764/VIXEN.-.2021.5.24.1203.-.2021-05-25.18_55_03.log)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.24.1203
 - Neos Platform: Any
 - Link to reproduction World/Item: The item is in a private inventory folder, don't know how to get a link
 - Regression: Unsure

## Reporters:
Shadow Panther#5154

**Comment by Frooxius** [comment] 2021-05-25 16:15
Can you send me link to any of the reproduction items please? As funny as "Be me" is, I need to actually be able to replicate this.

**Comment by shadowpanther** [comment] 2021-05-25 16:17
That's the problem, the item is not in a public folder and I don't know how to get a direct link to the item.

**Comment by Frooxius** [comment] 2021-05-25 16:18
Yeah I can just double or quadruple the maximum depth, that can fix it potentially, but I won't be able to test.

If you can give me the exact path and name of the item, I can find it in the database. I'll increase the depth in the next build so you can test if that's better.

**Comment by shadowpanther** [comment] 2021-05-25 16:20
It's in /Stuff, item name is 'fast furry transform'
<img width="206" alt="image" src="https://user-images.githubusercontent.com/675104/119533141-3d840500-bd8e-11eb-9aab-f1a64b30a2ed.png">

**Comment by Mattyrogue** [comment] 2021-05-25 18:27
Related; Joshfluffy's inventory contents are now inaccessible; any item or avatar spawned just fills the hierarchy with InventorySpawn and AvatarSpawn. This issue has been persisting since yesterday (25/05/2021).
[joshfluffy asset failure.zip](https://github.com/Neos-Metaverse/NeosPublic/files/6541521/joshfluffy.asset.failure.zip)

The entire file is full of Newtonsoft.Json.JsonReader reader errors.
`---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: The reader's MaxDepth of 128 has been exceeded. Path 'Object.Children[1].Children[1].Children[0].Children[0].Children[1].Children[0].Children[7].Children[0].Children[1].Children[1].Children[0].Children[0].Children[3].Children[5].Children[0].Children[1].Children[1].Children[3].Children[1].Children[0].Children[3].Children[2].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Children[0].Components'.
  at Newtonsoft.Json.JsonReader.Push (Newtonsoft.Json.JsonContainerType value) [0x000ae] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.JsonReader.SetToken (Newtonsoft.Json.JsonToken newToken, System.Object value, System.Boolean updateIndex) [0x00062] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.JsonReader.SetToken (Newtonsoft.Json.JsonToken newToken) [0x00000] in <d47de75a7e3f422ca4ca64a654c80495>:0 
  at Newtonsoft.Json.Bson.BsonDataReader.ReadType (Newtonsoft.Json.Bson.BsonType type) [0x0009f] in <ef7d79831a074d38a894013d0a20285f>:0 
  at Newtonsoft.Json.Bson.BsonDataReader.ReadNormal () [0x00086] in <ef7d79831a074d38a894013d0a20285f>:0 
  at Newtonsoft.Json.Bson.BsonDataReader.Read () [0x00033] in <ef7d79831a074d38a894013d0a20285f>:0 
  at BaseX.DataTreeConverter.ReadDictionary (Newtonsoft.Json.JsonReader reader) [0x0003e] in <e9ec7be0fa204774bf965acd5c4260d4>:0 `

**Comment by Frooxius** [comment] 2021-05-25 20:36
Ok pushed a fix in 2021.5.25.1225, please reopen if still experiencing issues!

**Closed by Frooxius** 2021-05-25 20:36 UTC
Labels: Bug
