### ISSUE TITLE
"Has Mouth Tracking/Has eye tracking" Logix nodes

### ISSUE THREAD

**Issue by ModernBalloonie** [Neos-Metaverse/NeosPublic#3621] opened 2022-02-23 12:24 UTC
### Is your feature request related to a problem? Please describe.

I use different viseme settings based on if I don't have my mouth tracking, or if I have my mouth tracking.

### Relevant issues

Not that i'm aware of.

### Describe the solution you'd like

I would like an easy way to put a user into a node which outputs a bool, True if mouth tracking is enabled, false if mouth tracking is disabled, Same with eye tracking.

### Describe alternatives you've considered

Checking if the reference is null for the mouth tracking source, but a dedicated node would open up more possibilities.

**Comment by ProbablePrime** [comment] 2022-05-07 20:11
Duplicate of: https://github.com/Neos-Metaverse/NeosPublic/issues/2283

**Closed by ProbablePrime** 2022-05-07 20:11 UTC
Labels: Enhancement
