### ISSUE TITLE
Add node to get timezone offset of a user

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#1259] opened 2020-11-02 20:10 UTC
Local time is one of those odd nodes that provides different values for different users because the timezone offset in datetime is different. However in some cases it's very useful to know what time it is for different users in a world (such as user status boards)

To facilitate that can we get a node that provides the timezone offset as an integer for a given user? That way no more funky math around subtracting times on a specific users machine needs to be done.

Currently I believe the way to do this is get the user in questions machine to write to a register with a time offset of their utc now and local time, which can be error prone and is some very funky math.

**Comment by Earthmark** [comment] 2020-11-02 20:11
I realize that some time zones are fractional hours as well, dunno what to do with that.

**Comment by mralext20** [comment] 2020-11-02 20:15
it would need to be a float, as the UTC offset. 

similar to this would be nodes that can take a generic TZDatabase time zone and return either the time or UTC Offset for that time zone. 

see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for list of time zones.

**Comment by LeDrascol** [comment] 2020-12-05 18:53
This appears to be a duplicate of #598

**Comment by H3BO3** [comment] 2020-12-05 19:17
@LeDrascol It's not. This issue is for getting the numerical timezone offset for a user, and the issue you mentioned is for applying an arbitrary timezone offset to a time. While they could be closely connected in terms of use, they aren't duplicates

**Comment by shadowpanther** [comment] 2021-07-03 11:57
> it would need to be a float, as the UTC offset.
> 
> similar to this would be nodes that can take a generic TZDatabase time zone and return either the time or UTC Offset for that time zone.
> 
> see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for list of time zones.

Actually, not float, but TimeInterval (the type you get when you subtract two DateTimes)

**Comment by ProbablePrime** [comment] 2021-07-03 22:19
This is technically already possible, I cover this in this video: https://youtu.be/8sTvzFHvMb8

Additionally here's a picture of some logix to achieve this.

![image](https://user-images.githubusercontent.com/8791132/124367961-07e5fd80-dc11-11eb-9ff8-a0aae0f894d6.png)

- The Top half of the Image is doable TODAY, you just need to do some maths.
   - In this we use Two DateTimes minuses from each other which produces a TimeSpan node(This is functionally equivalent to your request for a numeric offset but you don't need to use Int or Float values)
- The Bottom half uses some custom nodes i've been implementing, It is not possible today.

One of the problems here is that producing a node which takes a user value and outputs a timezone/timespan based on their timezone is a little more complex and I'm unsure what you need it for. 

Could someone clarify your scenarios? Especially with the above setup in the top half of my image and my video you can achieve it without much fancy maths.

@shadowpanther @Earthmark @MR-Alex42 ?

**Comment by shadowpanther** [comment] 2021-07-03 22:34
@ProbablePrime `To Local Time` is only working in the context of the Local User. This request is about getting other user's offset. Yes, we can pulse a Write on behalf of another user, but having this as a user's property instead might be useful and less complicated to wire. Especially currently as we don't have a clean way to pass impulses to other users.

Querying a user's time offset should be similar to how we query ping/FPS currently.

**Comment by ProbablePrime** [comment] 2021-07-03 22:40
Ahh i see:
![image](https://user-images.githubusercontent.com/8791132/124368299-c0fa0700-dc14-11eb-80ac-b1c9fbf3a7b6.png)

That's unfortunately a little more complex. For things like Platform/Controllers etc, when a user joins a session we sync up some static data such as that.

But Timezone isn't included in this. We'd have to wire that through which is a little tricky and usually reserved for vital information.

**Comment by shadowpanther** [comment] 2021-07-03 22:47
Yes, I believe that's what @Earthmark originally asked for. I understand that this would require to add another property to User class and sync this property once on join or once in a while like fps.

**Comment by mralext20** [comment] 2021-07-03 23:34
@ProbablePrime will one of the nodes added be able to go from e.g. `America/Anchorage` Into the correct timezone?

**Comment by ProbablePrime** [comment] 2021-07-04 00:37
@mralext20 we could, its just a little tricky to catch exceptions there and make it clear to the user. We'd have to put lots of guards around it.

**Comment by ProbablePrime** [comment] 2021-07-04 05:37
![image](https://user-images.githubusercontent.com/8791132/124374325-27038000-dc4f-11eb-9539-bfc4d77bfa07.png)

Here's some ideas. I must add that, I'm just playing around here. While these are in my local build of Neos they'd need to pass a design and code review from Froox before they'd be in consideration. But I'm treating them as an experiment in learning various parts of LogiX internals and I wanted to do that in a way that lets you the community see what I'm doing / thinking.

**Comment by Earthmark** [comment] 2021-07-04 06:49
I like the pattern, it's quite a number of nodes related to time... as long as they can be isolated to only be shown in a section around time then that seems nice to me.

**Comment by ProbablePrime** [comment] 2021-07-06 08:20
With Froox's guidance we're going to do this a lot more simply. Avoiding the "Timezone" data type makes things a lot simpler. 

![image](https://user-images.githubusercontent.com/8791132/124566879-4d185400-ddf8-11eb-87b4-d98ef6367081.png)


This will actually be going to review with Froox :)

As for "Parse Timezone" this node is too complicated to provide right now.

**Comment by ProbablePrime** [comment] 2021-07-06 19:54
This was added in 2021.7.6.1154.

- Added nodes for getting user's time offset from UTC (requested by @Earthmark, @Alex from Alaska, implemented by @ProbablePrime | Docs)
-- User Time Offset - gives current TimeSpan offset of given user relative to UTC
-- User Time - gives given user's current time in their timezone
-- Local User Time Offset - gives time offset of local user

You can use the timespan nodes to add/subtract from UTC.

**Closed by ProbablePrime** 2021-07-06 19:54 UTC
Labels: Enhancement
