### ISSUE TITLE
Desktop standing height component or setting.

### ISSUE THREAD

**Issue by LewisSnow** [Neos-Metaverse/NeosPublic#2264] opened 2021-05-16 15:57 UTC
## Relevant issues
Say you have an avatar with a low/high height compensation. This will change the scale of the avatar which in desktop mode could look odd when standing. I.E Standing on tip toes, Floating, or constant squatting.

## Describe the solution you'd like
Being able to add a component or a setting (More than likely a component) that changes the height at which the desktop mode stands at. Should be simple enough.

## Describe alternatives you've considered
Possible setting in the settings menu however it doesn't warrant having it set there just yet.

## Additional context
![20210516115147_1](https://user-images.githubusercontent.com/61498631/118403663-7eb54000-b63d-11eb-955b-4e03133a1811.jpg)
![20210516115206_1](https://user-images.githubusercontent.com/61498631/118403665-7f4dd680-b63d-11eb-97a3-93a09e145152.jpg)
![20210516115236_1](https://user-images.githubusercontent.com/61498631/118403667-7fe66d00-b63d-11eb-8ede-09e537fe2b5d.jpg)

**Comment by shiftyscales** [comment] 2021-05-17 00:22
It should be the same in both VR (in particular while in seated mode) as it is in the desktop mode. Is it possible you have your height in the settings misconfigured, or your playspace is incorrectly calibrated? (E.g. the floor isn't quite where the floor actually is?)

**Comment by Frooxius** [comment] 2021-05-17 02:52
@shiftyscales Is correct, the standing height is based on your actual Height setting in the Settings, which is same for both VR and screen.

What is this set to? It's possible there's some odd interaction with the avatar offset and desktop mode posing that could be adjusted.

Can you send me a sample avatar to test? Doesn't have to be this one, just a simple one that reproduces the isssue.

**Comment by LewisSnow** [comment] 2021-05-17 14:47
> It should be the same in both VR (in particular while in seated mode) as it is in the desktop mode. Is it possible you have your height in the settings misconfigured, or your playspace is incorrectly calibrated? (E.g. the floor isn't quite where the floor actually is?)

It's very possible I've misconfigured my height however last time I've checked it's currently set to my height.

The avatar is scaled when changing "height compensation", therefore it's going to look like it's floating or on its tiptoes due to the nature of the "maintain seated height" regardless of which mode you're in (Desktop or VR), So this may not be an issue with any system in particular. @Frooxius 

Even still I can send you an avatar if need be.

**Comment by shiftyscales** [comment] 2021-05-17 22:40
That's what I mean, @LewisSnow - it could also still possibly be your playspace too.

If your height is set correctly, your playspace is calibrated accurately, and your avatar is configured properly, there shouldn't be any height/size difference between physically standing in your playspace, sitting with seated mode enabled, or playing in the desktop mode.

**Comment by LewisSnow** [comment] 2021-05-17 23:44
> That's what I mean, @LewisSnow - it could also still possibly be your playspace too.
> 
> If your height is set correctly, your playspace is calibrated accurately, and your avatar is configured properly, there shouldn't be any height/size difference between physically standing in your playspace, sitting with seated mode enabled, or playing in the desktop mode.

Right, That is correct however, When you modify the **Avatar Height Compensation** There are differences. 

My reason this setting is modified is for Full body calibration to allow the avatar to fit better. In doing so- The avatar is scaled down and doesn't touch the ground fully when standing due to actually height not changing but the scale of the avatar changing. 

If we could change the height setting to match the compensation per avatar. This could be fixed.

**Comment by LewisSnow** [comment] 2021-05-17 23:45
I think this could be renamed to Avatar height offset instead of desktop height. Now that I think of it.
It's more of a general thing rather than an issue with desktop.

**Comment by shiftyscales** [comment] 2021-10-07 04:18
Closing this issue as it sounds like the underlying issue is caused by #1120 and users shrinking their avatar smaller than they should to avoid the issue.

In the meantime, you could potentially accomplish what you are wanting in this issue by use of the AvatarTrackingOffset component? Although I'm not certain if that component will apply while in desktop. It would need to be tested.

**Closed by shiftyscales** 2021-10-07 04:18 UTC
Labels: Enhancement, Needs More Information, Low Priority
