### ISSUE TITLE
URI Doesn't Cast Correctly From Interface Card

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#2565] opened 2021-07-01 20:55 UTC
## Describe the bug
I'm not sure if the title is correct but it is what the issue I'm seeing seems to imply. Dragging a display node out of the URI field of an Interface Card appears to cast to a string, but then always shows null even when the URI is not null. More interestingly is if I try and drag the URI from the card into ToStr, it also still tries to (brokenly?) cast it to string, which doesn't seem to make sense.

## Relevant issues
None seen.

## To Reproduce
1. Create a StaticTexture2D.
2. Put something in the URI box.
3. Pull out an interface card for that component.
4. Pull out a display node for the URI.

## Expected behavior
For the display node to display the URI present in the component.

## Log Files
Nothing obvious showing.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/958670/124188119-bb86aa80-dab6-11eb-8c1d-efad2a4f3206.png)

![image](https://user-images.githubusercontent.com/958670/124188385-1c15e780-dab7-11eb-960c-08e9b8e16a92.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.7.1.498
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: No

## Additional context
N/A

## Reporters:
Enverex#6528

**Comment by Enverex** [comment] 2021-07-01 21:01
It seems that pushing the URI through a Format node works, but not via other methods.

**Comment by shiftyscales** [comment] 2021-07-02 01:39
Duplicate of #2464. You can use the ToString node because Uri's are not castable to a string.

**Closed by shiftyscales** 2021-07-02 01:39 UTC
Labels: Duplicate, Not a Bug
