### ISSUE TITLE
Userspace and Worldspace Desynchronized

### ISSUE THREAD

**Issue by LexiBasilisk** [Neos-Metaverse/NeosPublic#3186] opened 2021-10-13 19:19 UTC
### Describe the bug?

The userspace and its avatar are becoming desynchronized from my position in worldspace, and throwing constant null reference exceptions in my log.

### Relevant issues

There have been previous issues that have caused similar desynchronization to occur, but this one appears to be right from launch.

### To Reproduce

It appears all I need to do is launch Neos for this to occur. I'm not able to find a specific condition that triggers it otherwise.

Using a fresh local database seems to mitigate this issue until it comes up again.

### Expected behavior

The userspace should remain in sync with the worldspace.

### Log Files

In the following log, I launched Neos, noticed that my userspace and worldspace were out of sync, then exited Neos.
[SHIFTYWINDOWS - 2021.10.11.1175 - 2021-10-13 11_57_10.log](https://github.com/Neos-Metaverse/NeosPublic/files/7340663/SHIFTYWINDOWS.-.2021.10.11.1175.-.2021-10-13.11_57_10.log)

### Screenshots

![image](https://user-images.githubusercontent.com/54213390/137197213-5099cb93-032b-4abd-8928-7d14168fe220.png)

### How often does it happen?

Sometimes

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.11.1175

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

I believe it broke on this build.

### Additional context

Uncertain as to why, but creating a new local database seems to mitigate the issue. I am now on my third database, and preserved the previous two that exhibited this issue. I suspect there is some condition that triggers this to occur, but I am presently uncertain as to what.

### Reporters

Shifty

**Comment by shiftyscales** [comment] 2021-10-14 16:35
It appears that all that's required is for me to relaunch Neos after being signed in. (Second start after making a fresh local database.)

In bringing an inspector into my userspace I think I might have discovered why.

There are two separate SettingsManager components, one on a slot called `Settings` and another on a slot called `CloudSettings`, additionally, the `CloudSettings` slot has an avatar builder under it.

So I think what's been happening is after my first login, I've been getting two userspace avatars generated which has been causing the issues.

I deleted the avatar builder found under the cloud settings slot, and restarted- now I have two CloudSettings slots, but aside from that, things seem to be working as intended.

So I believe this might've been user-error on my part and I somehow dropped the avatar builder slot under my cloud settings at some point?

Should this issue be closed, @Frooxius?

**Comment by Frooxius** [comment] 2021-10-14 21:35
Hmm that's really odd, I have no idea how did avatar builder get there.

I think if it's just that yeah you should close this, as it's likely something that got messed up for you specifically.

**Closed as completed** 2021-10-14 22:02 UTC
Labels: Bug
