### ISSUE TITLE
Get User Viewport Transforms

### ISSUE THREAD

**Issue by seif1** [Neos-Metaverse/NeosPublic#2287] opened 2021-05-18 09:36 UTC
# Get User Viewport Transforms

## Is your feature request related to a problem? Please describe.
The user could be using a number of view targeting controllers:
- first person
- third person
- Freeform
- UI Targeting

There is currently no reliable way to get the current view location of a user, as they could be in any of the above states, Freeform, and UI Targeting use the "View" slot, first person uses head transforms, and third person appears to have no way to find the transforms of the viewpoint when a user is in this viewing mode.

## Relevant issues
#2286

## Possible Solutions
 - If the View slot moved to track the first person and third person cameras when relevant, then the View BodyNodeSlot could be used.
 - A LogiX Node that allows you to get the transforms of a users active view.

**Comment by shiftyscales** [comment] 2021-05-18 19:07
If I'm understanding correctly, I believe this is a duplicate of #2238. These nodes already exist.

> Added these two nodes in 2021.5.17.871 which should help cover the usecases:
> 
>     Added UserActiveViewTargettingController node (under Users) which outputs the currently active view targetting controller (first person, third person, UI camera, Freeform and any future ones) (based on request by @ LeDrascol)
>     Added UserViewReferenceActive which indicates if given user has currently active view reference (based on request by @ LeDrascol)

**Comment by seif1** [comment] 2021-05-18 21:30
Sorry, I believe this wasn't clear enough, the problem more specifically is that there is no reliable way to determine where the user's actual view is (Its actual transforms), the recently added LogiX nodes help, allowing the use of different slot information based on their output, but there seems to be no way to find the transforms of the 3rd person camera, and it is also a bit strange to have to use a bunch of different slots with comparisons to change which exact slot is used to get the view transforms for a user's view, when that information could just be given more simply, such as the view slot could be changed to always match where the user's view is, or a LogiX node that outputs the actual transforms of a users view.

**Comment by shiftyscales** [comment] 2021-05-18 22:03
Some of this information can already be inferred, e.g. if you're using the above nodes, you could determine which camera they have active, and thus presumably where their viewport (and by extension its transforms) based on the relevant slots.

Can you clarify your intended use-cases for **why** you want access to the exact transforms of their current viewport?

What problems would having this node (or whatever mechanism is decided on) solve/how do you envision it being used?

**Comment by seif1** [comment] 2021-05-18 22:20
So my specific use case is that I am making a tool to snap logix to a grid, which heavily relies on knowing a lot about the users view in order to properly determine rotation's, using the existing nodes and comparisons of those to change which slot my tool looks at the transforms of seems like it would not be very future proofed, (for the same reason the recent type input was added) so it would be better if there was some reliable way to find the viewpoint transforms that could be updated, or changed without causing any problems in tools developed with them.

**Comment by Frooxius** [comment] 2021-05-19 05:49
Do you need the view to be synchronized or is accessing local user's view position and rotation ok? 

The problem is that there's not actually necessarily a Slot corresponding to the view in all cases, so we can't give you that one and it's not always synchronized because it's implicit, meaning it can't be made to work the same way as BodyNode slot without extra network bandwidth.

We could look into either option though, there are ways to minimize the network load. Although accessing the current local view position and rotation is much easier and would work in all cases too.

**Comment by seif1** [comment] 2021-05-19 06:46
Having it access the value locally would work fine, at least for my case, the whole thing comes down to there being no way to get the transforms for certain view modes at all currently (specifically third person), and a improper assumption on my part that you would have to parse the UserActiveViewTargettingController to string in order to do comparisons. Every other case has somewhere you can get the position of the viewpoint.

**Comment by Frooxius** [comment] 2021-05-20 17:55
Added nodes in 2021.5.20.1063, hope they help!

- Added LogiX nodes for accessing local user's view/ears transform overrides (under Users/Local Output) (based on request by @seif1)
-- ViewPosition, ViewRotation, ViewScale and ViewOverriden (bool)
-- EarsPosition, EarsRotation, EarsScale and EarsOverriden (bool)

**Closed by Frooxius** 2021-05-20 17:55 UTC
Labels: Enhancement, Needs More Information
