### ISSUE TITLE
Session Crash on setting ActiveNodeType of Logix Tip

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1853] opened 2021-03-22 16:41 UTC
## Describe the bug
When someone other than the host sets the ActiveNodeType of a Logix tip to certain values, that crashes the session.

## Relevant issues
Couldn't find any.

## To Reproduce
1. Inspect a Logix tip.
2. Get someone who isn't the host to set the ActiveNodeType to FrooxEngine.ValueField`1[[System.Type, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
3. The session crashes instantly.

## Expected behavior
Anything that doesn't involve crashing the session.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.16.1287
 - Neos Platform: Windows, probably Any
 - Regression: Don't know.

## Reporters:
Cameron#7818

**Comment by Frooxius** [comment] 2021-03-22 16:45
Do you have a log for the crash?

**Comment by Psychpsyo** [comment] 2021-03-22 17:55
This should be the relevant section of my logs:
[log.txt](https://github.com/Neos-Metaverse/NeosPublic/files/6184313/log.txt)

**Comment by Frooxius** [comment] 2021-03-22 18:20
From the log it seems that the crash occurs when you attempt to spawn node of this type, but your reproduction steps don't mention this.

I don't see anything that would indicate a possible crash just by setting the ActiveNodeType to given value. Are the reproduction steps correct? If so, can you post the whole log please (in general, please always post a whole log, as getting relevant section can cut out some crucial information/context or not be relevant at all)?

**Comment by Psychpsyo** [comment] 2021-03-22 19:11
The reproduction steps are correct but spawning the compoent also crashes the session. (since the host can still set it)
I generally prefer not to send my full logs since they can include infos about events and objects from private or local sessions but [here they are](https://github.com/Neos-Metaverse/NeosPublic/files/6184735/SYSTEM-PURPLE.-.2021.3.16.1287.-.2021-03-22.07_18_02.log).
(It might be good to make the logs not include potentially sensitive info like the names and IDs of items, sessions and users.)

**Comment by Frooxius** [comment] 2021-03-22 19:23
Thanks! If you prefer, you can send us logs privately in Discord DM.

Unfortunately removing sensitive information from the logs would prevent us from using the logs to diagnose many of the issues.

**Comment by Frooxius** [comment] 2021-03-23 03:59
Found the cause, fix in 2021.3.23.231, thanks for the info!

**Comment by 3x1t-5tyl3** [comment] 2021-03-24 20:14
Apologies for re-investigating this. But the "fix" just closed all writing into the field.

Unfortunately this also breaks all node-type-writing for custom logix-scripts that may automate certain functions.
Example of this: I have a function on my tool that allows me to spawn a Variable from a write node which needs me to write into the "ActiveNodeType".

Is there a way to get that functionality back? It seems a bit hardcore to just outright disable writing into the typefield.

**Comment by Frooxius** [comment] 2021-03-24 20:18
We haven't disabled writing into the typefield (at least not intentionally), only added validation for the type's that you put there, which will reject any types that aren't valid.

Can you give me examples of any types that don't work anymore?

**Comment by 3x1t-5tyl3** [comment] 2021-03-24 20:21
Alll of them. Any type even if 100% valid (for example copied from another logixtip) just resets the valuefield and the logixtip component rejects the type value and resets it to whatever it was before.

We tried manual insertion, write nodes and primitivemembereditors, all of which fail.

**Comment by Frooxius** [comment] 2021-03-24 20:37
Ok thanks, I found the issue, have a fix coming in the next build!

**Comment by Frooxius** [comment] 2021-03-27 08:51
Forgot to close this!

**Closed by Frooxius** 2021-03-27 08:51 UTC
Labels: Bug
