### ISSUE TITLE
Session previews failing to load after cache clear

### ISSUE THREAD

**Issue by AdmiralSoap** [Neos-Metaverse/NeosPublic#3032] opened 2021-09-18 11:32 UTC
### Describe the bug?

I cleared my cache folder yesterday. And now consistently when I boot up Neos the world list's previews fail to load.

Attached files: Log and a picture.

### Relevant issues

I'm not aware of other relevant issues

### To Reproduce

Not sure if it's because clearing cache in the newest build.

### Expected behavior

To be able to load world previews.

### Log Files

[DESKTOP-M3LTEEK - 2021.9.16.105 - 2021-09-18 14_16_02.log](https://github.com/Neos-Metaverse/NeosPublic/files/7189810/DESKTOP-M3LTEEK.-.2021.9.16.105.-.2021-09-18.14_16_02.log)

### Screenshots

![Image](https://user-images.githubusercontent.com/2409607/133887282-ca4c6487-8b2a-499f-a4b5-5210b11fb1d1.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

9.16.105

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### Reporters

AdmiralSoap#4934

**Comment by Ducky07** [comment] 2021-09-18 11:41
Same here, I just removed my cache and my world previews and skyboxes aren't loading in either.
[Napo - 2021.9.16.105 - 2021-09-18 14_36_36.log](https://github.com/Neos-Metaverse/NeosPublic/files/7189823/Napo.-.2021.9.16.105.-.2021-09-18.14_36_36.log)

**Comment by AdmiralSoap** [comment] 2021-09-18 11:46
Oh I just noticed GreaseMonkey's issue is related to this one:
https://github.com/Neos-Metaverse/NeosPublic/issues/3030

**Comment by shiftyscales** [comment] 2021-09-18 15:38
Yes, going to close this as a duplicate of #3030. It appears the projection 360 shader might not have compiled properly, so when a user clears their cache they're left with a broken copy compared to users that have it already cached.

**Closed by shiftyscales** 2021-09-18 15:38 UTC
Labels: Bug, Duplicate
