### ISSUE TITLE
Inspector to show where a value is being driven from

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2406] opened 2021-06-02 19:46 UTC
## Is your feature request related to a problem? Please describe.
It's great that the inspector shows (in pink) that a value is driven. However, it would be extremely useful to know where that value is being driven from. Right now I don't know of a way to easily get that information other than searching all over the object for something that looks like a driver.

## Describe the solution you'd like
I'm not sure... an additional button next to driven values that you can click and it pops up the thing driving it? Kind of like the way materials work when you click the arrow button and you get a new inspector with the material.

## Requesting user
Xekri

**Comment by H3BO3** [comment] 2021-06-02 19:47
Duplicate of #2059

**Closed by H3BO3** 2021-06-02 19:47 UTC
Labels: Enhancement
