### ISSUE TITLE
on user avatar loaded logix node

### ISSUE THREAD

**Issue by gentlecolts** [Neos-Metaverse/NeosPublic#3634] opened 2022-03-14 22:38 UTC
### Is your feature request related to a problem? Please describe.

There already exist a number of nodes related to user events, such as if a user joins, or respawns, however there is currently no direct means of determining when a user has switched avatars.

### Relevant issues

Various systems may rely on injecting into or monitoring a user's avatar.  Currently, NEOS requires many hacky solutions for handling both the detection of an avatar switch, and actually finding the avatar that has been equipped.  Having a means by which logix can detect a user equipping, and/or fully loading an avatar would greatly simplify some of these systems.

### Describe the solution you'd like

The presence of an "On User Avatar Load" logix node, perhaps with potentially better verbiage, which would fire when a user switches, first loads, or otherwise equips an avatar.  This node would ideally provide the user that performed the action, and, if possible, the avatar's slot.  The latter may be complicated, at this time, and may rely on collections.  Additionally, a boolean input may be desirable for selecting whether or not this node should fire on scripted avatar equipping, vs an explicit user action

### Describe alternatives you've considered

Similar functionality can be achieved already, however it relies on a lot of hacky, indirect actions.  One must first find the user's avatar, which can currently only be done using heuristic methods, and can then check to see if that slot ever leaves the user's root.  While possible, it would be far more elegant to simply have the game fire an event for this instead.

**Comment by Zyzyl** [comment] 2022-03-15 07:04
Thanks for the suggestion! This appears to be essentially a duplicate of https://github.com/Neos-Metaverse/NeosPublic/issues/1694. As such, I'm closing this issue and I suggest adding any additional thoughts as comments on the older one instead.

If you believe this request is sufficiently different to require a separate issue, you can re-open this one. Though if you do so, I'd suggest editing the text to make it clear how this one differs from #1694.

**Closed by Zyzyl** 2022-03-15 07:04 UTC
Labels: Enhancement
