### ISSUE TITLE
Add a component for context menu sliders

### ISSUE THREAD

**Issue by jonnyawsom3** [Neos-Metaverse/NeosPublic#3090] opened 2021-09-26 19:09 UTC
### Is your feature request related to a problem? Please describe.

I've seen a few times either avatars or worlds have a slider/radial wheel to set a percentage of volume or a value (VBLFC's volume slider for example), at the moment I've been told it requires calculating where the user is pointing and creating an interface yourself. For someone still learning how to find components yet alone use them, it practically locks them out of an extremely useful feature without someone who understands it being on hand.

### Describe the solution you'd like

I think having a built-in component (Similar to how ButtonToggle works) to add a slider to a context menu item would both decrease the skill needed to use them and make more options available to newer players, opening up easy volume sliders, brightness settings, blendshape changing and more in a fraction of the time.

### Describe alternatives you've considered

I've asked for help with making a slider twice on the discord server, from what I can tell either I need to find something that already has the slider and reverse engineer it, or learn more Logix and maths to calculate everything and create it from scratch.

**Comment by Frooxius** [comment] 2021-09-26 19:17
Duplicate of: https://github.com/Neos-Metaverse/NeosPublic/issues/2433

**Closed by Frooxius** 2021-09-26 19:17 UTC
Labels: Enhancement
