### ISSUE TITLE
Put contact requests at the top of your contacts list

### ISSUE THREAD

**Issue by chemicalcrux** [Neos-Metaverse/NeosPublic#1864] opened 2021-03-23 18:26 UTC
## Is your feature request related to a problem? Please describe.
Contact requests are very subtle right now, making it a bit too easy to miss them.

## Relevant issues
I didn't see any when searching for "contact request" and "friend request"

## Describe the solution you'd like
Put pending contact requests at the top of your contact list, so that they're immediately visible when you open up the Contacts menu.

## Describe alternatives you've considered
Making the friend request more noticeable (I think it's silent?) and displaying a popup when you log in with pending requests, would also be helpful.

## Additional context
N/A

**Comment by shiftyscales** [comment] 2021-03-23 19:59
Contact requests currently already show a number on the contacts icon when you have one pending (similar to messages, etc.) I really wouldn't like the contact requests to be on the top of the list, if anything, I'd want them at the bottom, just above the offline users in my list, because I find they already often get in the way when trying to browse to a user marked as busy/away on my contacts list much less when trying to browse my contacts that are online if this change were made.

Either way as well, there will be a proper notification system in the future, it just needs to be developed, and UI for it made.

**Comment by FlameSoulis** [comment] 2021-03-24 04:51
The problem is if you have too many contacts. Perhaps a tab for 'new requests' in the contacts menu?

**Comment by Psychpsyo** [comment] 2021-03-25 03:03
I'd also prefer them below the people marked as away/busy instead. Having them at the very top would be absolutely terrible for me as I usually keep them around until I've seen someone a bit more often so I have a lot of requests on pending.
It might be best to have a separate tab for them.
That said, ordering them by most recent first would be really helpful.

**Comment by Frooxius** [comment] 2021-03-25 03:05
I think putting them at top would cause too many issues right now. I know some people are kinda keeping them there until they decide and this would require them scroll past them. 

The new contacts UI is planned to have collapsible categories and filters, which should take care of this.

**Closed** 2021-03-25 03:20 UTC
Labels: Enhancement, Won't Fix/Implement
