### ISSUE TITLE
add keybinding to desktop mode and keybinding in general

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3137] opened 2021-10-04 21:52 UTC
### Is your feature request related to a problem? Please describe.

the problem is I can't rekey bind my keys and also for VR players there controller

### Relevant issues

none that I could find

### Describe the solution you'd like

I know this is probably planned for the settings overhaul but in the settings you would be able to rekey bind your keys or VR inputs

and this probably won't be added in a good while

### Describe alternatives you've considered

none really

**Comment by shiftyscales** [comment] 2021-10-04 22:14
Duplicate of #1314 and this item is also featured on our roadmap.

https://github.com/Neos-Metaverse/NeosPublic/projects/1#card-54820820

**Closed by shiftyscales** 2021-10-04 22:14 UTC
Labels: Enhancement
