### ISSUE TITLE
Prevent reticle going below horizon check box on the Neos launcher no longer functions.

### ISSUE THREAD

**Issue by pushstartvr** [Neos-Metaverse/NeosPublic#2366] opened 2021-05-29 04:07 UTC
Hi again shifty.
There is a checkbox on the launcher specifically for screen 360 mode.
It is for planetarium use (dome theatre, 180) and prevents the cursor from going below the horizon whilst using in a dome theatre.
This feature no longer works.

Whilst in this mode, the new menu should not take up the full screen.  It should only be displayed in the top hemisphere as the bottom hemisphere is not visible in a dome theatre.

I requested this feature from froox in the early days and it has simply broken.

Cheers.

**Comment by ProbablePrime** [comment] 2021-05-29 04:28
Hey @pushstartvr thank you for providing additional details, this unfortunately still doesn't follow our template. Could you edit your original post to cover this?

**Comment by Frooxius** [comment] 2021-06-08 06:33
Closing this as Duplicate of https://github.com/Neos-Metaverse/NeosPublic/issues/2417, got already fixed in the recent build.

**Closed by Frooxius** 2021-06-08 06:33 UTC
Labels: Bug, Desktop Mode
