### ISSUE TITLE
Cant Import Avatar - Stuck on "Processing Rigged Meshes"

### ISSUE THREAD

**Issue by GearBell** [Neos-Metaverse/NeosPublic#2126] opened 2021-04-30 23:54 UTC
**Summary** - No matter what file type, no matter changing of the rig or changing of the mesh - avatar importing gets stuck on Processing Rigged Meshes on that little circle import indicator. Seems to import other avatars just fine, though oddly slower than usual.

**Detail** - Yes my avatars rigs tend to get on the wild side, however - this avatar is simply a remodeling of an old avatar, and that old avatar imports just fine. Ive tried these tests so far to see if any kind of change would get it to get passed the Processing Rigged Meshes infinite load:
Mesh original and Rig original - failed
Mesh original and simple new rig - failed
Simple new mesh and Rig Original - failed
Simple new mesh and simple new rig - failed
File types Ive tried: FBX, DAE, GLTF, Blend

The avatar consists of one mesh and one png material. The blendshapes on the mesh consists of standard visemes and mouth tracking shapekeys. I have tried restarting neos and clearing my cache - neither helped.

The original avatar this new one was remodeled on imports just fine, though oddly slow. No matter what Ive done with this particular new avatar - Neos gets stuck importing it.
I have included logs - I dont know which ones are what so Ive included Player Log and Neos Log.
[Player.log](https://github.com/Neos-Metaverse/NeosPublic/files/6408524/Player.log)

[DESKTOP-MGT25AS - 2021.4.29.1307 - 2021-04-30 15_57_00.log](https://github.com/Neos-Metaverse/NeosPublic/files/6408526/DESKTOP-MGT25AS.-.2021.4.29.1307.-.2021-04-30.15_57_00.log)

**Comment by AMonsoonofBabies** [comment] 2021-05-01 00:02
I can also confirm that I've had an import get stuck on this step before, though unfortunately I no longer have that file to test with. The file only contained a simple humanoid mesh and rig, built from scratch like other successful projects of mine.

**Comment by shiftyscales** [comment] 2021-05-01 00:07
By the look of things, it appears to potentially be an issue in hand rig detection again.

Can you provide a sample model/rig on this issue to test with, @GearBell?

**Comment by GearBell** [comment] 2021-05-01 00:11
how do i provide a sample model rig? ironically the hands are the only thing unaltered from the original. the simplified rig failed too.

**Comment by shiftyscales** [comment] 2021-05-01 00:16
You should be able to just drag and drop the file onto the comment box here on GitHub to upload it. Alternatively, you could just DM me it if you can't attach it here for some reason, @GearBell.

**Comment by GearBell** [comment] 2021-05-01 00:32
Here is a link to the fbx tests mentioned above - https://drive.google.com/drive/folders/1LfV9C3-EiNGD6WPLkZ-YGHxtvrrPDzx6?usp=sharing

**Comment by shiftyscales** [comment] 2021-05-01 01:30
I believe I identified the issue. The models have unapplied modifiers. When applying the modifier on the test box model, it imports properly, with the other models I get "Modifier cannot be applied to a mesh with shape keys", so the modifiers can't be applied.

**Comment by GearBell** [comment] 2021-05-01 02:02
unfortunatly the only modifier on the avatar is the armature one - applying it removes all weightpainting. however the fact that it successfully imported with no weightpainting narrows it down to weightpainting issue - however even if it were bad weightpainting, neos still imports that. it narrows it down, but does not identify the solution sadly.

**Comment by shiftyscales** [comment] 2021-05-01 03:03
GearBell had tried copying the mesh onto an older version of the rig she had modified to create the models that fail import. She re-weightpainted it, and it imported without issue. She noted it would be good to keep the issue open for the moment in case other models/cases crop up to try and identify the underlying cause.

**Comment by Frooxius** [comment] 2021-05-01 16:19
This looks like something in the naming/structure of the model that's tripping up Neos. I'll have a look on the sample model and see what it is.

**Comment by GearBell** [comment] 2021-05-01 21:11
Ive done a bit more testing and yes, it does seem to be the naming system. despite the fact that neos is made to ignore anything with the <NoIK> name in the bone name - it just simply ignored the one actual arm bone it was supposed to find. so, i went back, and one by one checked and renamed the ignorable bones with <NoIK> and imported each and every version until it worked. the arms were working. the hands though were disregarding the NoIK thing and chose to go with the dummy hands since they had stuff weightpainted to it - my solution from there was to weightpaint a simple cube to each true hand fingure, and then suddenly neos was happy and ignored the inteneded dummy hand and happily went with the cube hands, to which once in neos i deleted the cube mesh and neos still purred along. In short - if you have vital bones with nothing weightpainted to it at all, neos will ignore them and desperatly latch onto anything else of similar naming. Solution - if you have strange rigs like I do, it seems you now must have *something* weightpainted to vital bones (the standard arms, legs, spine, chest, etc) just get a cube and badly weightpaint it to those bones and delete it later once its in neos. I do not know if this was the correct solution to solve this issue, but it seemed to work. TLDR; make sure all necessary bones have something weightpainted to it.

**Comment by GearBell** [comment] 2021-05-01 21:12
actually now that i think about it, one of the testing models provided here does this and it still didnt work, so.... i have no idea. but what i did above ^ worked for my avatar specifically.

**Comment by Frooxius** [comment] 2021-05-02 03:56
I found the cause. It has nothing to do with naming, but rather it's because the hand skeleton isn't bound to any geometry at all. There is a mechanism in the rig detection, which rejects any objects that aren't actually mesh bones, since those typically cause problems.

However in your case it seems that the hand rig is just a dummy, without anything weightpainted to those bones, so it ends up rejecting all of the objects as not valid bones and that breaks it.

I have a fix coming in the next build for that, it should import correctly on that. Just to confirm that the hand mesh not being weightpainted to the base rig is intentional?

**Comment by GearBell** [comment] 2021-05-02 06:03
yes it is intentional

**Comment by Frooxius** [comment] 2021-05-04 08:08
Fixed in 2021.5.4.471, the sample models should now import correctly!

**Closed by Frooxius** 2021-05-04 08:08 UTC
Labels: Bug
