### ISSUE TITLE
Desktop FOV input field can input 0 FOV

### ISSUE THREAD

**Issue by win189** [Neos-Metaverse/NeosPublic#1981] opened 2021-04-09 03:35 UTC
IMPORTANT: PLEASE REPLACE OR DELETE (if not relevant) ANY TEXT IN BRACKETS [Like this] AND THIS ONE AS WELL

## Describe the bug
[A clear and concise description of what the bug is.]
When using My headset if i hit F8 to go into desktop mode my screen just goes white i can see and access and interact with the menu but everything else is blank and white

## Relevant issues
[Did you find any existing issues relevant to this one? If you found the same issue, please contribute to that one instead of making a duplicate.] if i dont use my headset aka Launch neos in desktop mode it works normal

## To Reproduce
[Steps to reproduce the behavior:
4. See error]

## Expected behavior
[A clear and concise description of what you expected to happen.]
i expected when i hit f8 to go into desktop mode 

## Screenshots / Video
[If applicable, add screenshots or a video to help explain your problem.]
![image](https://user-images.githubusercontent.com/24577138/114124441-780b0e80-98c2-11eb-8e2c-c127f8ec62e1.png)

## Bug information (please complete the following information):
 - How often does it happen: [Always, Sometimes, Only Once] every time
 - Does the bug persist after restarting Neos? [Yes/No] yes
 - Neos Version: [version number]2021.4.6.931
 - Neos Platform: [Any, Windows, Linux, Android/Quest] Windows
 - Link to reproduction World/Item: [Optional, but can speed up response for more complex reproduction cases]
 - Regression: [Did this work before? Yes (which build?) / No] yes  dont recall the buildnumber but it was before f8 was made primary

## Additional context
[Add any other context about the problem here.]

## Reporters:
[Usernames / Discord handles of anyone (including yourself) who has reported/replicated this bug (will be used to credit in release notes)]  Fuzy Sidwell

**Comment by win189** [comment] 2021-04-11 23:26
it also dosent work if i use screen only mode from the launcher

**Comment by shiftyscales** [comment] 2021-04-17 02:31
It appears the root cause of this issue is that the desktop FOV input field can accept an input value of 0 degrees, whereas the slider has a minimum clamp of 10. So effectively the 'white screen' was just a really zoomed in desktop cursor that filled the entire screen, @Frooxius.

**Comment by Frooxius** [comment] 2021-04-17 03:22
Fixed in 2021.4.17.185!

**Closed by Frooxius** 2021-04-17 03:22 UTC
Labels: Desktop Mode, Not a Bug, Tweak
