### ISSUE TITLE
Sort the hubs of nested sessions according to the total number of users

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2747] opened 2021-08-05 16:29 UTC
### Is your tweak request related to a problem? Please describe.

After the introduction of nested sessions, I noticed that the hub sessions are still being sorted by the number of users in the hub session itself, not the total number of users in the hub and all the nested sessions.
This makes it even harder for events to show up in the world browser, as sometimes the hub session is only used to choose a nested leaf to join, most of the time has 0 active users and thus falls off the active sessions list entirely.

### Describe what would you like tweaked

The hub session should use the total number of users in all nested sessions as the sort criteria.

### Describe alternatives you've considered

Not having nested sessions for events?

### Additional context

Metaverse Public Hub (under the cursor) shows 11 users in the hub plus two nested sessions, but is sorted between 4 and 2 user sessions:
![image](https://user-images.githubusercontent.com/675104/128615024-0fcd6fce-7bb3-4f83-a531-5a26104b9b6d.png)

**Comment by shiftyscales** [comment] 2021-08-05 19:59
I think this might be a regression, because I'm fairly certain it used to do exactly this.

**Comment by shadowpanther** [comment] 2021-08-06 19:11
> I think this might be a regression, because I'm fairly certain it used to do exactly this.

Might be. The feature was introduced not long ago, and I didn't see many session use it yet, so didn't get a "feel" how it worked before I noticed that it puts the session at the very end of the list or hides it, while still showing the correct total number of users visually. If it indeed was working properly before, then yes, it's a regression.

**Comment by Frooxius** [comment] 2021-08-12 21:49
Should be fixed in 2021.8.12.1293, thank you for the report!

**Closed by Frooxius** 2021-08-12 21:49 UTC
Labels: Tweak, Worlds, UI
