### ISSUE TITLE
Headless Cannot Start

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#3116] opened 2021-10-01 16:22 UTC
### Describe the bug?

Headless doesn't seem to be able to start anymore. Others are reporting the same issue since last night. Oddly enough I didn't have the issue when I restarted the headless then, but I do now. It'll throw these errors repeatedly (at a very long interval) before eventually failing with a "NO WORLD>" prompt.

### Relevant issues

None found.

### To Reproduce

Start a headless on Linux.

### Expected behavior

For it to start in the usual fashion.

### Log Files

No errors (or warnings) other than this in the terminal.

```
Exception running asynchronous task:
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object) ---> System.NullReferenceException: Object reference not set to an instance of an object
  at CloudX.Shared.CloudXInterface.Login (System.String credential, System.String password, System.String sessionToken, System.String secretMachineId, System.Boolean rememberMe, System.String recoverCode, System.String totp) [0x00256] in <0ef742e3738c4b92b10475b2069fb25c>:0
  at NeosHeadless.Program+<>c__DisplayClass25_0.<Main>b__2 () [0x001a1] in <9139e8d24ee041cca3ee81af5fca774d>:0
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object
  at CloudX.Shared.CloudXInterface.Login (System.String credential, System.String password, System.String sessionToken, System.String secretMachineId, System.Boolean rememberMe, System.String recoverCode, System.String totp) [0x00256] in <0ef742e3738c4b92b10475b2069fb25c>:0
  at NeosHeadless.Program+<>c__DisplayClass25_0.<Main>b__2 () [0x001a1] in <9139e8d24ee041cca3ee81af5fca774d>:0 <---


   at void BaseX.UniLog.Error(string message, bool stackTrace)
   at void FrooxEngine.CoroutineManager.CheckExceptions(Task task)
   at void System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke() in /home/ben/build/mono-git/src/mono/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 48
   at void System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in /home/ben/build/mono-git/src/mono/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2334
   at bool System.Threading.ThreadPoolWorkQueue.Dispatch() in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:line 785
   at bool System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:line 1261
```

Here's the entire log:

```
4:50:46 PM.540  Initializing Neos: Beta 2021.10.1.551
CPU: UNKNOWN, Processor Count: 16 (Physical: UNKNOWN)
Max GC Generation: 1, IsLittleEndian: True
System Memory: -1.00 B
GPU: UNKNOWN, VRAM: -1.00 B, POT Byte Aligned: True
System.Numerics.Vectors HW accelerated: True, Vector<float>.Count: 4
HeadDevice: Headless
4:50:46 PM.541  6.13.0 (makepkg/1bdb6cc55c3 Thu Sep  2 01:31:14 PM UTC 2021)
4:50:46 PM.541  Supported Texture Formats: Unknown, Alpha8, RGB24, ARGB32, RGBA32, BGRA32, RGBAHalf, ARGBHalf, RGBAFloat, ARGBFloat, BC1, BC2, BC3, BC4, BC5, BC6H, BC7, ETC2_RGB, ETC2_RGBA1, ETC2_RGBA8, ASTC_4x4, ASTC_5x5, ASTC_6x6, ASTC_8x8, ASTC_10x10, ASTC_12x12
4:50:46 PM.541  Argument: /home/steam/NeosVR/Neos.exe
4:50:46 PM.542  Available locales: cs, de, en, en-gb, eo, es, et, fi, fr, is, ja, ko, nl, no, pl, ru, sv, tr, zh-cn, zh-tw
4:50:46 PM.542  Loading Config.json...
4:50:46 PM.542  Computing compatibility hash...
4:50:46 PM.543  Compatibility Hash: EGOhsmgIlE8snT5taC1SGA==
4:50:46 PM.543  Initializing FrooxEngine...
4:50:46 PM.544          Initializing Libraries
4:50:46 PM.545  Configuring System.Net.ServicePointManager
4:50:46 PM.569  Calling Coder<T>
4:50:47 PM.074  Performing a dummy texture decode
4:50:47 PM.079  FreeImage Version: 3.18.0
4:50:47 PM.085  BepuPhysics Version: 2.4.0-neos3
4:50:47 PM.085  FreeType Version: 2.11.0
4:50:47 PM.085  Opus Version: libopus 1.1.3
4:50:47 PM.091  Exception Initializing AssimpContext:
Assimp.AssimpException: Error loading unmanaged library from path: Assimp64.so
  at Assimp.Unmanaged.AssimpLibraryLinuxImplementation.NativeLoadLibrary (System.String path) [0x0004e] in <2bbd770ad2e943ec9a89007d8dfbcb77>:0
  at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary (System.String path) [0x00007] in <2bbd770ad2e943ec9a89007d8dfbcb77>:0
  at Assimp.Unmanaged.AssimpLibrary.LoadLibrary () [0x00030] in <2bbd770ad2e943ec9a89007d8dfbcb77>:0
  at Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded () [0x00008] in <2bbd770ad2e943ec9a89007d8dfbcb77>:0
  at Assimp.Unmanaged.AssimpLibrary.GetExtensionList () [0x00000] in <2bbd770ad2e943ec9a89007d8dfbcb77>:0
  at Assimp.AssimpContext.GetSupportedImportFormats () [0x0000e] in <2bbd770ad2e943ec9a89007d8dfbcb77>:0
  at CodeX.AssetHelper..cctor () [0x00445] in <589e85daaf2840d5a1b61c702d4cd454>:0
4:50:47 PM.091  Supported 3D model formats: meshx
4:50:47 PM.092  Supported point cloud formats: pts, las, laz
4:50:47 PM.092  Supported image formats: bmp, ico, jpg, jif, jpeg, jpe, jng, koa, iff, lbm, mng, pbm, pcd, pcx, pgm, png, ppm, ras, tga, targa, tif, tiff, wap, wbmp, wbm, psd, psb, cut, xbm, xpm, dds, gif, hdr, g3, sgi, rgb, rgba, bw, exr, j2k, j2c, jp2, pfm, pct, pict, pic, 3fr, arw, bay, bmq, cap, cine, cr2, crw, cs1, dc2, dcr, drf, dsc, dng, erf, fff, ia, iiq, k25, kc2, kdc, mdc, mef, mos, mrw, nef, nrw, orf, pef, ptx, pxn, qtk, raf, raw, rdc, rw2, rwl, rwz, sr2, srf, srw, sti, x3f, webp, jxr, wdp, hdp
4:50:47 PM.092  Supported audio formats: wav, wave, flac, ogg
4:50:47 PM.092  Supported video formats: mp4, mpeg, avi, mov, mpg, mkv, flv, webm, mts, 3gp, bik, m2v, m2s, wmv, m3u8, m3u, pls, m4a, mp3, aac, ac3, aif, aiff, ape, au, it, mka, mod, mp1, mp2, opus, s3m, sid, w64, wma, xm, nsf, nsfe, gbs, vgm, vgz, spc, gym
4:50:47 PM.092  Supported font formats: ttf, otf, ttc, otc, woff
4:50:47 PM.092  Supported subtitle formats: srt, sub, sub, ssa, ttml, vtt
4:50:47 PM.092          Gathering all types
4:50:47 PM.093  Assembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
4:50:47 PM.096  Assembly: Neos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.096  Assembly: FrooxEngine, Version=2021.10.1.551, Culture=neutral, PublicKeyToken=null
4:50:47 PM.111  Assembly: System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
4:50:47 PM.111  Assembly: CodeX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.111  Assembly: CommandLine, Version=2.8.0.0, Culture=neutral, PublicKeyToken=5a870481e358d379
4:50:47 PM.112  Assembly: Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
4:50:47 PM.114  Assembly: CloudX.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.115  Assembly: BaseX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.116  Assembly: System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
4:50:47 PM.116  Assembly: CommandX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.116  Assembly: BusinessX, Version=2021.10.1.552, Culture=neutral, PublicKeyToken=null
4:50:47 PM.116  Assembly: System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
4:50:47 PM.116  Assembly: System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
4:50:47 PM.116  Assembly: System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
4:50:47 PM.116  Assembly: System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
4:50:47 PM.116  Assembly: System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
4:50:47 PM.116  Assembly: System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
4:50:47 PM.116  Assembly: System.Text.Json, Version=5.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
4:50:47 PM.116  Assembly: System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
4:50:47 PM.116  Assembly: PostX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.116  Assembly: System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
4:50:47 PM.116  Assembly: Octokit, Version=0.50.0.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.117  Assembly: LiteNetLib, Version=1.0.7767.18715, Culture=neutral, PublicKeyToken=null
4:50:47 PM.117  Assembly: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
4:50:47 PM.117  Assembly: LiteDB, Version=4.1.5.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27
4:50:47 PM.118  Assembly: SharpFont, Version=4.0.1.200, Culture=neutral, PublicKeyToken=48add4c483071cdf
4:50:47 PM.118  Assembly: System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
4:50:47 PM.118  Assembly: netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
4:50:47 PM.118  Assembly: System.Collections, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
4:50:47 PM.118  Assembly: System.Runtime.InteropServices, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
4:50:47 PM.118  Assembly: Ben.Demystifier, Version=0.1.0.0, Culture=neutral, PublicKeyToken=a6d206e05440431a
4:50:47 PM.119  Assembly: FreeImageNET, Version=3.15.1.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.119  Assembly: BepuPhysics, Version=2.4.0.1, Culture=neutral, PublicKeyToken=9345ce38ee48a1cd
4:50:47 PM.121  Assembly: BepuUtilities, Version=2.4.0.1, Culture=neutral, PublicKeyToken=a595ef937c270ac9
4:50:47 PM.121  Assembly: POpusCodec, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.121  Assembly: AssimpNet, Version=3.2.0.0, Culture=neutral, PublicKeyToken=0d51b391f59f42a6
4:50:47 PM.121  Assembly: SubtitlesParser, Version=1.4.8.0, Culture=neutral, PublicKeyToken=null
4:50:47 PM.121          Initializing connector fields for core classes
4:50:47 PM.154                  Initializing connector for FrooxEngine.AudioSystem
4:50:47 PM.254                  Initializing connector for FrooxEngine.AssetManager
4:50:47 PM.256  No connectors for: FrooxEngine.AssetManager
4:50:47 PM.256                  Initializing connector for FrooxEngine.Slot
4:50:47 PM.258  No connectors for: FrooxEngine.Slot
4:50:47 PM.258                  Initializing connector for FrooxEngine.RenderManager
4:50:47 PM.259  No connectors for: FrooxEngine.RenderManager
4:50:47 PM.260                  Initializing connector for FrooxEngine.World
4:50:47 PM.261  No connectors for: FrooxEngine.World
4:50:47 PM.261                  Initializing connector for FrooxEngine.WorldManager
4:50:47 PM.262  No connectors for: FrooxEngine.WorldManager
4:50:47 PM.293          Initializing asset classes
4:50:47 PM.300          Initializing workers
4:50:47 PM.301  Extracting Connectors
4:50:47 PM.337  Extracting Workers
4:50:47 PM.340  Initializing non-generic workers
4:50:47 PM.455  Initializing LogiX
4:50:47 PM.475  Initialized Logix in 00:00:00.0193543, workers: 4909, LogixNodes: 3631, overloads: 154
4:50:47 PM.482  Initializing InputInterface...
4:50:47 PM.494  Initializing LocalDB...
4:50:47 PM.509          Reading settings file
4:50:47 PM.520          Performing version checks and updates, loaded version: 8
4:50:47 PM.521  MachineID: 3eqxf_36huqlpjlpqvqlza
4:50:47 PM.521          Loading LiteDB database
4:50:47 PM.701          Configuring LiteDB database
4:50:47 PM.781  Saving Settings
4:50:47 PM.785  Initializing JobProcessor...
4:50:47 PM.799  Initialized WorkProcessor. Background Workers: 16, Priority Workers: 15
4:50:47 PM.799  Initializing AssetManager...
4:50:47 PM.847  Initializing NetworkManager...
4:50:47 PM.848  Initializing AudioSystem...
4:50:47 PM.886  Initializing GlobalCoroutineManager...
4:50:47 PM.892  Initializing WorldManager...
4:50:47 PM.899  Initializing CloudX Interface...
4:50:47 PM.902  HttpClient AutomaticDecompressionSupported: True
4:50:47 PM.931  DoNotSendReadStatus set to: False
4:50:47 PM.931  Initializing SecurityManager...
4:50:47 PM.932  Initializing RecordManager...
4:50:47 PM.932  Initializing PlatformInterface...
4:50:47 PM.933          Steam
4:50:48 PM.021  SteamAPI failed to initialize

   at void BaseX.UniLog.Error(string message, bool stackTrace)
   at void FrooxEngine.SteamConnector.InitializeSteamAPI()
   at async Task<bool> FrooxEngine.SteamConnector.Initialize(PlatformInterface platformInterface)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<<Initialize>d__32>(ref <Initialize>d__32 stateMachine) in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 459
   at Task<bool> FrooxEngine.SteamConnector.Initialize(PlatformInterface platformInterface)
   at async Task FrooxEngine.PlatformInterface.Initialize(Engine engine)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<<Initialize>d__12>(ref <Initialize>d__12 stateMachine) in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 304
   at Task FrooxEngine.PlatformInterface.Initialize(Engine engine)
   at async Task FrooxEngine.Engine.Initialize(string appPath, string dataPath, string cachePath, ISystemInfo systemInfo, IInternalResource resources, bool verboseInit)
   at void System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<<Initialize>d__291>(ref <Initialize>d__291 stateMachine) in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:line 304
   at Task FrooxEngine.Engine.Initialize(string appPath, string dataPath, string cachePath, ISystemInfo systemInfo, IInternalResource resources, bool verboseInit)
   at void NeosHeadless.Program.Main(string[] args)
4:50:48 PM.022  Initializing WorldAnnouncer...
4:50:48 PM.026  Initializing NetworkManager...
4:50:48 PM.027  Supported network protocols: lnl-nat, lnl
4:50:48 PM.027  FrooxEngine Initialized in 1488.8786 ms
4:50:48 PM.027  FrooxEngine Initialization Finished
4:50:48 PM.028  Starting Userspace world
4:50:48 PM.324  MaxUsers set to 1. LastModifyingUser:

   at void BaseX.UniLog.Log(string message, bool stackTrace)
   at void FrooxEngine.WorldConfiguration.FieldChanged(IChangeable obj)
   at void FrooxEngine.SyncElement.SyncElementChanged(IChangeable member)
   at void FrooxEngine.SyncField<int>.ValueChanged()
   at bool FrooxEngine.SyncField<int>.InternalSetValue(in int value, bool sync, bool change)
   at void FrooxEngine.SyncField<int>.set_Value(int value)
   at void FrooxEngine.Sync<int>.set_Value(int value)
   at void FrooxEngine.World.set_MaxUsers(int value)
   at World FrooxEngine.World.LocalWorld(WorldManager manager, WorldAction init, DataTreeNode load, bool unsafeMode)
   at World FrooxEngine.WorldManager.StartLocal(WorldAction init, DataTreeDictionary load)
   at World FrooxEngine.Userspace.SetupUserspace(Engine engine)
   at void NeosHeadless.Program.Main(string[] args)
4:50:48 PM.567  Starting running world:
4:50:48 PM.585  Userspace world started, attaching Userspace component
4:50:48 PM.606  Userspace on Attach, running setup
4:50:48 PM.606  Processing commandline arguments
4:50:48 PM.690  Running default bootstrap
4:50:48 PM.699  Setting URL: local://3eqxf_36huqlpjlpqvqlza/1o7_yecYUkuVzpZO762ULw.lz4bson
4:50:48 PM.879  DoNotSendReadStatus set to: False
4:50:48 PM.921  WorldName set to Userspace. LastModifyingUser:

   at void BaseX.UniLog.Log(string message, bool stackTrace)
   at void FrooxEngine.WorldConfiguration.FieldChanged(IChangeable obj)
   at void FrooxEngine.SyncElement.SyncElementChanged(IChangeable member)
   at void FrooxEngine.SyncField<string>.ValueChanged()
   at bool FrooxEngine.SyncField<string>.InternalSetValue(in string value, bool sync, bool change)
   at void FrooxEngine.SyncField<string>.set_Value(string value)
   at void FrooxEngine.Sync<string>.set_Value(string value)
   at void FrooxEngine.World.set_Name(string value)+() => { }
   at void FrooxEngine.World.RunSynchronousActions()
   at void FrooxEngine.World.NextRefreshStage()
   at bool FrooxEngine.World.Refresh()
   at void FrooxEngine.WorldManager.UpdateStep(double maxMilliseconds)
   at bool FrooxEngine.WorldManager.RunUpdateLoop(double maxMilliseconds)
   at void FrooxEngine.Engine.UpdateStep(double maxMilliseconds)
   at void FrooxEngine.Engine.RunUpdateLoop(double maxMilliseconds)
   at void NeosHeadless.Program.UpdateLoop()
   at void System.Threading.ThreadHelper.ThreadStart_Context(object state) in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/threading/thread.cs:line 71
   at void System.Threading.ThreadHelper.ThreadStart() in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/threading/thread.cs:line 109
4:50:48 PM.967  User Joined Userspace. Username: q3, UserID: , MachineID: 3eqxf_36huqlpjlpqvqlza
4:50:49 PM.978  User Spawn Userspace. Username: q3, UserID: , MachineID: 3eqxf_36huqlpjlpqvqlza
4:50:49 PM.984  Logging in as EnverexBot
4:50:49 PM.986  DoNotSendReadStatus set to: False
4:50:51 PM.459  Exception running asynchronous task:
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object) ---> System.NullReferenceException: Object reference not set to an instance of an object
  at CloudX.Shared.CloudXInterface.Login (System.String credential, System.String password, System.String sessionToken, System.String secretMachineId, System.Boolean rememberMe, System.String recoverCode, System.String totp) [0x00256] in <0ef742e3738c4b92b10475b2069fb25c>:0
  at NeosHeadless.Program+<>c__DisplayClass25_0.<Main>b__2 () [0x001a1] in <9139e8d24ee041cca3ee81af5fca774d>:0
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object
  at CloudX.Shared.CloudXInterface.Login (System.String credential, System.String password, System.String sessionToken, System.String secretMachineId, System.Boolean rememberMe, System.String recoverCode, System.String totp) [0x00256] in <0ef742e3738c4b92b10475b2069fb25c>:0
  at NeosHeadless.Program+<>c__DisplayClass25_0.<Main>b__2 () [0x001a1] in <9139e8d24ee041cca3ee81af5fca774d>:0 <---


   at void BaseX.UniLog.Error(string message, bool stackTrace)
   at void FrooxEngine.CoroutineManager.CheckExceptions(Task task)
   at void System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke() in /home/ben/build/mono-git/src/mono/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 48
   at void System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in /home/ben/build/mono-git/src/mono/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2334
   at bool System.Threading.ThreadPoolWorkQueue.Dispatch() in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:line 785
   at bool System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /home/ben/build/mono-git/src/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:line 1261
```

### How often does it happen?

Sometimes

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.10.1.551

### What Platforms does this occur on?

Linux

### Did this work before?

Yes

**Comment by shadowpanther** [comment] 2021-10-01 16:52
Can confirm - here's my own log.
[manul - 2021.10.1.551 - 2021-10-01 19_48_05.log](https://github.com/Neos-Metaverse/NeosPublic/files/7268844/manul.-.2021.10.1.551.-.2021-10-01.19_48_05.log)

**Comment by Lexevolution** [comment] 2021-10-01 17:14
[lex-media_-_2021.10.1.551_-_2021-10-01_22_10_49.log](https://github.com/Neos-Metaverse/NeosPublic/files/7268976/lex-media_-_2021.10.1.551_-_2021-10-01_22_10_49.log)
I'm having similar issues too. Cannot fully start my headless.

**Comment by WallTack** [comment] 2021-10-01 18:27
Same exception here
[ns5005928 - 2021.10.1.551 - 2021-10-01 17_52_11.log](https://github.com/Neos-Metaverse/NeosPublic/files/7269403/ns5005928.-.2021.10.1.551.-.2021-10-01.17_52_11.log)

**Comment by RoxyBoxxy** [comment] 2021-10-01 18:46
Same here 
[b9522e73-4187-40b7-be49-cb7daf4011f2 - 2021.10.1.551 - 2021-10-01 18_02_13.log](https://github.com/Neos-Metaverse/NeosPublic/files/7269474/b9522e73-4187-40b7-be49-cb7daf4011f2.-.2021.10.1.551.-.2021-10-01.18_02_13.log)

**Comment by Frooxius** [comment] 2021-10-01 21:45
Hmm, this is a bit of an odd one. The API reports that automatic response decompression is supported, but then it seems like it actually doesn't support it, so it can't get any data from the response. As far as I can tell on Windows Mono this is fine, it's only Linux Mono that seems to be affected. 

I've pushed a build 2021.10.1.1298 which explicitly disables it on Linux despite the reported support status, hopefully this helps. Please give it a try and see if that resolves the issue!

**Comment by WallTack** [comment] 2021-10-01 21:52
Confirmed - working for me now on 2021.10.1.1298

**Comment by Frooxius** [comment] 2021-10-01 21:54
Sweet thank you! Closing this for now!

**Closed by Frooxius** 2021-10-01 21:54 UTC
Labels: Bug, High Priority, Headless/Server System, Linux, Waiting on fix confirmation
