### ISSUE TITLE
New user completed the intro pages, then got stuck on blank page.

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#1408] opened 2020-11-28 01:22 UTC
A new user (on discord they are Gramophonical) joined the tutorial world WIP world and reported they completed entering their height, submitted it, and then was greeted with a blank screen.

Here is the log, it looks like my world is spewing errors so I'll need to fix that, but it looks like a single exception occurred for them.
[MSI_-_2020.11.27.277_-_2020-11-27_16_57_35.log](https://github.com/Frooxius/NeosPublic/files/5609907/MSI_-_2020.11.27.277_-_2020-11-27_16_57_35.log)

**Comment by Earthmark** [comment] 2020-11-28 01:28
[MSI_-_2020.11.27.277_-_2020-11-27_17_18_47.log](https://github.com/Frooxius/NeosPublic/files/5609912/MSI_-_2020.11.27.277_-_2020-11-27_17_18_47.log)
it iccurred for them again, but succeeded the third time

**Comment by Earthmark** [comment] 2020-11-29 08:52
looks like a quest ran into this today, dont have a log this time though
iceyalt9 was the username

**Comment by shiftyscales** [comment] 2020-12-01 01:54
I'm not certain I'm understanding what the underyling issue is/what you're proposing? This is regarding your community-made tutorial world? What is the actual issue itself/can it be replicated in isolation outside of that world/setup?

**Comment by Earthmark** [comment] 2020-12-01 08:45
A new user going through the neos system initial tutorial reported that the tutorial page went not blank on them and they couldn't interact with it anymore. I'm not sure how they got to my world but they did and that's when I reported it. The next day Player Kode alerted me that they ran into another player who had the same experience and whom found their way to kodes world. 

It seems some bug in the neos tutorial, the one where you pick your language, configure your height, and choose your microphone has some condition where the dashboard turns black and goes non responsive.

**Comment by shiftyscales** [comment] 2020-12-01 15:31
Do you know for certain if it's the tutorial panels in the local home/on the dashboard? Or is it the tutorial panel inside of the MTC where they were having the issue?

I have just now realized there is a session joiner plate in the local home though- that's probably how they got into your session in the first place...

**Comment by Earthmark** [comment] 2020-12-01 16:42
It seems to be the local home dashboard panels, the user who joined my world was unable to use the home screen of the dash. They were unable to close the dash as well, and apparently the bottom buttons were greyed out.

**Comment by Earthmark** [comment] 2020-12-01 16:43
I'm not sure of a replication case, but it's apparently happened to two users so possibly it's a low chance race condition. Possibly this is related to the patch notes about race conditions?

**Comment by shiftyscales** [comment] 2020-12-01 17:48
> It seems to be the local home dashboard panels, the user who joined my world was unable to use the home screen of the dash. They were unable to close the dash as well, and apparently the bottom buttons were greyed out.

Okay, so it does sound like they ended up joining in on your session from the session joiner in their local home. The dash is unable to be closed or screens changed until you progress to the MTC tutorial, it is then unable to be reopened until you complete the MTC tutorial.

I've made an issue, #1424 to help ensure that specific scenario doesn't come up where a user accidentally leaves their local home early- but as for the dash itself breaking, I can't say I saw anything specific in the logs you've provided suggesting what the issue might otherwise be.

**Comment by Earthmark** [comment] 2020-12-01 17:57
They specifically said the screen locked up and they had nowhere to go, and I do not believe they had completed the local world tutorial yet.
I'm worried that removing the joiner may result in hiding the issue if it's a different one than you described, as new users will get super stuck instead of soft stuck.

**Comment by shiftyscales** [comment] 2020-12-01 18:03
If a cause/replication case can be made for the dash itself becoming unusable, that would help a lot. Either way, users joining other sessions before unlocking their dash is problematic in of itself, so I think it'd still help. If they did get hard-stuck, hopefully they would consider rebooting Neos if necessary. But from what's been reported so far, that might very well be an edge case.

Did the users say how they happened to come into your sessions? Did they intentionally seek it out because their dash was stuck? Or did they accidentally stumble into it, and later realize they had no way to progress?

**Comment by Aerizeon** [comment] 2020-12-01 18:41
From what I remember, he stumbled into the session accidentally (or maybe because it had "Tutorial" in the session.).

We did walk him through posting a screenshot of his dashboard at the time, but i don't recall if I saved it (perhaps Earthmark did), but from what I remember, the only visible elements were the dashboard screen frames, none of the screen content.

**Comment by Earthmark** [comment] 2020-12-01 18:55
I don't have it in my downloads, and I don't see it inside neos, I don't think I saved it or such. Either way, I agree with what @Aerizeon says, I do recall seeing that exact thing in the picture. He took the picture by taking a desktop screenshot, so it contained his dashboard as was rendered on his display.

**Comment by Frooxius** [comment] 2020-12-02 00:11
Hmm I don't really see anything in those logs, the user seems to join the community made tutorial soon after start. Are those the correct logs? 

Does the tutorial always break after the same page? Is it right after the height setting page?

**Comment by Aerizeon** [comment] 2020-12-02 00:13
His report was that both times it occurred, it was after he typed in his height in the field and pressed enter. 

I think it was something odd, like `5' 2"`
Not sure if the input format was set to Imperial

**Comment by Frooxius** [comment] 2020-12-02 00:18
He mentioned another user having the same issue though, but I'm not too sure if that one was at the same page as well. 

The input format doesn't matter, you can type it in any units. It only matters for what the parsed value is displayed as.

**Comment by Earthmark** [comment] 2020-12-02 02:16
The second person I heard about second hand from Player Kode on neos, they didn't get logs but I recorded their username in here.

Both logs are from the first user, they encountered the bug twice in a row, then on the third time got through it just fine.
That they imperially knew when it was resolved also suggests to me this isn't them hitting the wrong button early, something was clearly incorrect to the user to the point they recognized it.

I have their discord should you want additional feedback from them about it.

**Comment by shiftyscales** [comment] 2020-12-05 23:46
Furf#7691 has provided a couple of logs and a screenshot from when this issue has occurred for them, @Frooxius.

https://cdn.discordapp.com/attachments/439422161657135106/784761113400049674/FURFTOP_-_2020.12.5.608_-_2020-12-05_07_10_56.log

https://cdn.discordapp.com/attachments/439422161657135106/784761115727888404/FURFTOP_-_2020.12.5.608_-_2020-12-05_07_25_42.log

![image](https://user-images.githubusercontent.com/54213390/101267725-d9528380-3710-11eb-9562-26457dccbfa6.png)

**Comment by Frooxius** [comment] 2021-01-29 08:34
I added a timeout before the button to go to the next page can be pressed, on a slight suspicion that they might be clicking the button twice in a row and somehow breaking things, but I'm not too sure if that's really the cause.

I've added a bunch of detailed logging in 2021.1.29.504 as well, so if you encounter someone with this issue again, please have them send logs!

**Comment by shiftyscales** [comment] 2021-04-01 16:44
I've not heard any reports of this issue happening since the changes were made. Closing out this issue.

**Closed by shiftyscales** 2021-04-01 16:44 UTC
Labels: Needs More Information
