### ISSUE TITLE
PBS Multi UV Metalic breaks on setting AlphaClip mode

### ISSUE THREAD

**Issue by AlexThorin** [Neos-Metaverse/NeosPublic#1807] opened 2021-03-06 09:58 UTC
IMPORTANT: PLEASE REPLACE OR DELETE (if not relevant) ANY TEXT IN BRACKETS [Like this] AND THIS ONE AS WELL

## Describe the bug
[Materal goes "waiting to apply" and turns pink.]

## Relevant issues
[N/A]

## To Reproduce
[Start with a PBS Multi UV Metallic
Apply a Albedo texture with alpha
Apply a normal map
Apply a secondary albedo texture with no alpha
Set alpha mode to Alpha Clip
The material should set waiting to apply true once the alpha mode is set and shortly after turn pink]

## Expected behavior
[Expected the material to alpha using the Abedo texture (not secondary albedo) as a reference for where to alpha.]

## Screenshots / Video
[Google Drive link to video of replicating the issue
https://drive.google.com/file/d/1IwLbCbcq6gyq0R6h5ymG05mQjpSVv-Iu/view?usp=sharing]

## Bug information (please complete the following information):
 - How often does it happen: [Always]
 - Does the bug persist after restarting Neos? [Yes]
 - Neos Version: [BETA 2021.3.5.371]
 - Neos Platform: [Windows]
 - Link to reproduction World/Item: [N/A]
 - Regression: [Unsure]

## Additional context
[N/A]

## Reporters:
[Neos: Alex Thorin
Discord: Alex Thorin#9381]

**Comment by shadowpanther** [comment] 2021-03-06 10:25
Duplicate of #1804

**Closed** 2021-04-25 20:58 UTC
Labels: Bug, Duplicate, Materials/Shaders
