### ISSUE TITLE
LogiX: Read Dynamic Variable does not update when variable is changed

### ISSUE THREAD

**Issue by mpmxyz** [Neos-Metaverse/NeosPublic#2798] opened 2021-08-14 22:48 UTC
### Describe the bug?

_Read Dynamic Variable_ nodes only change their output when one of their inputs changes.
Changing the value of the dynamic variable does not change the output.
New connections to the output receive the updated value but also ignore future changes.

### Relevant issues

I searched for "Read Dynamic" and did not find matching issues.

### To Reproduce

Create a basic Dynamic Variable setup, read the variable using _Read Dynamic Variable_ node and change the value of the variable. (e.g. using an Inspector Window)

### Expected behavior

The output of the LogiX node should change.

### Screenshots

Initial State:
![20210815000913_1](https://user-images.githubusercontent.com/8538547/129461983-8a948f17-76d1-4e81-8ba3-e282276a3c28.jpg)

After Changing value:
![20210815000927_1](https://user-images.githubusercontent.com/8538547/129461984-cc07b259-2d60-4b7d-8c56-6516d975bd37.jpg)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Current

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

"neosrec:///U-TheAutopilot/R-79d31a2d-ef6e-4376-b149-6c35c9bb0140", spawn item "Read Dynamic Variable Bug"

### Did this work before?

I Don't Know

### Additional context

It looks like _Dynamic Variable Input_ is directly connected to the dynamic variable system but _Read Dynamic Variable_ is not.

### Reporters

TheAutopilot

**Comment by shadowpanther** [comment] 2021-08-14 23:16
This is how the Read node works. If you were to use it in an impulse evaluation context, it would be updated with the current value, but otherwise it does not produce regular updates. Use the DynVar Input node that you already have there to get proper updates, or use an Updating Relay.

**Comment by ProbablePrime** [comment] 2021-08-14 23:44
Shadow Panther, is right here. You can also, use an updating relay on the output of Read Dynamic Variable. 

Its how many nodes work here in Neos where an evaluation will force an update otherwise it is stationary. 

You can read some information about the introduction of Dynamic Variable Input here: https://discord.com/channels/402159838827905024/469131434628612116/757511724893995074

It's highly recommended to use Input where you can due to this behaviour etc. 

Due to this being not a bug, I will close this one for now.

**Closed** 2021-08-14 23:44 UTC
Labels: LogiX, Not a Bug

**Comment by mpmxyz** [comment] 2021-08-15 00:27
Hmm... That's not really satisfying.
My use case involves a slot selection and displaying formatted values from it.
Those values can change but usually stay the same for a longer time.
-> Using _Updating Relay_ to update _every_ frame is a waste.
-> _Dynamic Variable Input_ cannot read from different slots

There are 2 workarounds I know of:
-manual updating using dynamic impulses (with less frequency than _Updating Relay_)
-moving "probe slots" into the slot hierarchy you want to look at

Both workarounds add quite a lot of (programming) overhead to the simple task of "Let this be the current value of VarA.VarB."

What makes this behaviour confusing is the fact that most, if not all, other nodes that refer to a "state" of a slot update their values automatically.
This automatic update allows one use LogiX in a declarative way up to the point where you are explicitly interested in state.
(Which is where Impulses come into play; they represent state changes.)

While the behaviour may be intended I would argue it should be adjusted. If breaking existing LogiX is a concern I would vote for an additional boolean parameter e.g. "autoUpdate" with default value "false".

**Comment by ProbablePrime** [comment] 2021-08-15 00:33
I would use Updating Relay here. Its actually not that bad when used in moderation.

Some nodes will auto-update and some won't. It depends on how they're created internally within our code base. I agree it is confusing but we'll eventually be making this clearer.

For specifically this node, I don't think we'd be unable to change it to an auto-updating flow, this is one of the reasons the Input variant was created. It handles things a little more optimally.
