### ISSUE TITLE
add null button to every single input node

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3300] opened 2021-11-03 00:49 UTC
### Is your feature request related to a problem? Please describe.

I want an Null button to every single input node like the string input
![image](https://user-images.githubusercontent.com/76523692/139970765-dfb4dc01-444d-437e-b5a1-425643133e71.png)

### Relevant issues

none that I could find

### Describe the solution you'd like

I would like for every single input node to have a Null button like the demonstration above

### Describe alternatives you've considered

none that I can think of maybe using mods or plugins but that is hacky

**Comment by Frooxius** [comment] 2021-11-03 00:49
Duplicate of: https://github.com/Neos-Metaverse/NeosPublic/issues/3052

**Closed by Frooxius** 2021-11-03 00:49 UTC
Labels: Enhancement
