### ISSUE TITLE
Quickly editing values via simple math equations

### ISSUE THREAD

**Issue by amplified1** [Neos-Metaverse/NeosPublic#3439] opened 2021-12-07 19:43 UTC
### Is your feature request related to a problem? Please describe.

Typing in values, especially with the VR keyboard, can be a bit tedious, this set of shortcuts could make it a bit easier to quickly make edits to values without having to clear them and can also be helpful for when a value needs to be an exact multiple of another value, for example standard texture resolutions.

### Describe the solution you'd like

When somebody types a `/x` `*x` `-x` or `+x` after a value it will set the value to the answer of that equation. To demonstrate further, you have a value set to `256` on the inspector, you then type a `*4` after it so that it says `256*4`, but immediately after pressing enter the value automatically converts to `1024`. This is a feature that blender has and I use it regularly.

### Describe alternatives you've considered

Dedicated buttons for doing these operations could also work, but I think that it is best to not add more to the UI like that.

**Comment by shadowpanther** [comment] 2021-12-07 19:46
This is a duplicate of #1571

**Closed by shadowpanther** 2021-12-07 19:46 UTC
Labels: Enhancement
