### ISSUE TITLE
Random World Tab or Spawn Random World Orb button

### ISSUE THREAD

**Issue by GearBell** [Neos-Metaverse/NeosPublic#2746] opened 2021-08-05 15:23 UTC
### Is your feature request related to a problem? Please describe.

World hopping is a great way to see what everyone has made in Neos, however lots of worlds get buried or skipped - just like in VRChat they had a Random Worlds tab, allowing even the most obscure worlds to be visited by world hoppers. Can we get one please? Or perhaps even a Pick Random World button to spawn a singular world orb.
Its a great way to see much more of Neos for those hole-in-the-wall worlds people never thought to look at. (And would give lots of people more things to do in regards of world hopping activities)

### Describe the solution you'd like

Solution - 
A) Random World Tab, perhaps scrambling its list once an hour.
B) A dashboard button in Worlds Tab to Summon Random World Orb

### Describe alternatives you've considered

The only other alternative was logix "hacking" neos to pick a random world orb (i honestly have no idea how it worked but was told it "was not pretty")

**Comment by shadowpanther** [comment] 2021-08-05 15:28
Duplicate of #2566.

**Closed by shadowpanther** 2021-08-05 15:28 UTC
Labels: Enhancement, Worlds, UI
