### ISSUE TITLE
Emergency exiting out of closing session softlocks you.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2327] opened 2021-05-23 17:28 UTC
## Is your tweak request related to a problem? Please describe.
When using the emergency exit gesture in the 'closing Neos', session, you'll leave the session and Neos won't shut down but your dash will also not open anymore.

## Describe what would you like tweaked
Reactivate the dash when a user exits the 'exiting Neos' session.

## Describe alternatives you've considered
-making it impossible to leave that session which just restricts a player's options.
-leaving this as-is so Neos just needs to be force-closed in this situation.

**Comment by Frooxius** [comment] 2021-05-23 20:09
We cannot reactivate the dash or cancel the exit, because Neos is already in irreversible shutdown process, but we can prevent that gesture from working when exiting.

**Comment by Psychpsyo** [comment] 2021-05-24 14:18
Huh. Then I might've not waited for long enough for Neos to shut down afterwards. Disabling the gesture should be fine then.

**Comment by TehTurk** [comment] 2021-07-12 23:16
This seems resolved should I close this @Psychpsyo ?

**Comment by shiftyscales** [comment] 2021-07-14 00:12
> 
> 
> This seems resolved should I close this @ Psychpsyo ?

If you've confirmed it's fixed, then please close it, @TehTurk.

**Comment by Psychpsyo** [comment] 2022-03-03 11:58
> This seems resolved should I close this @Psychpsyo ?

I just tested it again and no, it is not solved. (This was in desktop mode, using Ctrl+Shift+Q)
Due to that I'd also like to add that, in desktop mode, this locks you out of looking around. (Except when using freecam, then looking around still works but the cursor is permanently visible and moving across the screen.)

Also, this may be related / the same problem as in #436

**Closed** 2024-04-14 08:25 UTC
Labels: Tweak
