### ISSUE TITLE
World crash when avatar is spanwed while having ChildParentAudioClipPlayer or ButtonAudioClipPlayer are on the avatar

### ISSUE THREAD

**Issue by kulzae** [Neos-Metaverse/NeosPublic#2974] opened 2021-09-09 03:20 UTC
### Describe the bug?

Experiencing world crashing upon joining or when spawning avatar using the lightning bolt button while avatar has ChildParentAudioClipPlayer or ButtonAudioClipPlayer 

### Relevant issues

no

### To Reproduce

join or spawn into world using my avatar with the components on it

### Expected behavior

Not crashing

### How often does it happen?

Sometimes

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.8.1291

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

**Comment by Frooxius** [comment] 2021-09-09 06:25
Do you have a log file for this? Usually crashes leave stack traces in logs that make them easy to fix, but without one it's much difficult to find the cause.

**Comment by kulzae** [comment] 2021-09-09 13:47
Im asking the host of the world I joined for log from that session. i dont think the log of the headless i was in would be relevant as that one was on 946

**Comment by Frooxius** [comment] 2021-09-09 13:58
If the headless was on 946 then it's likely the bug that was fixed in 2021.9.8.1291. Does this still happen when everyone is on the latest build?

**Comment by kulzae** [comment] 2021-09-09 14:03
The headless i was currently in was in 946. the host i was joining was on 1291 as was I. after i noticed the session i joined had crashed i swapped my av while in the headless and caused that to crash as well

**Comment by kulzae** [comment] 2021-09-09 14:07
I cant seem to get it to occur again. like i said im getting the logs from the host of that session i just need to wait for them.

would it be possible having a mixed bag of client versions could cause the host to crash?

**Comment by Frooxius** [comment] 2021-09-09 14:41
Yes, the host was still running code with the bug present, so it's not surprising they crashed. It sounds pretty much like the bug that was fixed since it can't seem to happen again.

**Comment by kulzae** [comment] 2021-09-09 15:10
[DESKTOP-V0IT2TC_-_2021.9.8.1291_-_2021-09-08_18_46_29.log](https://github.com/Neos-Metaverse/NeosPublic/files/7137694/DESKTOP-V0IT2TC_-_2021.9.8.1291_-_2021-09-08_18_46_29.log)
[RENEGADE - 2021.9.8.1291 - 2021-09-08 22_57_10.log](https://github.com/Neos-Metaverse/NeosPublic/files/7137697/RENEGADE.-.2021.9.8.1291.-.2021-09-08.22_57_10.log)

attached are the log files from the host and from my comp. crash occurs around 8:07PM on the host

**Comment by Frooxius** [comment] 2021-09-09 16:09
Thanks! Looks like it's actually completely unrelated to the ChildParentAudioClipPlayer, but I was able to fix the issue.

**Comment by kulzae** [comment] 2021-09-09 16:11
welp i figured it was something due to that as the only thing that changed was using those components but glad you figured it out anyways

**Comment by Frooxius** [comment] 2021-09-09 19:12
Fixed in 2021.9.9.1144! Thanks for the logs!

**Closed by Frooxius** 2021-09-09 19:12 UTC
Labels: Bug, Needs More Information
