### ISSUE TITLE
Make Tooltip Scale Adjustable

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2726] opened 2021-07-31 15:53 UTC
### Is your tweak request related to a problem? Please describe.

I'm always frustrated when I equip a tool. This is because Neos's auto-detection for tooltip scale decided that they should be massive on my avatar.

### Describe what would you like tweaked

Give us an option to override/change whatever scale Neos auto-detects for tooltips on an avatar.

### Describe alternatives you've considered

1. Scaling the tool. This doesn't work because the tool will then be too small or too big for other avatars,
2. Scale the tool's grip pose. Same problem as above.
3. Scale the avatar's tooltip anchors. This has no effect on the tooltip's scale.
4. Add an invisible index finger to the avatar and scale that since that seems to be what the default tooltip scale is based on. (not an option for obvious reasons)
5. Drive the tool's scale with logix after it is equipped. (Also undesirable.)
6. Do nothing about this. (My current solution; Does not fix the issue.)

### Additional context

So far I know that myself, Goodvibes, Gourry, EpicEaston and Jeana have run into this as a problem.

**Comment by shadowpanther** [comment] 2021-07-31 15:57
Related: #746

**Comment by ukilop** [comment] 2021-07-31 18:30
Afaik scale is based on finger bones distance from the wrist bone.
On My avatar, tools are very small as my “hands” are tiny and hidden

**Comment by Frooxius** [comment] 2021-07-31 19:55
This is duplicate of #746, closing this one.

**Closed by Frooxius** 2021-07-31 19:55 UTC
Labels: Duplicate, Tools, Tweak
