### ISSUE TITLE
Option to clear LogixReference components with null RefNode

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2066] opened 2021-04-21 13:33 UTC
## Is your tweak request related to a problem? Please describe.
I have a slot with 500-1000 LogixReference components that don't lead anywhere anymore. (RefNode is null).

## Describe what would you like tweaked
Either an option to clear them all (maybe somewhere in the optimization wizard thingies) or have Neos remove those automatically when saving or spawning the item / when the RefNode field goes to null.

## Describe alternatives you've considered
Writing a plugin or Logix setup to do this automatically or manually deleting over 500 components, both sounding like more of a hassle than they have to be.

**Comment by shiftyscales** [comment] 2021-04-21 15:52
This is a duplicate of #1491.

> Sorry this won't happen as official implementation. As a rule I'm not adding ad hoc "fixes" for bugs like this. Like ProblablePrime mentioned, the proper approach is to redesign the mechanism, which is planned along the way to address a multitude of other problems as well.

Apologies for the inconveniences.

**Closed by shiftyscales** 2021-04-21 15:52 UTC
Labels: Duplicate, Tweak, Won't Fix/Implement

**Comment by Psychpsyo** [comment] 2021-04-21 16:09
While that will probably not change the final verdict here, I'd say that this is not a duplicate of #1491 as that issue is about an entirely different component with different behavior.
Neos does already attempt to clean up LogixReference components. (It removes them when the RefArrow is destroyed, for example)
The same can't be said about LogixInterfaceProxy components.
