### ISSUE TITLE
Mesh collider can't get on collision start 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#3278] opened 2021-10-30 20:05 UTC
### Describe the bug?

Zyzyl said it worked for him before but I need this so it broke because now it doesn't work 

### Relevant issues

Colliders

### To Reproduce

Mesh collider and then try to get a on collision start out of it nothing happens

### Expected behavior

It doing the pulse 

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Latest

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

Zyzyl said it worked before 

### Reporters

Zyzyl and me

**Comment by Frooxius** [comment] 2021-10-30 20:10
We'll need proper replication steps of what you're doing, this is unfortunately too vague.

**Comment by Zyzyl** [comment] 2021-10-30 20:15
I thought I remembered it working in the past. I'll have a look through available documentation etc tomorrow and, if it does indeed look like a bug, I'll sort out a repro

**Comment by alexderpyfox** [comment] 2021-10-30 20:30
Replication is step 0 go in walk run locomotion step 1 spawn object step 2 get logic node that says on comission start step 3 plug mesh collider in on collision start step 4 cycle through all possible collider settings of the mesh collider to try to get one to pulse when you touch it step 5 none of them pulse at all step 6 try all of the collider settings it with character collider on

**Comment by alexderpyfox** [comment] 2021-10-30 20:31
It does work with box collider and convex hull but they aren't suitable for what I'm making

**Comment by Zyzyl** [comment] 2021-10-31 06:22
For context, Alex was trying to get an impulse from the On Collision Start node when a user collided with a MeshCollider

I'm going to close this one because:
1) The documenation on the wiki https://wiki.neos.com/Collider says that MeshColliders should not be usable for this
2) This comment from ProbablePrime https://discord.com/channels/402159838827905024/439422161657135106/904107585727266836 suggests that things are working as intended
3) It seems Alex solved their problem with some help.

If you still believe this is a problem Alex you can still comment on here.

**Closed by Zyzyl** 2021-10-31 06:22 UTC
Labels: Bug, Needs More Information
