### ISSUE TITLE
While in F8 Desktop Mode, the "Save As" world orb menu appears according to the headset position

### ISSUE THREAD

**Issue by ProbablePrime** [Neos-Metaverse/NeosPublic#3762] opened 2022-09-26 08:01 UTC
### Describe the bug?

When in VR, and you hit "Save As" an orb appears in front of you allowing you to select: Save Here, Save To Invetory.
When in ScreenMode(NOT F8) this orb also appears nicely.

When switched into Desktop via VR(F8), The orb appears in a position suitable for VR and freezes your view making it almost impossible to save a world in this state.

### Relevant issues

I'm almost certain I've seen this reported before but couldn't find it due to overloaded terms(save, world) returning so many results sowwi!

### To Reproduce

1. Run Neos in VR Mode
2. Open a world
3. Switch to Desktop using F8
4. Rotate 180 degrees or larger away from your original VR view
5. Try to use "save as" to save a world

### Expected behavior

The save world option/orb should be usable at all times.

### Log Files

N/A

### Screenshots

N/A

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Latest

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

SHFR

**Comment by LexiBasilisk** [comment] 2022-09-26 18:31
This is a duplicate of #2006. Closing and redirecting to that issue.

**Closed as completed by LexiBasilisk** 2022-09-26 18:31 UTC
Labels: Bug, Duplicate

**Comment by ProbablePrime** [comment] 2022-09-27 00:12
Thanks Shifty!
