### ISSUE TITLE
Hidden World "Ask to join" option in display name

### ISSUE THREAD

**Issue by komdog** [Neos-Metaverse/NeosPublic#2280] opened 2021-05-18 00:39 UTC
## Is your feature request related to a problem? Please describe.
Very often users won't bother asking to join hidden worlds since all they can see is `Hidden` or `Hidden, Contacts +`, causing them to become discouraged. To combat this, some users will name _non-hidden_ worlds **"Ask to join"**, as they want to limit who can enter the world without discouraging people from asking. However, this can often lead to people joining without asking.

By adding an `Ask To Join` status **OR** giving users the ability to display the name of the world, they can keep their worlds hidden and ensure that people will be more comfortable requesting an invite from them without feeling like they're intruding.

Here are examples of how the status would look
![github_name_suggestion](https://user-images.githubusercontent.com/42328288/118570563-6aab3480-b74a-11eb-9423-5288f8f24a11.png)

## Relevant issues
https://github.com/Neos-Metaverse/NeosPublic/issues/1084 (Though this seems to be requesting an entire system)

## Describe the solution you'd like
A checkbox in the sessions menu that will add `Ask To Join` by the world status
**- OR -**
A checkbox in the sessions menu that will allow the name to be displayed in others' contact lists. 

## Describe alternatives you've considered
As stated above, making a public world with "Ask to join" in the title could work, but it's often the case users would **want** this world to be private and not show up on the session list.

## Additional context
This would probably only need to be added for Public `Hidden` and Contacts + `Hidden`, as people in contacts only or above would probably not want users requesting to join.

Otherwise the `Ask To Join` status would have to be removed for those that are not contacts with the host of the world.

**Comment by 3x1t-5tyl3** [comment] 2021-05-18 00:42
#1084 DUPLICATE

**Comment by 3x1t-5tyl3** [comment] 2021-05-18 00:46
This is a direct duplicate of #1084 . The conversation should probably be merged into that one as to not create literal duplicate GH issues which can be confusing for everyone.

**Comment by komdog** [comment] 2021-05-18 00:53
> This is a direct duplicate of #1084 . The conversation should probably be merged into that one as to not create literal duplicate GH issues which can be confusing for everyone.

The referenced issue doesn't follow the Neos Feature Request format. Furthermore, it doesn't consider the existence of Hidden Worlds and the social issues surrounding them considering it was made in 2020, Which is confusing in it's own right.

I'm also not asking for the implementation of a request to join feature.

**Comment by 3x1t-5tyl3** [comment] 2021-05-18 00:56
Seems rater hacky to just inject a string. Which is not great. Ontop of a potential rework of the contacts list already a thing that is a thing for the closer future. While I do agree that the other GH issue has problems; Creating a new one instead of cleaning up the old seems rather unnecessary to me in more than one way and removes alot of potentially important conversation on the matter.

**Comment by komdog** [comment] 2021-05-18 01:24
How about this then:

1. Addition of a boolean, `CurrentSessionAsk` for example, which would be togglable in the sessions menu
2. Addition of locale text for the status `"Contacts.InHiddenAsk"` and `"Contacts.InHiddenFriendsOfFriendsAsk"`
3. Addition `if (friend.UserStatus.CurrentSessionAsk) {}` conditional to change apply the change

That's would solve the "Hacky" nature of just injecting a string.

**Comment by shiftyscales** [comment] 2021-05-18 01:47
A generalized 'request invite' system seems like it would take care of the needs of the issue (and is something that has previously been discussed as a possibility). It wouldn't need to apply to one specific session visibility, and would also implicitly take care of the 'asking' in a single step.

If a user is capable of sending an invite, you could send them an invite request, and if accepted, you'd be connected to the session. (Potentially requiring another confirmation on the part of the user getting added to the session so they aren't pulled away at an inconvenient time.)

This is something that would make much more sense to be dealt with when the contacts UI is reworked/when the notification system is developed (both are separate additions/features.)

Also worth noting- this seems more like a social issue than a technical one. E.g. while hidden, if the session is set to Anyone and Don't show in session lists, it will read as just 'Hidden World', compared to the others, e.g. Hidden, Contacts Only, etc. If a user sees "Hidden World" or "Hidden, Contacts+ World", they should feel compelled to ask for an invite as that indicates the session's openness, even if it's hidden.

Your proposal doesn't seem like a good option to handle the issue you're experiencing.

**Closed by shiftyscales** 2021-05-18 01:47 UTC
Labels: Enhancement, Won't Fix/Implement
