### ISSUE TITLE
Headless "allowedUrlHosts" Ignored?

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#3120] opened 2021-10-01 23:48 UTC
### Describe the bug?

I've had bunch of hosts in my remote allowed list for forever on the headless as it's used for a bunch of things, but as of a few days ago (maybe a week or so) outbound requests to these hosts don't seem to work anymore. Checking with Logix seems to confirm they're not allowed despite the config explicitly allowing it:

```
"allowedUrlHosts": [ "xnode.org", "neos.xnode.org", "neocdn.xnode.org", "youtube.com", "twitch.tv", "neosvr-api.com", "www.xnode.org", "www.neos.xnode.org", "www.neocdn.xnode.org", "www.youtube.com", "www.twitch.tv", "www.neosvr-api.com" ]
```

It's trying to connect out on the standard HTTPS port so no special port specification should be required as per the recent patchnotes.

### Relevant issues

None found.

### To Reproduce

Run a Linux headless with a host explicitly allowed, try and initiate a load/connection to that host from the headless.

### Expected behavior

For the request to work as it's allowed.

### Screenshots

Here's the headless writing to the bool. You can see that I'm allowed, but despite the config above, the headless claims it's not allowed to connect out to this address.
![image](https://user-images.githubusercontent.com/958670/135696472-00e18586-2844-463f-8db4-f387897ce0be.png)

On an aside, I thought you were able to specify hosts without a protocol at the beginning in the past, but doing so now causes the Logix to break.
![image](https://user-images.githubusercontent.com/958670/135696506-7eb58b29-0391-4e31-b825-463c9387aab7.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.12.967

### What Platforms does this occur on?

Linux

### Did this work before?

Yes

**Comment by WallTack** [comment] 2021-10-02 17:12
Possibly related to #2993

**Comment by Frooxius** [comment] 2021-10-03 11:35
Can you share a log from your headless startup please? I've tried replicating this locally, but it doesn't seem to happen on my end. It might be that for some reason the allowed hosts aren't properly setup or loaded or something else is going on.

**Comment by Enverex** [comment] 2021-10-03 11:39
I think you've just highlighted the issue. I didn't realise it echo'd the allowed list in to the log. It looks like Neos is allowing port 80 by default, but not port 443 which should be allowed by default as that's the standard SSL/HTTPS port (which almost enforced over normal HTTP at this point).

```
6:43:56 PM.815  Logging in as EnverexBot
6:43:56 PM.816  DoNotSendReadStatus set to: False
6:43:57 PM.547  Initializing SignalR
6:43:57 PM.669  Connecting to SignalR...
6:43:59 PM.268  Connected to SignalR
6:43:59 PM.287  Logged in successfully
6:43:59 PM.287  Allowing host: xnode.org, Port: 80
6:43:59 PM.288  Allowing host: neos.xnode.org, Port: 80
6:43:59 PM.288  Allowing host: neocdn.xnode.org, Port: 80
6:43:59 PM.288  Allowing host: youtube.com, Port: 80
6:43:59 PM.288  Allowing host: twitch.tv, Port: 80
6:43:59 PM.288  Allowing host: neosvr-api.com, Port: 80
6:43:59 PM.288  Allowing host: www.xnode.org, Port: 80
6:43:59 PM.288  Allowing host: www.neos.xnode.org, Port: 80
6:43:59 PM.288  Allowing host: www.neocdn.xnode.org, Port: 80
6:43:59 PM.288  Allowing host: www.youtube.com, Port: 80
6:43:59 PM.288  Allowing host: www.twitch.tv, Port: 80
6:43:59 PM.288  Allowing host: www.neosvr-api.com, Port: 80
6:43:59 PM.306  Resolving SessionID:
```

**Comment by Frooxius** [comment] 2021-10-03 11:46
That's normal. Ports 80 and 443 do not require actual port specification. If you allow port 80, you can make requests both on 80 and 443 and vice versa. That's definitely not the issue.

It's a bit odd through, it seems like they're registered, so there's likely some issue with checking or something like that. Are you able to check if the behavior happens on Windows as well? I'll have to try a Linux machine to test, it might be something with Mono.

**Comment by Enverex** [comment] 2021-10-03 12:07
Seems to work on Windows. Copied my Config.json over exactly from the Linux server to my desktop PC and ran the headless client there. Everything had loaded in correctly so all the outbound calls must have worked.

**Comment by Frooxius** [comment] 2021-10-03 13:12
I see, thanks for the info! I've tried running it under Linux Mono, but I still couldn't replicate it. I've added a new 2021.10.3.784 in the build, can you try with that one and see if the log?

**Comment by Enverex** [comment] 2021-10-03 13:30
Not seeing any output regarding the issue in the logs or any mention of connection attempts (at least nothing that references the URL or domain in question).

[log.txt](https://github.com/Neos-Metaverse/NeosPublic/files/7273408/log.txt)

Unrelated issue but I noticed that if the world/session description is null (or omitted) in the headless config, rather than leaving the description alone (which you'd expect and is what it does for the world name) it blanks it.

**Comment by Frooxius** [comment] 2021-10-03 13:32
Oh I think I looged it using wrong function sorry! Can you copy the screenshot of the window (or copy the output of the console) right after the "Allowing host:" segment? It should print out right after that.

**Comment by Enverex** [comment] 2021-10-03 13:53
Here we are:
```
DoNotSendReadStatus set to: False
Initializing SignalR
Connecting to SignalR...
Connected to SignalR
Logged in successfully
Allowing host: xnode.org, Port: 80
Allowing host: neos.xnode.org, Port: 80
Allowing host: neocdn.xnode.org, Port: 80
Allowing host: youtube.com, Port: 80
Allowing host: twitch.tv, Port: 80
Allowing host: neosvr-api.com, Port: 80
Allowing host: www.xnode.org, Port: 80
Allowing host: www.neos.xnode.org, Port: 80
Allowing host: www.neocdn.xnode.org, Port: 80
Allowing host: www.youtube.com, Port: 80
Allowing host: www.twitch.tv, Port: 80
Allowing host: www.neosvr-api.com, Port: 80
https://neos.xnode.org/ allowed: Allowed
Resolving SessionID:
```

Interestingly the host check in-world is now also reporting true (it was reporting false before, as per the original screenshot)...
![image](https://user-images.githubusercontent.com/958670/135756019-8d12ea54-7bb7-47dc-8d1b-82b0da173d09.png)

But if I try and run a GET String...
![image](https://user-images.githubusercontent.com/958670/135756538-183cfd5f-0b4f-4c26-99b7-2a02514947e5.png)
(the web server never sees this request, it doesn't appear to leave Neos)

Switching it out to a local user, shows success from my user:
![image](https://user-images.githubusercontent.com/958670/135756699-dd9e5658-2a53-403c-af94-b9b4eed95ef1.png)

**Comment by shadowpanther** [comment] 2021-10-03 14:02
Funny, it also shows it allowed on my headless, which doesn't have this host in the list
<img width="349" alt="image" src="https://user-images.githubusercontent.com/675104/135757087-4b168b50-381e-4032-9061-b2fa09a89c10.png">

**Comment by Frooxius** [comment] 2021-10-03 15:10
Oh weird. I think I might be running the check way too early perhaps. I'll try to look after I get some sleep. Sorry!

**Comment by Enverex** [comment] 2021-10-05 01:04
Any luck?

**Comment by Enverex** [comment] 2021-10-05 19:23
So testing this further, the issue specifically is that the headless can't talk to anything hosted on itself. If I have it try and connect out to a third party, that'll work, but anything that resides on the same server (i.e. the web service) will throw an "OnError" from the GET node. If a host isn't allowed in the first place, the GET node doesn't fire at all so it doesn't look like it's an allow issue. I tried having Neos connect to the server's own IP, and localhost (both numeric and hostname) all act the same way. Polling it as a user rather than the headless host still works fine. None of these requests ever hit the web server.

Unfortunately the only output from the GET node on failure is the response code "0".

The server has no issues connecting to itself under normal circumstances, it can CURL, WGET and in whatever other way interact with itself.

**Comment by Enverex** [comment] 2021-10-05 19:57
Additionally https://neocdn.xnode.org (which ISN'T hosted on the same server) doesn't work, but http://neocdn.xnode.org does, but both of these work fine in a browser and via anything else (it's a CDN for the main server).

**Comment by Enverex** [comment] 2021-10-07 02:22
So I tried to recreate this issue on someone else's server that also ran a webserver and couldn't recreate the issue.

Would it be possible to add some logging for when the GET Request throws an error with what the error actually is? The return code is "0" and... that's it, so there's no information from Neos with regards to what's failing, in any way. The request doesn't reach the web service so there's no logging to look at on that side.
![image](https://user-images.githubusercontent.com/958670/136310013-42ad85c7-755c-4a14-aa8b-e205aa22b7cc.png)

**Comment by Enverex** [comment] 2021-10-08 15:39
I've narrowed this down further. It's specific to HTTPS. HTTP queries still work. I also tried deploying Nginx alongside Apache and the issue persisted there. HTTP GET requests from Neos worked fine, HTTPS immediately failed. I even tried non-standard ports (using the same port each time - 81) and configuring that port showed the same behaviour - worked as HTTP, Neos failed with HTTPS.

So my recreation list so far is as follows:
Linux.
Web server running on same machine as Neos headless.
Neos headless making HTTPS call to local web server.

I'm using a FQDN for the calls but I'm not sure that's relevant (but somewhat important as it's needed for the SSL/HTTPS part to work).

**Comment by Bontebok** [comment] 2021-12-22 06:31
I believe this a problem with either the Let's Encrypt certificate or a problem with handling if TLS/cyphers within Mono. I'm investigating the exact same issue and I found that your server and mine were both signed by the same chain and Root CA. I don't know much about Mono, but I did check the certmgr command and it does appear that the ISRG Root X1 cert appears to be in the trust list for Mono.

If you capture packets or look at your https server, you may see the attempts to negotiate TLS but it seems like Neos just gives up and never sends any data. This is typically due to a cert or a TLS issue.

I'm going to keep digging but I don't know much about Mono but I'm leaning towards the problem being with the certificate store or possibly in the TLS libraries.

**Comment by Bontebok** [comment] 2021-12-22 08:01
Got it!

The issue is stemming from an expired Let's Encrypt certificate that is interfering with the newer Let's Encrypt X1 certificate. To resolve this, you need to blacklist the expired certificate from your system or docker image. 

Before doing so, run this command from your (docker) shell.

`csharp -e 'new System.Net.WebClient ().DownloadString ("https://neocdn.xnode.org/")'`

Look for the following error:

```
System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
<Stack Trace Clipped>
```

Then, blacklist this certificate with the following command:

`sed -i 's#mozilla/DST_Root_CA_X3.crt#!mozilla/DST_Root_CA_X3.crt#' /etc/ca-certificates.conf && update-ca-certificates`

You can now re-run the csharp command above and you will now see an error 403 (which is correct in the case of your URL).

To make this permanent in your docker image. Add the following line to your dockerfile somewhere prior to your user switching so it runs as root.

```
# Blacklist the DST_Root_CA_X3 cert to fix Let's Encrypt X1
RUN     sed -i 's#mozilla/DST_Root_CA_X3.crt#!mozilla/DST_Root_CA_X3.crt#' /etc/ca-certificates.conf && update-ca-certificates
```

I will share this with @shadowpanther as I use their docker image and this would be helpful to add for others who are facing this problem. Please let me know if this resolves your issue. Thanks!

**Comment by Enverex** [comment] 2021-12-22 09:19
Thanks for tracking that down, it cost me days of my life but unfortunately due to my lack of familiarity with C#/Mono, I hit a wall identifying the cause other than "both ends abruptly stop talking to each other".

Looks like there's been a bug open on Mono's side since 1st of October but it's unresolved:
https://github.com/mono/mono/issues/21233 - "The bottom of the issue is that Mono uses an old fork of BoringSSL, which is a fork of OpenSSL 1.0 and includes a broken chain validator that isn't even used by Chrome/Chromium (who are the creators/maintainers of BoringSSL)."

**Comment by Enverex** [comment] 2021-12-22 15:17
Ok, this was far more fiddly on Arch which doesn't seem to have the same mechanism for removing certificates. In this case the only way to stop Mono using the old CA certificate was to remove it from Mono's own certificate store, specifically the file `/usr/share/.mono/new-certs/Trust/2e5ac55d.0`.

**Comment by Bontebok** [comment] 2021-12-22 18:08
Sorry that took so long but glad that you reported it here so that others who may have trouble with their headless clients exchanging data with a host using Let's Encrypt certificate can find the solution.

For now, I will close this issue as this is not a bug pertaining to Neos but of to Mono itself on the handling of expired certificates.

**Comment by Enverex** [comment] 2021-12-22 18:12
This does highlight a lack of feedback or debugging from Neos though, after seeing the error from Mono, it was pretty obvious, but Neos was failing silently which made this almost impossible to track down.

**Closed** 2021-12-22 18:11 UTC
Labels: Not a Bug, Headless/Server System

**Comment by shadowpanther** [comment] 2022-01-29 15:58
@Bontebok added the `sed` line to the Dockerfile, the :latest image should currently contain the fix.
