### ISSUE TITLE
Neos freezes every other second if a vertical monitor is connected

### ISSUE THREAD

**Issue by butterbutts** [Neos-Metaverse/NeosPublic#3678] opened 2022-05-20 20:50 UTC
### Describe the bug?

In both VR and desktop mode, if there is a vertical monitor connected, Neos will freeze for a second every two seconds consistently the entire time the game is running. Disconnecting the vertical monitor and restarting the game fixes the issue until you turn the monitor back on.

### Relevant issues

N/A

### To Reproduce

Start the game with a vertical monitor connected.

### Expected behavior

The game should not stutter/freeze.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### Additional context

Someone else reported the same problem on reddit: https://www.reddit.com/r/NeosVR/comments/s8sx6w/neos_vr_hangs_exactly_every_second/
Windows 11 Pro x64
AMD Ryzen 5600X
Nvidia RTX 3070 Ti

**Comment by LexiBasilisk** [comment] 2022-07-30 13:38
Just noticed this is a duplicate of #2813 - thanks for the report.

**Closed as completed by LexiBasilisk** 2022-07-30 13:38 UTC
Labels: Bug, Duplicate
