### ISSUE TITLE
Asset variants for textures cause exceptions, and result in textures not loading.

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#3619] opened 2022-02-22 10:57 UTC
### Describe the bug?

Yesterday I updated some textures on my avatar - today, these textures no longer load, and result in exceptions in the log.

This seems to only affect variants which use both MaxSize and Compression - removing the MaxSize, or switching to RawRGBA results in the texture loading normally.

Restarting neos, and clearing my cache did not resolve the issue.

```
5:26:28 AM.426 (105 FPS)	Starting GatherJob for neosdb:///9dbc06a3ba56bba79b0fe6840d0bcd52c887850e269b5832071e342ccc529ca9?version=2&compression=BC3_LZMA&quality=100&width=1024&height=1024&mips=False&filtering=Box&legacyHDR=False, AttemptsLeft: 5
5:26:28 AM.448 (105 FPS)	Finished Gather for: neosdb:///9dbc06a3ba56bba79b0fe6840d0bcd52c887850e269b5832071e342ccc529ca9?version=2&compression=BC3_LZMA&quality=100&width=1024&height=1024&mips=False&filtering=Box&legacyHDR=False. Elapsed: 0.0220035 s
5:26:28 AM.456 (105 FPS)	Exception decoding texture asset: C:/Users/Epsilion/AppData/Local/Temp/Solirax/NeosVR\Cache\vby1o6ht2li87evt
Variant: Type: Texture2D, FilterMode: Anisotropic, Aniso: 8, WrapU: Clamp, WrapV: Clamp, WrapW: Repeat, MipMapBias: 0, Readable: False, Exact: True, Compression: BC3_LZMA, Quality: 100, Width: 2048, Height: 2048, Mipmaps: True, Filtering: Box
VariantIdenfifier: version=2&compression=BC3_LZMA&quality=100&width=1024&height=1024&mips=False&filtering=Box&legacyHDR=False
System.IO.InvalidDataException: Version is too new: 1
  at CodeX.Bitmap2D.LoadRaw (System.IO.Stream stream) [0x00044] in <9305dcafe5b3481fab676401a77501cd>:0 
  at CodeX.Bitmap2D.LoadRaw (System.String file) [0x00007] in <9305dcafe5b3481fab676401a77501cd>:0 
  at FrooxEngine.Texture2D.DecodeFile (System.String file, FrooxEngine.Texture2DVariantDescriptor descriptor, System.Boolean forceMips) [0x000a3] in <a6ff441fca7c4a97bc5b9dca720b524b>:0 
  at FrooxEngine.Texture`5+<LoadTargetVariant>d__37[E,D,C,M,B].MoveNext () [0x005c5] in <a6ff441fca7c4a97bc5b9dca720b524b>:0 

   at void BaseX.UniLog.Error(string message, bool stackTrace)
   at async void FrooxEngine.Texture<FrooxEngine.Texture2DVariantDescriptor, CodeX.Texture2DVariantDescriptor, FrooxEngine.ITexture2DConnector, CodeX.BitmapMetadata, CodeX.Bitmap2D>+<LoadTargetVariant>d__37.MoveNext()
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(object stateMachine)
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at void BaseX.WorkProcessor.ProcessQueue(ThreadWorker worker, ConcurrentQueue<Action> queue)
   at void BaseX.WorkProcessor.JobWorker(ThreadWorker worker)
   at BaseX.WorkProcessor+ThreadWorker(WorkProcessor processor, Worker worker, WorkType targetWorkType, ThreadPriority priority, int index)+() => { }
   at void System.Threading.ThreadHelper.ThreadStart_Context(object state)
   at void System.Threading.ThreadHelper.ThreadStart()
5:26:28 AM.460 (105 FPS)	Error decoding texture variant: Type: Texture2D, FilterMode: Anisotropic, Aniso: 8, WrapU: Clamp, WrapV: Clamp, WrapW: Repeat, MipMapBias: 0, Readable: False, Exact: True, Compression: BC3_LZMA, Quality: 100, Width: 2048, Height: 2048, Mipmaps: True, Filtering: Box, File: C:/Users/Epsilion/AppData/Local/Temp/Solirax/NeosVR\Cache\vby1o6ht2li87evt, URL: neosdb:///9dbc06a3ba56bba79b0fe6840d0bcd52c887850e269b5832071e342ccc529ca9
```

### Relevant issues

N/A

### To Reproduce

This seems to only affect textures that I uploaded yesterday, and only when loading a compressed variant with a MaxSize constraint. RGBA32 loads fine.

### Expected behavior

1. Compressed variants should load properly
2. Variants which fail to load should fall back on a functional variant.

### Log Files

[DESKTOP-M6LBCPT - 2022.1.28.1310 - 2022-02-22 03_45_05.log](https://github.com/Neos-Metaverse/NeosPublic/files/8115838/DESKTOP-M6LBCPT.-.2022.1.28.1310.-.2022-02-22.03_45_05.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1310

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### Reporters

Epsilion

**Comment by shadowpanther** [comment] 2022-02-22 14:01
This is a duplicate of #3388

**Closed** 2022-02-22 14:07 UTC
Labels: Bug
