### ISSUE TITLE
Opening a new world you don't own, by default, should open the "Start Custom Session"

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2827] opened 2021-08-20 04:23 UTC
### Is your tweak request related to a problem? Please describe.

If a user wants to start a new session, who doesn't fully understand how our world browser works. Clicking "Start Session" starts a public session by default. I think when you click Start Session, it should open (1) the Custom Sessions window instead. It would be super useful as when you want to open a <i>Not public</i> world.. you have to go through 3 more windows to do that, but if it prompted you by default, you wouldn't have to worry about that and you can customize every session without needing to go through those three screens.

### Describe what would you like tweaked

I would like "Start Session" to open up the custom session tab, instead of needing to visit 3 windows to do the same task. It only adds a second button press if you don't want to change anything and open the world as public.

(Technically can be treated as a confirmation you want to open the world) which I guess will be nice since I personally have opened worlds on accident.) but at the same time, lessons how many windows you need to go to if you want to open a new world to be contacts+ hidden.

#2779 would also be nice
#1216 sounds like something similar too my request <i>(Sorry if it's considered to be a duplicate)</i>

### Describe alternatives you've considered

Continue needing to visit 3 windows to start a custom session of a world you don't own. I'm open for conversations & ideas.

### Additional context

(1)
![image](https://user-images.githubusercontent.com/53165730/130176911-319914c1-934b-4113-abd6-a85c3901d12f.png)

**Comment by H3BO3** [comment] 2021-08-20 04:28
I think #1216 would cover this if the only concern is World Access Level, since that's specifically what the issue addresses

**Comment by AshtonSparx** [comment] 2021-08-20 04:32
My issue also references the Hide From Public Listing so it could technically merge the two into this

**Comment by H3BO3** [comment] 2021-08-20 04:33
Maybe as an optional checkbox, and then clicking one of the access level buttons starts the session.

**Comment by shadowpanther** [comment] 2021-08-20 13:31
Maybe on the small first popup take a bit of the big Start Session button and add a `...` button for extended session options that opens this same popup? This is a widely used convention to provide extended options of the same general action.

**Comment by AshtonSparx** [comment] 2021-08-20 21:58
> 
> 
> Maybe on the small first popup take a bit of the big `Start Session` button and add a `...` button for extended session options that opens this same popup? This is a widely used convention to provide extended options of the same general action.
> 

That sounds great! It would still reduce the amount of windows you have to go through. while also keeping old functionality of the original button

**Comment by Frooxius** [comment] 2021-08-21 13:11
This is technically duplicate of https://github.com/Neos-Metaverse/NeosPublic/issues/1216, it's pretty much the same problem. I suggest closing one of the issues so we don't split the discussion over multiple ones.

**Closed** 2021-08-22 01:19 UTC
Labels: Tweak, Worlds, UI
