### ISSUE TITLE
Please consider adding my logix nodes for handling JSON strings

### ISSUE THREAD

**Issue by zogtrog** [Neos-Metaverse/NeosPublic#2129] opened 2021-05-01 14:55 UTC
I have created a set of Logix nodes for converting JSON to Logix values and vice versa.
I would be very grateful if they could be incorporated into NEOS / or the sample Library as this would allow JSON 
object data to be prepared to send to web services or decoded when received, which I would find extremely useful.
There are also a couple of nodes in there for interacting with Mongo.db you might want to keep or omit, or 
move to a separate project

Please see my sample library 

https://github.com/zogtrog/NeosSampleLibrary/tree/zogtrog-JINT4NEOS

**Comment by LeDrascol** [comment] 2021-05-01 14:57
This is a duplicate of #221

**Comment by zogtrog** [comment] 2021-05-01 14:59
Yes but I have written the code for the nodes - it just needs incorporating is it's deemed good enough,

**Comment by zogtrog** [comment] 2021-05-01 15:01
I will post it under #221

**Comment by 3x1t-5tyl3** [comment] 2021-05-01 15:01
> 
> 
> This is a duplicate of #221

This is not a duplicate. Zogtrog in this case supplied a piece of code himself as consideration. Rather than saying that he wanted it at all.

**Comment by Frooxius** [comment] 2021-05-01 15:02
I'm sorry, but we are currently not including any 3rd party code/libraries like this into official Neos distribution. All code that goes into official codebase needs to be designed with several goals in mind, including long term maintainability, content compatibility and security, because it cannot be easily changed once it's introduced and content is built upon it.

We have an official implementation planned here: https://github.com/Neos-Metaverse/NeosPublic/issues/221 that will build such system on other general per-requisites (e.g. Collections) to ensure above goals are met.

**Closed by Frooxius** 2021-05-01 15:02 UTC
Labels: Enhancement

**Comment by zogtrog** [comment] 2021-05-01 15:08
I understand, I just wanted to help.
