### ISSUE TITLE
LocalAudioDeviceStream is downmixed

### ISSUE THREAD

**Issue by troyBORG** [Neos-Metaverse/NeosPublic#3898] opened 2023-05-15 05:36 UTC
### Is your tweak request related to a problem? Please describe.

Audio for this is downmixed to mono, would like Independent channel control

### Describe what would you like tweaked

I would like to have to ability with this to choose either left, or right audio channels,

### Describe alternatives you've considered

I tried moving a slot near my left and right ears thinking it might give me different values

### Additional context

I'm using this to detect when people talk and using the volume to drive a gradient driver to make my ears perk up when I hear people talk near me.

**Comment by LexiBasilisk** [comment] 2023-05-20 15:25
This is a duplicate of #421.

**Closed as completed by LexiBasilisk** 2023-05-20 15:25 UTC
Labels: Duplicate, Tweak
