### ISSUE TITLE
</closeall> RTF Tag not properly closing tags in World Names

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#3089] opened 2021-09-26 11:23 UTC
### Describe the bug?

When naming a world (for example my homeworld)
`<color=#666>THE QORE</color>` works fine but using `<color=#666>THE QORE</closeall>` closes the RTF Tag and adds a </b> at the end.

### Relevant issues

#3061

### To Reproduce

Name a world with a </closeall>

### Expected behavior

For it to properly close the tags.

### Screenshots

![grafik](https://user-images.githubusercontent.com/61988002/134805576-f01ec42d-3395-417d-96dc-3d85f6733cf8.png)
![2021-09-26 13 17 50](https://user-images.githubusercontent.com/61988002/134805604-ee04b5c0-408a-4622-9dd5-21afec04438b.jpg)
![2021-09-26 13 17 48](https://user-images.githubusercontent.com/61988002/134805606-402ca0ab-7b09-43db-824c-eca6095780bd.jpg)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.9.22.1431

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

`Sox#0001` `3x1t_5tyl3#0001`

**Comment by Frooxius** [comment] 2021-09-27 07:08
This is actually not a bug, the </closeall> is working as it should - it closes all tags, including the initial <b> that's injected into the name, so the last </b> ends up printed out as a result, since you've already closed it yourself.

We can add some things to deal with this though, probably some kind of "Closeall block" that will present a barrier for the </closeall> tag.

**Comment by 3x1t-5tyl3** [comment] 2021-09-27 15:41
Oh! I didn't look at it that way. That makes sense. I think a proper blocking feature for it is nice to have, at-least internally. I assume some future UI could suffer from a similar issue and could definitely benefit from this.

**Comment by AshtonSparx** [comment] 2021-09-27 18:00
My quick fix for people being knobs and not closing their tags properly is stripping them from their world names #2801 instead of trying to fix it for them externally

**Comment by Frooxius** [comment] 2021-09-28 14:37
Added <closeallblock> tag in 2021.9.28.865 that you can use. However I haven't added it to the Contacts UI since it's going to be reworked anyway and it's not worth the effort to chase down all the places in the code where it's updated now. If you find any new UI parts where this is an issue, let me know and I can update those.

**Closed by Frooxius** 2021-09-28 14:37 UTC
Labels: Tweak, Not a Bug
