### ISSUE TITLE
Headless client world crash on CommonToolPermissions failure

### ISSUE THREAD

**Issue by bredo228** [Neos-Metaverse/NeosPublic#3651] opened 2022-04-19 07:53 UTC
### Describe the bug?

When a user in a headless with non-builder permissions grabs a builder holding a tool, the resulting validation element causes a full world crash.

### Relevant issues

n/a

### To Reproduce

Have a builder hold a tooltip with a grabbable avatar, then get a user set to guest to grab the builder.

### Expected behavior

World not to crash

### Log Files

Crash occurs on line 736

[8eb987b2-4126-4342-a31a-5da50c2b647d - 2022.1.28.1335 - 2022-04-19 03_36_28.log](https://github.com/Neos-Metaverse/NeosPublic/files/8510954/8eb987b2-4126-4342-a31a-5da50c2b647d.-.2022.1.28.1335.-.2022-04-19.03_36_28.log)

### Screenshots

https://user-images.githubusercontent.com/29470709/163953105-4a364ea8-baa8-4bf0-8f51-abd42e8332ab.mp4

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Headless Client Beta 2022.1.28.1335 (Linux)

### What Platforms does this occur on?

Linux

### Did this work before?

I Don't Know

### Reporters

bredo, BigRedWolfy

**Comment by shadowpanther** [comment] 2022-04-19 07:57
Duplicate of #1693

**Closed** 2022-04-19 08:00 UTC
Labels: Bug, Duplicate, Headless/Server System
