### ISSUE TITLE
LogiXTip Projection mode - Leniency

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2203] opened 2021-05-08 18:36 UTC
## Is your tweak request related to a problem? Please describe.
So currently using the logixtip with the projection mode I tend to miss a node's point in the last millisecond when pointing at it. Causing huge frustrations. This goes for both desktop *and* VR.

## Describe what would you like tweaked
I'd like it to have some form of leniency with the snapping behaviour to not "miss" the target at the last second of letting go.

## Describe alternatives you've considered
Code my own collider based solution.

## Additional context
There's plenty of times (VR or desktop doesn't matter here as I like using the projection mode for VR aswell.. cause I'm lazy and who doesn't like longrange logix?) where I miss the target due to what I assume is microjitter in my controllers or my mouse (even with me being at a very low 400dpi setting) which causes the laser to overshoot and miss entirely.

**Comment by ukilop** [comment] 2021-05-08 19:05
On top of this, the temp wires that are stretched to the logix tip have colliders, and can block the connection sometimes.

**Comment by Frooxius** [comment] 2021-05-09 00:57
The LogiX tip already has a form of leniency for connecting, it checks colliders within a radius around the tool. It sounds like something weird might be going on. Canyou provide me more information on when this happens? What conditions and such? Possibly record a video?

@ukilop What are you basing that on? The tip checks and ignores colliders that aren't relevant to its interaction, so those wires really shouldn't matter.

**Comment by H3BO3** [comment] 2021-05-09 01:03
![20210508190205_1](https://user-images.githubusercontent.com/62123804/117557431-0db7cc00-b030-11eb-95c7-452b6050c082.jpg)

**Comment by H3BO3** [comment] 2021-05-09 01:04
![20210508190358_1](https://user-images.githubusercontent.com/62123804/117557447-34760280-b030-11eb-9521-5b44bdd99caa.jpg)

Cannot grab when laser hit point is not close

**Comment by Frooxius** [comment] 2021-05-09 01:19
Those seem like expected behavior, you're not really getting close and you're blocking the laser fully with a ribbon by pointing through it, without pointing at something else. The original issue talks about missing the node point at "last millisecond", but neither of those seem to be relevant to that, but rather intentionally blocking it.

**Comment by H3BO3** [comment] 2021-05-09 01:24
![2021-05-08 19 24 00](https://user-images.githubusercontent.com/62123804/117557693-f9290300-b032-11eb-8de5-9798dd3b86a9.jpg)

**Comment by H3BO3** [comment] 2021-05-09 01:28
Maybe the TempWire should just have no collider?

**Comment by Frooxius** [comment] 2021-05-09 01:29
That still seems to be expected behavior still, you're intentionally blocking it, rather than "missing last millisecond". We can remove the collider, but I don't know if that'd be causing the issue described in the original post.

**Comment by H3BO3** [comment] 2021-05-09 01:32
![20210508193142_1](https://user-images.githubusercontent.com/62123804/117557795-10b4bb80-b034-11eb-979c-a319f315bbf3.jpg)

The initial issue happens when the trigger is released while the cursor is on the ribbon and not the node or connectpoint.

**Comment by H3BO3** [comment] 2021-05-09 01:33
![20210508193311_1](https://user-images.githubusercontent.com/62123804/117557819-3fcb2d00-b034-11eb-856a-5627365196eb.jpg)

Result of letting go in that position

**Comment by H3BO3** [comment] 2021-05-09 01:35
@Frooxius It is extremely reproducible and consistent

**Comment by H3BO3** [comment] 2021-05-09 01:40
Uploading 2021-05-08 19-37-35-1.mp4…

**Comment by H3BO3** [comment] 2021-05-09 01:40
https://user-images.githubusercontent.com/62123804/117557907-3e4e3480-b035-11eb-880c-51f5603c8e09.mp4

**Comment by 3x1t-5tyl3** [comment] 2021-05-10 10:59
Here's me and marsmaantje, he disables the collider as I hold it and when I try to connect the leniency towards the right of the display node is good but not to the left of the display node.
https://user-images.githubusercontent.com/61988002/117648929-25599680-b18f-11eb-80a7-934f915b40de.mp4

**Comment by Frooxius** [comment] 2021-05-25 20:37
I removed the collider in 2021.5.25.1225, hopefully that helps. Will still have to look into other things.

**Comment by shiftyscales** [comment] 2021-07-18 19:43
As far as I've seen this issue is fixed by the tweak made by Frooxius. There is still no means to connect a wire to a node unless the laser is on the canvas of the node- but as far as I've seen it is now consistent in always connecting when it appears connected, and vice versa.

**Closed by shiftyscales** 2021-07-18 19:43 UTC
Labels: Needs More Information, Tweak
