### ISSUE TITLE
Unable to delete group cloud variables

### ISSUE THREAD

**Issue by OfficialR3ido101** [Neos-Metaverse/NeosPublic#3680] opened 2022-05-27 11:32 UTC
### Describe the bug?

When trying to delete a created group cloud variable it does not delete it just returns an error even known the cloud var is written correctly.

### Relevant issues

#3280

### To Reproduce

Create a group cloud variable and then try to delete it.

### Expected behavior

To delete the cloud varible.

### Screenshots

![creating group var](https://user-images.githubusercontent.com/39566484/170690810-c2b359aa-a59f-413b-bf97-45af83cfcfd3.png)
![20220527212042_1](https://user-images.githubusercontent.com/39566484/170691039-564011f8-33c5-4b6d-b9f1-13e6ae115110.jpg)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

R3ido101#4995
Red Wolf#6715

**Comment by ProbablePrime** [comment] 2022-05-27 18:20
This is unfortunately a duplicate of #3280 so I will be closing.

**Closed as not planned by ProbablePrime** 2022-05-27 18:20 UTC
Labels: Bug, Duplicate
