### ISSUE TITLE
better gesture implementation

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3769] opened 2022-10-11 11:09 UTC
### Is your feature request related to a problem? Please describe.

I have seen countless gesture systems in Neos and all of them are good in their own right but none of them are perfect I would like to see a proper gesture component that will just get the basic gestures like rock and roll, finger point, thumbs up, fist, hand open, peace, ECT 

### Relevant issues

none that I can think of

### Describe the solution you'd like

I would like to have a component that would get the basic gestures of someone's controller like rock and roll, finger point, thumbs up, fist, hand open, peace, ECT 

### Describe alternatives you've considered

doing a really complicated Logics based solution which has been criticized for being really complicated and overwhelming for new users

### Additional context

adding this in would make it way more accessible for new users to make emotes a series of bool values would be fine for every gesture

**Comment by ProbablePrime** [comment] 2022-10-11 11:22
This is a duplicate of: #1980 and will therefore be closed.

**Closed as completed by ProbablePrime** 2022-10-11 11:22 UTC
Labels: Duplicate, Enhancement
