### ISSUE TITLE
save dialog for a new generated world does not show in desktop-mode (F8 from VR-Mode)

### ISSUE THREAD

**Issue by Ardescar** [Neos-Metaverse/NeosPublic#3383] opened 2021-11-19 17:46 UTC
### Describe the bug?

it happened for me several times - but i dont know if that happens always.

I create a world in desktop-mode-(F8 from VRmode) and do just test something in there and want to save that new world in my inventory... But the dialog for world save does not appear in desktop. i have to jump back to vr headset to see the dialog. 

This does work in non-vr-mode desktop flawless tho.

While that happens the interaction with anything in world is not possible.

### Relevant issues

didnt find any

### To Reproduce

just go in neos in vr mode and press F8 for desktop and create a new world and try to save it ...

### Expected behavior

that the dialog is visible

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.10.1253

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Ardescar#2046

**Comment by ProbablePrime** [comment] 2021-11-19 19:00
Hey Aredescar this is a duplicate of #2006 so i will be closing it and directing users over there

**Closed** 2021-11-19 19:00 UTC
Labels: Bug, Duplicate, UI
