### ISSUE TITLE
Add universal system for mouth and eye tracking for upcoming headsets like omnicept and decagrear 

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#2815] opened 2021-08-17 12:40 UTC
### Is your feature request related to a problem? Please describe.

There is no universal system and I'm not sure if hp omnicept mouth tracking is supported since I can't find it anywhere being mentioned and once the decagear comes it will also need to be intergrated and could be many in the future but atm it's inconvenient to wait till headsets get intergrated would be nice if we could attach these new things via API and a dll for more of an universal system that users can add support themselves i would like to see this as quickly as possible

### Relevant issues

Yeah the mention in the discord about an API so users can connect hardware to neosvr like eye mouth and so on

### Describe the solution you'd like

Quickly as possible an API that can be used to connect VR hardware to 

### Describe alternatives you've considered

Forcing it to work by any means necessary you know what i mean

### Additional context

Important feature

**Comment by shadowpanther** [comment] 2021-08-17 12:43
Duplicate of #1140

**Closed by shadowpanther** 2021-08-17 12:43 UTC
Labels: Enhancement
